### ISSUE TITLE
Arabic-Indic numerals

### ISSUE THREAD

**Issue by ibr123** [tesseract-ocr/tesseract#858] opened 2017-05-01 09:49 UTC
Hi,

I'm using tesseract 4.00alpha with liptonica 1.74.1 on Ubuntu 14 to create LSTM files for multiple Arabic fonts, which some of them have the common numerical system, (1 2 3 4 ...) but some of these font contains the a different numerical system, which usually more common in the Arabic scripts, 
which are ( ٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩)
yet the last set of numbers were not recognize but as symbols such as ! instead of ١ ,are these numbers are not integrated in the tesseract?
Thanks

**Comment by Shreeshrii** [comment] 2017-05-02 04:12
Ref: 
* https://en.wikipedia.org/wiki/Arabic_numerals
* https://en.wikipedia.org/wiki/Eastern_Arabic_numerals
* https://en.wikipedia.org/wiki/Arabic_script_in_Unicode

> The Arabic numeral glyphs 0–9 are encoded in ASCII and Unicode at positions 0x30 to 0x39, matching up with the second hexadecimal digit for convenience:

> The Eastern Arabic numerals (also called Arabic–Indic numerals and Arabic Eastern numerals) are the symbols used to represent the Hindu–Arabic numeral system, in conjunction with the Arabic alphabet. 

> Each numeral in the Persian variant has a different Unicode point even if it looks identical to the Eastern Arabic numeral counterpart. However the variants used with Urdu, Sindhi, and other South Asian languages are not encoded separately from the Persian variants. 

> See U+0660 through U+0669 and U+06F0 through U+06F9.

So, basically, there are three unicode ranges with numerals used in Arabic, Persian etc.

* 0x30 to 0x39
* U+0660 through U+0669 
* U+06F0 through U+06F9

If the fonts are putting ` Eastern Arabic numerals` in the 'Arabic numerals' range of 0x30 to 0x39, that would cause confusion during training.

https://github.com/tesseract-ocr/langdata/blob/master/ara/ara.training_text has  'Arabic numerals' range of 0x30 to 0x39. You can check whether it as  ( ٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩) and add it, if you want to include it for training.

**Comment by amitdo** [comment] 2017-05-02 06:37
If that numerals are indeed missing from the official traineddata, I suggest to open a new issue in the langdata repo.

**Comment by aboelmor** [comment] 2017-07-29 04:41
Did Anyone fix this problem? I am not using Unix in order to be able to train tesseract on new data, but I need to use the Eastern arabic numerals. if someone fixed it and has the traineddata file, please share it with us

Thanks

**Comment by reza1615** [comment] 2017-08-05 14:37
Persian's number's shape mostly the same as Arabic's but their Unicode is different!
Persian numbers= ۹ ۸ ۷ ۶ ۵ ۴ ۳ ۲ ۱ ۰
Arabic numbers = ٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩
Persian numbers' Unicode= \u06F9 \u06F8 \u06F7 \u06F6 \u06F5 \u06F4 \u06F3 \u06F2 \u06F1 \u06F0
Arabic numbers' Unicode =\u0660 \u0661 \u0662 \u0663 \u0664 \u0665 \u0666 \u0667 \u0668 \u0669
you can check them [here](https://r12a.github.io/apps/conversion/)

**Comment by Shreeshrii** [comment] 2017-08-05 14:47
@reza1615 

Are these getting recognized in the best traineddata? 
Are they being recognized as Arabic unicode numbers?

**Comment by reza1615** [comment] 2017-08-05 14:53
Yes, it mixed Persian with Arabic numbers (unicode) for example the image had these numbers
۱-۲ and it recognize ۱ as Persian number and ۲ as Arabic number their shape is the same but for searching and Unicode, they are different.
in another hand 3 and 4 and 5 and 6's shape are not the same see below
6 5 4 3
۶ ۵ ۴ ۳
٣ ٤ ٥ ٦ 
you can check it at [here](https://github.com/tesseract-ocr/tessdata/issues/70#issuecomment-320441157)

**Comment by reza1615** [comment] 2017-08-05 15:05
for more information see [Unicode Number, Decimal Digit' Category](http://www.fileformat.info/info/unicode/category/Nd/list.htm)

**Comment by Shreeshrii** [comment] 2017-08-05 15:08
@theraysmith 
Please update the desired characters for persian for the persian unicode range of numbers and ignore the unicode arabic number range for fas (persian), as mentioned above. Thanks!

**Comment by reza1615** [comment] 2017-08-05 15:41
usually, people use the un-standard keyboard (Arabic keyboard for typing Persian text) so there are many scan images of Persian's text  which have Arabic numbers like ٣ ٤ ٥ ٦  but the OCR should convert them to Persian Unicode

**Comment by Shreeshrii** [comment] 2017-08-08 01:50
Question from Ray in tesseract-ocr/langdata#72

> Anyone know which digits are needed for the other Arabic languages?
kur_ara, pus, uig

**Comment by amitdo** [comment] 2017-09-12 11:20
@zdenop, please close this issue.

The issue is related to the trained **data**. not code.

As said, the right place for this issue is the langdata repo.
See https://github.com/tesseract-ocr/langdata/issues/71, https://github.com/tesseract-ocr/langdata/issues/72

**Closed** 2017-09-12 11:32 UTC

**Comment by AbdelsalamHaa** [comment] 2018-05-04 07:13
Hi guys . I'm trying to find the traineddata fot arabic numbers only , can any body guide me where to find it thank you 

im using tesseract 4 visual studio 2017 c++

**Comment by rockerbaba** [comment] 2018-10-21 11:01
Hey there i am been trying to setup OCR for Arabic language in tesseract js but i am getting this error. i couldnt even get a replay through the support. 
![rymbl](https://user-images.githubusercontent.com/7455689/47266047-292a5c80-d542-11e8-9ba1-1a2c5ddcd60a.jpg)
