### ISSUE TITLE
Wrong format of the man-pages

### ISSUE THREAD

**Issue by moubctez** [tesseract-ocr/tesseract#2089] opened 2018-11-29 09:21 UTC
### Environment

* **Tesseract Version**: 4.0.0
* **Commit Number**:
* **Platform**: all

### Current Behaviour:
Man-pages are not formatted properly using `asciidoc`. They contain XML tags, not the actual man-page structure.

### Expected Behaviour:
Man-pages are formatted accordingly.

### Suggested Fix:
Use a2x (part of `asciidoc` package) and patch doc/Makefile.am
```
--- doc/Makefile.am.orig	2018-11-29 08:57:43.000000000 +0000
+++ doc/Makefile.am
@@ -2,7 +2,7 @@
 
 if ASCIIDOC
 
-asciidoc=asciidoc -d manpage
+asciidoc=a2x -f manpage
 
 
 man_MANS = \
@@ -36,7 +36,7 @@ EXTRA_DIST = $(man_MANS) Doxyfile
 html: $(patsubst %,%.html,$(man_MANS))
 
 %: %.asc
-	$(asciidoc) -o $@ $<
+	$(asciidoc) $<
 
 %.html: %.asc
 	asciidoc -b html5 -o $@ $<
```

**Comment by stweil** [comment] 2018-11-29 09:33
Yes, that's a known issue which should be fixed. Debian / Ubuntu currently uses a local patch to get man pages.

The problem is that the fix also requires a dtd file, for example `docbookx.dtd` on my Debian stretch.

**Comment by cjmayo** [comment] 2019-01-31 20:16
If changing to use docbook.xsl please consider using the location `http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl` as in #2209 for maximum compatibility.

**Comment by zdenop** [comment] 2019-02-02 19:44
Is the issue solved with https://github.com/tesseract-ocr/tesseract/pull/2212

**Comment by stweil** [comment] 2019-02-02 21:20
I assume so. @moubctez, can we close this issue?

**Closed** 2019-02-19 11:29 UTC
Labels: bug
