### ISSUE TITLE
Text in generated PDF in wrong order

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#170] opened 2015-12-11 06:21 UTC
The characters in the attached image are recognized by Tesseract, but placed in a wrong order when generating a PDF file (which prevents searching in the PDF):

    $ tesseract pdf-test.jpg pdf-test pdf
    $ pdftotext pdf-test.pdf -
    ra
    me
    ka
    ot
    ar
    fr
    In
    en
    ch
    is
    om
    on
    tr
    as
    r
    ne
    ei
    g
    un
    ob
    pr
    Bau und Er

The original text scan is not exactly horizontal (-0.5°). If this is fixed before doing OCR, Tesseract creates a PDF with the correct text.

![pdf-test](https://cloud.githubusercontent.com/assets/6734573/11728560/df7dfa46-9f8a-11e5-949c-6ff549c62f1d.jpg)

**Comment by jbreiden** [comment] 2015-12-12 00:36
I suspect the problem is in pdftotext. To find out, open the PDF in another viewer such as Chrome or Adobe Reader and see what you get during search and copy-paste.

**Comment by jbreiden** [comment] 2015-12-12 00:47
Confirmed. Poppler (used by pdftotext) has a very hard time with titled text. If you want Tesseract to be more aggressive at producing flat text lines for tilted images, modify ClipBaseline(). But a better approach is to to use a different text extractor, for example one based on PDFium.

https://github.com/tesseract-ocr/tesseract/blob/master/api/pdfrenderer.cpp#L275

**Comment by jbreiden** [comment] 2015-12-12 01:29
And finally, if you want to post-process Tesseract produced PDF to flatten out tilted textlines, that's also fairly easy. Just ask if you need details.

**Comment by stweil** [comment] 2015-12-12 07:32
`evince` (my standard PDF viewer on Linux) has the same problem and is not able to search such PDFs. The PDF viewer of `iceweasel` / `Firefox` gets the words right, so it is possible to search 'Infrarotkamera', but not the lines, so searching for word combinations does not work.

**Comment by amitdo** [comment] 2015-12-12 14:23
Evince's pdf support is based on Poppler.

https://en.wikipedia.org/wiki/Evince#Supported_document_formats
https://en.wikipedia.org/wiki/Poppler_%28software%29

**Comment by stweil** [comment] 2015-12-12 14:36
Maybe Firefox also uses parts of the Poppler code. So there are a number of PDF viewers which are less robust in getting correct text lines from a Tesseract PDF. Wikipedia shows that the list of these viewers is quit impressive. This increases my wish to understand and fix what goes wrong in Tesseract's PDF generation process.

**Comment by stweil** [comment] 2015-12-12 14:42
I just tested with Chromium (Debian's variant of Chrome). It gets the text better, but not good: "astronomischen Infrarotkamera" is not found because it is split in separate lines.

**Comment by amitdo** [comment] 2015-12-12 14:51
> Maybe Firefox also uses parts of the Poppler code. 

No.
https://github.com/mozilla/pdf.js

**Comment by amitdo** [comment] 2015-12-12 15:49
Chromium uses PDFium:
https://pdfium.googlesource.com/pdfium/
https://news.ycombinator.com/item?id=7781878
http://blog.foxitsoftware.com/foxit-pdf-technology-chosen-for-google-open-source/
https://groups.google.com/forum/#!forum/pdfium

**Comment by jbreiden** [comment] 2015-12-13 05:34
![tilt](https://cloud.githubusercontent.com/assets/4961958/11765657/b19b4bf6-a115-11e5-97d3-d8ec63256afc.png)

There's nothing invalid with the PDF files produced; tilted symbolic text lines are legitimate in PDF. They are the accurate representation of OCR results. The words are inside there just fine, along with some geometry describing the angle of the baseline. That said, this does blow the mind of some PDF simple minded text extractors who assume that it is impossible for a line of text to have any deviation of y-position between characters. (As you might imagine, this gets particularly fun with vertical Japanese text.)

You have exactly three choices if you want to better compatibility these viewers. One is to deskew the image before calling OCR. Second is modifying the section of code I pointed to earlier in Tesseract, to eliminate tilt in the symbolic text lines. Third is to remove the tilt in the invisible symbolic text lines, after the PDF is produced. All three of these approaches are relatively easy for a programmer and I'm happy to provide guidance.

There are major problems of forcing heavily titled text lines to be flat, a big one being
word highlightling ends up in the wrong place visually. So I would be reluctant to do that by default.

**Comment by stweil** [comment] 2015-12-13 09:07
There must be some other aspect of the original scan, because Tesseract generates a PDF which works perfectly with all viewers and with pdftotext from this generated image with the same tilted text:
![generated-image](https://cloud.githubusercontent.com/assets/6734573/11766292/348dd4d2-a181-11e5-80a5-b12946a7ca44.jpg)

**Comment by amitdo** [comment] 2015-12-13 09:17
Poppler homepage
http://poppler.freedesktop.org/

Maybe someone wants to fill a bug report?
>Use [bugzilla](http://bugs.freedesktop.org/) to report bugs or suggest enhancements. The component is `poppler`.

From the [TODO](http://cgit.freedesktop.org/poppler/poppler/tree/TODO):
> - Investigate better (that is, normal) text selection.

**Comment by amitdo** [comment] 2015-12-13 09:33
@stweil, what @jbreiden is saying is that some pdf viewer have bugs that make them present skewed text lines incorrectly

**Comment by stweil** [comment] 2015-12-13 09:44
Ok. Let me explain what I have understood. Obviously it is not possible to describe a rotated text line in PDF, so you have either to pretend that the line is horizontal (that's what ABBYY does with the original image and Tesseract does with the generated image), or you have to approximate the rotation by splitting the text line into smaller parts with different y values (which is causing trouble with most or even all free PDF viewers, at least those that are based on Poppler, Mozilla or PDFium).

I noticed a 2nd difference between ABBYY and Tesseract PDF: with Evince, selected text from the Tesseract PDF is shown as a simple blue rectangle, while in the ABBYY PDF it also shows the characters with some built-in font. But that's a different story.

**Comment by jbreiden** [comment] 2015-12-13 19:28
@stweil: You are misunderstanding. It is possible to describe a rotated text line in PDF. Tesseract does exactly this for any text line whose tilt is large enough. The tilted screenshot in Hebrew above is Tesseract output, displayed in Adobe Reader. You can even see the tilted text being highlighted for copy-paste in all their tilted glory. I point everyone again at the critical piece of code that explains the situation. It effectively says, 'Does the vertical displacement between the beginning and end of the baseline exceed 2 pts? (2 pts = 1 / 36 inch) If so, pretend the line is horizontal. Otherwise, faithfully record it as tilted.

https://github.com/tesseract-ocr/tesseract/blob/master/api/pdfrenderer.cpp#L275

P.S. While there is a prayer that Poppler will evolve, my best guess is it will instead be replaced with PDFium some time over the next 10 years. PDFium is by no means perfect, but it is much stronger than Poppler.

**Comment by jbreiden** [comment] 2016-02-02 18:48
I am going to close this issue soon, as working as intended. If people think the 
threshold should be increased, that's a reasonable thing to discuss. Right if
a text line has 2pts or less vertical displacement, we draw it totally flat. Maybe
that number should be 3pts.

**Closed** 2016-02-03 23:10 UTC

**Comment by ravidocs** [comment] 2017-06-15 21:30
I have similar problem while extracting data from pdf, it splits into one or two characters per line.  I tried using TESS4J which gets the text much better. So trying to find if there is any options in tesseract(java) i could use.

Thanks
