### ISSUE TITLE
Can't train on new font installed in ~/.fonts

### ISSUE THREAD

**Issue by faizan1041** [tesseract-ocr/tesseract#2163] opened 2019-01-17 07:55 UTC
I have following version installed on Ubuntu 18.04:
tesseract 4.0.0-beta.1
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX
 Found SSE

With tesstrain.sh, my training till lstmtraining stop went smooth by trying one of the fonts from /usr/share/fonts . I placed this font: [Anyline_Capitals](https://anyline.com/free-ocr-font/) inside my ~/.fonts folder and tried this command by changing fonts_dir and fontlist arguments:

`/usr/share/tesseract-ocr/tesstrain.sh --fonts_dir /root/.fonts --lang eng --linedata_only   --noextract_font_properties --langdata_dir ~/langdata   --tessdata_dir /usr/share/tesseract-ocr/4.00/tessdata --output_dir ~/tesstutorial/engtrain --fontlist 'Anyline_Capitals'`

which generated errors as shown in the log below:

```
=== Starting training for language 'eng'
[Thu Jan 17 06:35:28 UTC 2019] /usr/bin/text2image --fonts_dir=/root/.fonts --font=Anyline_Capitals --outputbase=/tmp/font_tmp.Bk2zXPFB2z/sample_text.txt --text=/tmp/font_tmp.Bk2zXPFB2z/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.Bk2zXPFB2z
Stripped 1 unrenderable words
Rendered page 0 to file /tmp/font_tmp.Bk2zXPFB2z/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using Anyline_Capitals
[Thu Jan 17 06:35:29 UTC 2019] /usr/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.Bk2zXPFB2z --fonts_dir=/root/.fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0 --max_pages=3 --font=Anyline_Capitals --text=/root/langdata/eng/eng.training_text
Stripped 446 unrenderable words
Rendered page 0 to file /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif
Stripped 431 unrenderable words
Rendered page 1 to file /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif
Stripped 279 unrenderable words
Rendered page 2 to file /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!

=== Phase UP: Generating unicharset and unichar properties files ===
[Thu Jan 17 06:35:32 UTC 2019] /usr/bin/unicharset_extractor --output_unicharset /tmp/tmp.RFFbW2BgH1/eng/eng.unicharset --norm_mode 1 /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.box
Failed to read data from: /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.box
Wrote unicharset file /tmp/tmp.RFFbW2BgH1/eng/eng.unicharset
[Thu Jan 17 06:35:32 UTC 2019] /usr/bin/set_unicharset_properties -U /tmp/tmp.RFFbW2BgH1/eng/eng.unicharset -O /tmp/tmp.RFFbW2BgH1/eng/eng.unicharset -X /tmp/tmp.RFFbW2BgH1/eng/eng.xheights --script_dir=/root/langdata
Loaded unicharset of size 3 from file /tmp/tmp.RFFbW2BgH1/eng/eng.unicharset
Setting unichar properties
Setting script properties
Writing unicharset to file /tmp/tmp.RFFbW2BgH1/eng/eng.unicharset

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
[Thu Jan 17 06:35:32 UTC 2019] /usr/bin/tesseract /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0 lstm.train
Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
Page 1
Failed to read boxes from /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif
Page 2
Deserialize header failed: /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.lstmf
Failed to read training data from /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.lstmf!
Page 3
Deserialize header failed: /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.lstmf
Failed to read training data from /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.lstmf!
ERROR: /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.lstmf does not exist or is not readable
```

**Comment by Shreeshrii** [comment] 2019-01-24 09:45
```
Rendering using Anyline_Capitals
[Thu Jan 17 06:35:29 UTC 2019] /usr/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.Bk2zXPFB2z --fonts_dir=/root/.fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0 --max_pages=3 --font=Anyline_Capitals --text=/root/langdata/eng/eng.training_text
Stripped 446 unrenderable words
Rendered page 0 to file /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif
Stripped 431 unrenderable words
Rendered page 1 to file /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif
Stripped 279 unrenderable words
Rendered page 2 to file /tmp/tmp.RFFbW2BgH1/eng/eng.Anyline_Capitals.exp0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
```

try converting your training text to ALL CAPITALS - uppercase letters and then retry. It seems that your font only supports CAPITALS hence lots of words are getting dropped. If there are no words on a page, then you will get 

Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!

**Comment by Shreeshrii** [comment] 2019-03-01 13:45
@faizan1041 If issue is solved, please close.

**Comment by Shreeshrii** [comment] 2019-04-13 08:24
Duplicate of https://github.com/tesseract-ocr/tesseract/issues/1902

@zdenop Please close.

**Closed** 2019-04-13 09:03 UTC
