### ISSUE TITLE
Clustering error: Matrix inverse failed with error

### ISSUE THREAD

**Issue by jeneser** [tesseract-ocr/tesseract#1111] opened 2017-09-06 15:19 UTC
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below. 

------------------------

### Environment

* **Tesseract Version**: 
```
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0
```

* **Commit Number**: 
(Install it from ubuntu apt. `sudo apt install tesseract-ocr`)

* **Platform**: 
```
Linux jeneser-X555LF 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Current Behavior:
When run the following command. An error has occurred.
```
cntraining hpu.font.exp0.tr
```
BUT, continue running commands, all is successfully.

My console:
```
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ tesseract hpu.font.exp0.tif hpu.font.exp0 box.train
Tesseract Open Source OCR Engine v3.04.01 with Leptonica
Page 1
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 2
Empty page!!
Page 3
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 4
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 5
Empty page!!
Page 6
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 7
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 2 words
Page 8
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 9
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 10
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 11
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 12
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 13
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
   Leaving 2 unlabelled blobs in 0 words.
Generated training data for 1 words
Page 14
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 15
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 16
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 17
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 18
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 19
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 20
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 21
FAIL!
APPLY_BOXES: boxfile line 1/q ((0,0),(15,20)): FAILURE! Couldn't find a matching blob
FAIL!
APPLY_BOXES: boxfile line 2/y ((15,0),(30,20)): FAILURE! Couldn't find a matching blob
FAIL!
APPLY_BOXES: boxfile line 3/j ((30,0),(45,20)): FAILURE! Couldn't find a matching blob
FAIL!
APPLY_BOXES: boxfile line 4/h ((45,0),(60,20)): FAILURE! Couldn't find a matching blob
APPLY_BOXES:
   Boxes read from boxfile:       4
   Boxes failed resegmentation:       4
APPLY_BOXES: Unlabelled word at :Bounding box=(0,0)->(60,20)
   Found 0 good blobs.
   1 remaining unlabelled words deleted.
Generated training data for 0 words
Page 22
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 23
FAIL!
APPLY_BOXES: boxfile line 1/h ((3,0),(17,20)): FAILURE! Couldn't find a matching blob
FAIL!
APPLY_BOXES: boxfile line 2/t ((17,0),(31,20)): FAILURE! Couldn't find a matching blob
FAIL!
APPLY_BOXES: boxfile line 3/m ((31,0),(45,20)): FAILURE! Couldn't find a matching blob
FAIL!
APPLY_BOXES: boxfile line 4/X ((45,0),(59,20)): FAILURE! Couldn't find a matching blob
APPLY_BOXES:
   Boxes read from boxfile:       4
   Boxes failed resegmentation:       4
APPLY_BOXES: Unlabelled word at :Bounding box=(3,0)->(60,20)
   Found 0 good blobs.
   1 remaining unlabelled words deleted.
Generated training data for 0 words
Page 24
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
   Leaving 2 unlabelled blobs in 0 words.
Generated training data for 2 words
Page 25
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 26
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 27
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 28
row xheight=8.66667, but median xheight = 10
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 29
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
Page 30
APPLY_BOXES:
   Boxes read from boxfile:       4
   Found 4 good blobs.
Generated training data for 1 words
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ unicharset_extractor hpu.font.exp0.box
Extracting unicharset from hpu.font.exp0.box
Wrote unicharset file ./unicharset.
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ mftraining -F font_properties -U unicharset -O hpu.unicharset hpu.font.exp0.tr
Warning: No shape table file present: shapetable
Failed to load font_properties from font_properties
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ mftraining -F font_properties -U unicharset -O hpu.unicharset hpu.font.exp0.tr
Warning: No shape table file present: shapetable
Reading hpu.font.exp0.tr ...
Flat shape table summary: Number of shapes = 45 max unichars = 1 number with multiple unichars = 0
Warning: no protos/configs for Joined in CreateIntTemplates()
Warning: no protos/configs for |Broken|0|1 in CreateIntTemplates()
Warning: no protos/configs for j in CreateIntTemplates()
Done!
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ cntraining hpu.font.exp0.tr
Reading hpu.font.exp0.tr ...
Clustering ...
Clustering error: Matrix inverse failed with error 1.44922

Writing normproto ...
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ cntraining hpu.font.exp0.tr
Reading hpu.font.exp0.tr ...
Clustering ...
Clustering error: Matrix inverse failed with error 1.44922

Writing normproto ...
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ mv normproto hpu.normproto
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ mv inttemp hpu.inttemp
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ mv pffmtable hpu.pffmtable
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ mv shapetable hpu.shapetable
jeneser@jeneser-X555LF:~/workSpace/fsociety-hpu/training/training-it$ combine_tessdata hpu.
Combining tessdata files
TessdataManager combined tesseract data files.
Offset for type  0 (hpu.config                ) is -1
Offset for type  1 (hpu.unicharset            ) is 140
Offset for type  2 (hpu.unicharambigs         ) is -1
Offset for type  3 (hpu.inttemp               ) is 2644
Offset for type  4 (hpu.pffmtable             ) is 331290
Offset for type  5 (hpu.normproto             ) is 331653
Offset for type  6 (hpu.punc-dawg             ) is -1
Offset for type  7 (hpu.word-dawg             ) is -1
Offset for type  8 (hpu.number-dawg           ) is -1
Offset for type  9 (hpu.freq-dawg             ) is -1
Offset for type 10 (hpu.fixed-length-dawgs    ) is -1
Offset for type 11 (hpu.cube-unicharset       ) is -1
Offset for type 12 (hpu.cube-word-dawg        ) is -1
Offset for type 13 (hpu.shapetable            ) is 337236
Offset for type 14 (hpu.bigram-dawg           ) is -1
Offset for type 15 (hpu.unambig-dawg          ) is -1
Offset for type 16 (hpu.params-model          ) is -1
Output hpu.traineddata created successfully.
```

### Suggested Fix:

Thanks!

**Comment by Shreeshrii** [comment] 2017-09-06 15:46
What language are you trying to train?

Have you checked whether new trained data is available for it in teesara
repository?

You should try with a newer version of tesseract. Look for tesseract OCR
ppa by alex.

**Comment by amitdo** [comment] 2017-09-06 15:53
duplicate of #771

**Comment by jeneser** [comment] 2017-09-07 02:41
> What language are you trying to train?

I want to re-train tesseract for a specific language. It contains `numbers` and `English letters`.
like: 

![30](https://user-images.githubusercontent.com/15034042/30143429-4d3e376c-93b8-11e7-9f7e-1cf8fa087247.jpeg)

> Have you checked whether new trained data is available for it in teesara
repository?

Yes, the new trained data is *available*.

data:
[hpu.traineddata.zip](https://github.com/tesseract-ocr/tesseract/files/1283315/hpu.traineddata.zip)

> You should try with a newer version of tesseract. Look for tesseract OCR
ppa by alex.

Yep, i will try it.

**Closed** 2018-09-29 07:07 UTC
Labels: duplicate
