### ISSUE TITLE
Segmentation fault ("Speicherzugriffsfehler") caused by "fast" traineddata

### ISSUE THREAD

**Issue by M3ssman** [tesseract-ocr/tesseract#2921] opened 2020-03-05 11:21 UTC
Hello,

I have 2 tesstrain-installations, one on a local machine, another on a virtual VM provided by our IT-SP.

Setup contains a small sample (tif+gt) for about 10-20 lines.

The local version runs fine and produces a final model, whereas the VM fails with (excerpt from [2020-03-05-tesstrain-mem.log](https://github.com/tesseract-ocr/tesstrain/files/4292613/2020-03-05-tesstrain-mem.log))

```
Continuing from data/frk/ulbzd.lstm
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0019.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0020.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0009.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0000.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0018.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0014.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0000_region0000_line0000.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0015.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0016.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0001_region0001_line.lstmf
Loaded 1/1 lines (1-1) of document /home/gitlab-runner/builds/tfDssL8r/0/aqayv/ulb-dd-ocr-training/data/ulbzd_latest/LINES_0001_region0002_region0002_line0006.lstmf
Makefile:248: recipe for target 'data/ulbzd/checkpoints/ulbzd_checkpoint' failed
make: *** [data/ulbzd/checkpoints/ulbzd_checkpoint] Speicherzugriffsfehler (Speicherauszug erstellt)

```

Both same OS (Ubuntu 18.04.03 LTS), same tesseract () and same python(venv)+Pillow.

Any suggestions welcome!

**Comment by M3ssman** [comment] 2020-03-13 16:06
@stweil 
Thanks very much! 
Great Job!
I can confirm that it works on my local machine the way you've pointed out!

**Comment by M3ssman** [comment] 2020-03-16 12:32
@stweil 
It also breaks with `frk.traineddata` model from https://github.com/tesseract-ocr/tessdata/blob/master/frk.traineddata which is quite large (up to 21 MB)

One has really stick to the fractur-Model from https://github.com/tesseract-ocr/tessdata_best/raw/master/frk.traineddata

**Comment by stweil** [comment] 2020-03-18 20:46
That's expected behaviour. Like `tessdata_fast`, `tessdata` contains fast models which don't work with training. In addition most of those models also contain data for the old recognizer.

**Comment by amitdo** [comment] 2020-04-24 06:37
>Tesseract should be fixed to handle the wrong kind of traineddata with a user friendly error message instead of crashing.

Duplicate of #1573.

**Closed by amitdo** 2020-04-24 06:37 UTC
