### ISSUE TITLE
Invalid characters with Tesseract 5.1.0 and tessdata_fast data (for German version) when using 32-bit Microsoft compiler

### ISSUE THREAD

**Issue by krzysiekj94** [tesseract-ocr/tesseract#3769] opened 2022-03-17 11:24 UTC
### Environment

* **Tesseract Version**: 5.1.0
* **Platform**: Windows 32-bit 

### Current Behavior:
I have the following problem:
1. I prepared a custom build for Tesseract 5.1.0, so as to generate dlls, which I then use in the project of a 32-bit .exe application.
2. I prepared the following dependencies with CMake 3.23 (without SW build): 
a. tesseract 5.1.0, leptonica 1.82.0, libtiff 4.3.0, libjpeg-turbo 2.1.3, zlib 1.2.11, libpng 1.6.37.
b. Links to src:
- tesseract 5.1.0 (https://github.com/tesseract-ocr/tesseract/releases) – 01.03.2022
- leptonica 1.82.0 (http://www.leptonica.org/download.html) – 22.09.2021
- libtiff 4.3.0 (http://download.osgeo.org/libtiff) – 20.04.2021
- libjpeg-turbo 2.1.3 (https://github.com/libjpeg-turbo/libjpeg-turbo/releases ) – 25.02.2022
- zlib 1.2.11 (https://github.com/madler/zlib/tags) – 15.01.2017
- libpng 1.6.37 (https://github.com/glennrp/libpng/releases/tag/v1.6.37) – 14.04.2019
c. I also fix CMakeList.txt a bit for tesseract to be able to generate .dll files - see: 
[CMakeLists.txt](https://github.com/tesseract-ocr/tesseract/files/8284026/CMakeLists.txt)
3. After generating the dependencies, I used them in a wrapper that uses CAPI and generated a dll file (also 32 bit) that I used in the application. The list of all dependencies is as follows:
![image](https://user-images.githubusercontent.com/12548678/158794280-5d048760-5419-49e3-bd8a-110fa0dc0640.png)
4. In the next step, I performed an OCR test in the application with tessdata germany data - deu.traineddata model: https://github.com/tesseract-ocr/tessdata_fast. 
5. At this point, I noticed inferior recognition quality compared to the Tesseract 4.1.1 version, which I used earlier. 
![image](https://user-images.githubusercontent.com/12548678/158797464-585c773a-f264-467b-9e56-a7dfefd25d3a.png)
a. test file: 
![test_file](https://user-images.githubusercontent.com/12548678/158796308-0e0e8e57-ad24-4eb5-b70a-0c6b99722663.png)
6. I noticed that there is also a problem with slash, for example: It is then changed to "jj" - see:
![image](https://user-images.githubusercontent.com/12548678/158798504-3bae659a-d0cd-434b-83ac-2de69ddb87dd.png)
7. I would like to add that I have also prepared a Tesseract 4.1.1 compilation with the dependencies as in point 2b. The quality of OCR did not change then.
8. I use tessdata_best as a temporary workaround (and it work), but the OCR speed for this model is not satisfactory for me.

### Expected Behavior:
I expect Tesseract 5.1.0 to recognize characters correctly, ie not converting "l", "m" to "j" or "i" to "j" for example in the tessdata_fast mode. I would like character recognition to work similar to Tesseract 4.1.1.

### Suggested Fix:
Consideration of an upgrade for deu.traineddata models on the website:
https://github.com/tesseract-ocr/tessdata_fast

**Comment by stweil** [comment] 2022-03-17 13:24
Tesseract 5 still supports the model files from Tesseract 4 with the "legacy mode", so if you are happy with that, you can use it.

**Comment by stweil** [comment] 2022-03-17 13:29
@krzysiekj94, I get a different result:

```
tesseract https://user-images.githubusercontent.com/12548678/158796308-0e0e8e57-ad24-4eb5-b70a-0c6b99722663.png - -l tessdata_fast/deu
 

Siegfried Aalfelden
Kurt-Schumacher-Platz 10
13405 Berlin

26.02.2019

 

Sehr geehrter Herr Aalfelden,

Informationen

Das Internet (von englisch internetwork, zusammengesetzt aus dem Präfix inter und
network „Netzwerk“ oder kurz net ‚Netz‘), umgangssprachlich auch Netz, ist ein
weltweiter Verbund von Rechnernetzwerken, den autonomen Systemen. Es ermöglicht
die Nutzung von Internetdiensten wie WWW, E-Mail, Telnet, SSH, XMPP, MOTT und
FTP. Dabei kann sich jeder Rechner mit jedem anderen Rechner verbinden. Der
Datenaustausch zwischen den über das Internet verbundenen Rechnern erfolgt über
die technisch normierten Internetprotokolle. Die Technik des Internets wird durch die
RFCs der Internet Engineering Task Force (IETF) beschrieben.

Die Verbreitung des Internets hat zu umfassenden Umwälzungen in vielen
Lebensbereichen geführt. Es trug zu einem Modernisierungsschub in vielen
Wirtschaftsbereichen sowie zur Entstehung neuer Wirtschaftszweige bei und hat zu
einem grundlegenden Wandel des Kommunikationsverhaltens und der Mediennutzung
im beruflichen und privaten Bereich geführt. Die kulturelle Bedeutung dieser
Entwicklung wird manchmal mit der Erfindung des Buchdrucks gleichgesetzt.

Die Übertragung von Daten im Internet unabhängig von ihrem Inhalt, dem Absender
und dem Empfänger wird als Netzneutralität bezeichnet.

Mit freundlichen Grüßen
```

**Comment by krzysiekj94** [comment] 2022-03-17 14:33
Hello @stweil , thanks for response.  I have more questions now:
1. Where exactly to get the tessdata_fast data for "legacy mode"? 
Based on the documentation https://github.com/tesseract-ocr/tessdata_fast I can see that legacy mode is not supported.
2. Can support legacy for tesseract be enforced when building a solution via CMakeList.txt from CMake? If so, where is that option?
It's my preview of CMake with tesseract: 
![test](https://user-images.githubusercontent.com/12548678/158828205-92c08578-c86b-49d8-9694-6f06eee81947.PNG)
4. On which version of Tesseract did you get the correct result? Where can I get the exact version you used? Is it 32-bit or 64-bit? Can you send a link to this version?
5. Is it possible that there is a different behavior for tessdata_fast on 32-bit and 64-bit versions of Tesseract 5.0.1?
6. Can there be problems with the use of CAPI? Perhaps I should switch to object oriented programming?
Below is an example of initialize a tesseract in my wrapper code:
![image](https://user-images.githubusercontent.com/12548678/158828717-4f906b7e-5f9d-42fb-8240-fc807067ca89.png)
![image](https://user-images.githubusercontent.com/12548678/158828757-3bc642b2-9a74-46cc-903a-393a83bab629.png)

Thanks in advance for your answer! Have a nice day.

**Comment by stweil** [comment] 2022-03-17 15:00
Please try the OCR with the default `tesseract` application. If that works fine (like it does in my test) you have to find out what you have to fix in your application.

**Comment by zdenop** [comment] 2022-03-17 18:03
Legacy model is available only in https://github.com/tesseract-ocr/tessdata.

**Comment by Shreeshrii** [comment] 2022-03-19 02:22
>I use tessdata_best as a temporary workaround (and it work), but the OCR speed for this model is not satisfactory for me.

Then please try, as suggested above, with model from  https://github.com/tesseract-ocr/tessdata which has legacy models as well as the 'fast' version of 'tessdata_best' models. Both are available in the same traineddata file, invoked with different --oem settings.

**Comment by krzysiekj94** [comment] 2022-03-23 16:14
I found one of the articles that seems to be similar to my problem: https://github.com/tesseract-ocr/tesseract/issues/3283
I did one of the tests and changed the option related to O2 optimization **to disabled**.  I was very surprised because disabling /O2 optimization caused OCR to return almost identical texts as in tesseract 4.1.1, which I expected. See below for settings in Visual Studio 2019 and for differences in text:

![image](https://user-images.githubusercontent.com/12548678/159742590-8316158c-0e24-4970-9c4e-04018b6e32f8.png)

![image](https://user-images.githubusercontent.com/12548678/159743609-b3fdbd7a-5334-4a53-9f21-e70f852bd226.png)

Now I have a question: Would it be wise if I compiled tesseractlib 5.1.0 with the /O2 optimization option turned off? Does this have any unexpected consequences? Maybe someone has similar problems and experiences? I feel close to solving the problem.

**Comment by stweil** [comment] 2022-03-23 17:53
Related issues: #2898 and #3283.

**Comment by stweil** [comment] 2022-03-23 17:54
> After installing the Mannheim installation, the OCR seems to form fine, but I don't know where it comes from.

The UB Mannheim binaries are build with the GNU compiler. Therefore they don't have this issue.

**Comment by zdenop** [comment] 2022-03-23 18:41
64bit works for me.:

```
>tesseract -v
tesseract 5.1.0-7-g0e526
 leptonica-1.83.0 (Jan 26 2022, 19:15:03) [MSC v.1929 LIB Release x64]
  libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.0.91) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 2019
 Found libarchive 3.5.1 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6 libzstd/1.4.9
 Found libcurl/7.75.0 zlib/1.2.11 libssh2/1.10.1_DEV
```

```
>tesseract i3769.png - -l tessdata_fast/deu
Siegfried Aalfelden
Kurt-Schumacher-Platz 10
13405 Berlin

26.02.2019

Sehr geehrter Herr Aalfelden,

Informationen

Das Internet (von englisch internetwork, zusammengesetzt aus dem Präfix inter und
network „Netzwerk“ oder kurz net ‚Netz‘), umgangssprachlich auch Netz, ist ein
weltweiter Verbund von Rechnernetzwerken, den autonomen Systemen. Es ermöglicht
die Nutzung von Internetdiensten wie WWW, E-Mail, Telnet, SSH, XMPP, MOTT und
FTP. Dabei kann sich jeder Rechner mit jedem anderen Rechner verbinden. Der
Datenaustausch zwischen den über das Internet verbundenen Rechnern erfolgt über
die technisch normierten Internetprotokolle. Die Technik des Internets wird durch die
RFCs der Internet Engineering Task Force (IETF) beschrieben.

Die Verbreitung des Internets hat zu umfassenden Umwälzungen in vielen
Lebensbereichen geführt. Es trug zu einem Modernisierungsschub in vielen
Wirtschaftsbereichen sowie zur Entstehung neuer Wirtschaftszweige bei und hat zu
einem grundlegenden Wandel des Kommunikationsverhaltens und der Mediennutzung
im beruflichen und privaten Bereich geführt. Die kulturelle Bedeutung dieser
Entwicklung wird manchmal mit der Erfindung des Buchdrucks gleichgesetzt.

Die Übertragung von Daten im Internet unabhängig von ihrem Inhalt, dem Absender
und dem Empfänger wird als Netzneutralität bezeichnet.

Mit freundlichen Grüßen
```

**Comment by krzysiekj94** [comment] 2022-03-24 08:55
Hello @zdenop . 

The problem still exists with the use of \ Ox. OCR returns the same result as the \ O2 flag.

![image](https://user-images.githubusercontent.com/12548678/159877105-1d9cf0be-730d-4f06-895c-7d5573b2905e.png)

![image](https://user-images.githubusercontent.com/12548678/159878300-49bd6475-19a5-4500-a0f4-bd6644f21ac0.png)

**Comment by krzysiekj94** [comment] 2022-03-24 09:25
> 64bit works for me.:
> 
> ```
> >tesseract -v
> tesseract 5.1.0-7-g0e526
>  leptonica-1.83.0 (Jan 26 2022, 19:15:03) [MSC v.1929 LIB Release x64]
>   libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.0.91) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11
>  Found AVX2
>  Found AVX
>  Found FMA
>  Found SSE4.1
>  Found OpenMP 2019
>  Found libarchive 3.5.1 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.6 libzstd/1.4.9
>  Found libcurl/7.75.0 zlib/1.2.11 libssh2/1.10.1_DEV
> ```
> 
> ```
> >tesseract i3769.png - -l tessdata_fast/deu
> Siegfried Aalfelden
> Kurt-Schumacher-Platz 10
> 13405 Berlin
> 
> 26.02.2019
> 
> Sehr geehrter Herr Aalfelden,
> 
> Informationen
> 
> Das Internet (von englisch internetwork, zusammengesetzt aus dem Präfix inter und
> network „Netzwerk“ oder kurz net ‚Netz‘), umgangssprachlich auch Netz, ist ein
> weltweiter Verbund von Rechnernetzwerken, den autonomen Systemen. Es ermöglicht
> die Nutzung von Internetdiensten wie WWW, E-Mail, Telnet, SSH, XMPP, MOTT und
> FTP. Dabei kann sich jeder Rechner mit jedem anderen Rechner verbinden. Der
> Datenaustausch zwischen den über das Internet verbundenen Rechnern erfolgt über
> die technisch normierten Internetprotokolle. Die Technik des Internets wird durch die
> RFCs der Internet Engineering Task Force (IETF) beschrieben.
> 
> Die Verbreitung des Internets hat zu umfassenden Umwälzungen in vielen
> Lebensbereichen geführt. Es trug zu einem Modernisierungsschub in vielen
> Wirtschaftsbereichen sowie zur Entstehung neuer Wirtschaftszweige bei und hat zu
> einem grundlegenden Wandel des Kommunikationsverhaltens und der Mediennutzung
> im beruflichen und privaten Bereich geführt. Die kulturelle Bedeutung dieser
> Entwicklung wird manchmal mit der Erfindung des Buchdrucks gleichgesetzt.
> 
> Die Übertragung von Daten im Internet unabhängig von ihrem Inhalt, dem Absender
> und dem Empfänger wird als Netzneutralität bezeichnet.
> 
> Mit freundlichen Grüßen
> ```

In my case, unfortunately, I can't use the x64 version because I have a 32-bit application that uses Tesseract's .dll's :(

**Comment by amitdo** [comment] 2022-03-24 10:49
Now I have a question: Would it be wise if I compiled tesseractlib 5.1.0 with the /O2 optimization option turned off? Does this have any unexpected consequences?

You tried it yourself with a good result. The expected consequence is much slower program execution.

Which version of MSVC 2019 exactly do you use? If it's not lhe latest one (16.11.11), can you upgrade to the latest one and retest?

If the issue still exist with the latest MSVC 2019 version, I suggest to send a new bug report to Microsoft, or reuse this one: https://developercommunity2.visualstudio.com/t/1336629.

**Comment by amitdo** [comment] 2022-03-25 12:29
This is similar to issue as #3283.

I closed this issue because it seems to be an issue with MSVC, not with Tesseract.

If a future version of MSVC will solve the issue, let us know.

**Comment by krzysiekj94** [comment] 2022-03-25 22:52
At the moment I'm using VS version 16.9.6 (older version) but I compiled on a different computer with the same VS 2019 x86 version. Interestingly, with /O2 optimization, but without AVX2, OCR works fine. Why? I do not know. 

![obraz](https://user-images.githubusercontent.com/12548678/160211821-21263b01-1243-4d64-b30f-31dd19549bef.png)

**Comment by stweil** [comment] 2022-03-26 06:44
> Interestingly, with /O2 optimization, but without AVX2, OCR works fine.

So the Microsoft compiler creates buggy code with `/O2` for [intsimdmatrixavx2.cpp](https://github.com/tesseract-ocr/tesseract/blob/main/src/arch/intsimdmatrixavx2.cpp).

@krzysiekj94, you could try to add `#pragma optimize( "", off )` in that file and test whether that fixes the issue.

**Comment by krzysiekj94** [comment] 2022-03-26 14:12
> > Interestingly, with /O2 optimization, but without AVX2, OCR works fine.
> 
> So the Microsoft compiler creates buggy code with `/O2` for [intsimdmatrixavx2.cpp](https://github.com/tesseract-ocr/tesseract/blob/main/src/arch/intsimdmatrixavx2.cpp).
> 
> @krzysiekj94, you could try to add `#pragma optimize( "", off )` in that file and test whether that fixes the issue. If that works, you could also try `#pragma optimize( "s", on )` as an additional pragma.

Hello @stweil , 

1). It looks like after adding only #pragma optimize( "", off ) in the intsimdmatrixavx2.cpp works - see code and comparing results:
![obraz](https://user-images.githubusercontent.com/12548678/160242178-6a0e51af-4a11-4404-ab01-5608bdde1c1b.png)
![obraz](https://user-images.githubusercontent.com/12548678/160242107-cd5ca7ab-3179-4e2d-bdc2-2b074131e70b.png)

2). After adding only #pragma optimize( "s", on ) in the intsimdmatrixavx2.cpp - you can see that somehow OCR is the worst 

![obraz](https://user-images.githubusercontent.com/12548678/160242456-777403c2-7b30-4063-b238-ad86dd3e5a5d.png)
![obraz](https://user-images.githubusercontent.com/12548678/160242475-30f77f41-2bed-460c-a146-5df9cbd02d7e.png)

3). After adding #pragma optimize( "", off ) and  #pragma optimize( "s", on ) together - I have the same result as when I added only #pragma optimize( "", off )

![obraz](https://user-images.githubusercontent.com/12548678/160242590-9cee300d-beb9-40b6-a39d-a80217ac5b57.png)
![obraz](https://user-images.githubusercontent.com/12548678/160243271-cc905d56-6885-411f-b162-526702f1bfde.png)

**My question is**: I understand that by "you could also try #pragma optimize (" s ", on) as an additional pragma" you mean using these two #pragma together - as in step 3?

**Comment by krzysiekj94** [comment] 2022-03-26 15:16
> > Now I have a question: Would it be wise if I compiled tesseractlib 5.1.0 with the /O2 optimization option turned off? Does this have any unexpected consequences?
> 
> You tried it yourself with a good result. The expected consequence is much slower program execution.
> 
> Which version of MSVC 2019 exactly do you use? If it's not lhe latest one (16.11.11), can you upgrade to the latest one and retest?
> 
> If the issue still exist with the latest MSVC 2019 version, I suggest to send a new bug report to Microsoft, or reuse this one: https://developercommunity2.visualstudio.com/t/1336629.

@amitdo  On version 16.11.11 the problem still recurs. I checked it.

**Comment by stweil** [comment] 2022-03-26 15:27
> **My question is**: I understand that by "you could also try #pragma optimize (" s ", on) as an additional pragma" you mean using these two #pragma together - as in step 3?

Yes, that's right. The first pragma disables the optimization options from your build environment. This was expected to work, but disabling all optimizations might result in bad performance. The second pragma therefore enables size optimization (similar to compiler option `/Os`).

Now those two `pragma` statements should be included conditionally, namely only for 32 bit builds and those compiler versions which show the bug. Maybe you can find out how this can be done with preprocessor conditionals.

**Comment by krzysiekj94** [comment] 2022-03-26 18:05
I have added below a suggestion for a fix VS x86 version 16.5 - 16.11 (https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170). 

See: https://pastebin.com/K1q5PzRf

![obraz](https://user-images.githubusercontent.com/12548678/160251855-dc11a89d-e34d-4806-96f3-b02f0ddb2ba1.png)

**Comment by stweil** [comment] 2022-03-26 20:18
Do you want to send a pull request? Then just add a comment (and an empty line after line 16).

**Comment by zdenop** [comment] 2022-03-27 09:50
The problem is with the 32-bit build only so there should be a check for 64-bit (`_WIN64`) build as `_WIN32 ` is defined for 32 and 64-bit build.

**Comment by amitdo** [comment] 2022-03-27 13:17
In #3283 Windows 10 **64-bit** was used, but the MSVC build is **32-bit**. how can we detect this?

**Comment by stweil** [comment] 2022-03-27 15:02
Only a built time check is needed (`#if ... defined(_WIN32) && !defined(_WIN64) ...`). The resulting 32 bit code fails on both 32 and 64 bit Windows.

**Comment by krzysiekj94** [comment] 2022-03-27 15:18
Hmm, from what I can see after changing the x86 / x64 compilation in combobox, the #pragma section turns on / off - after adding defined (WIN32) - this is probably used by MS to detect compile mode. Maybe it it's way to solve this problem?

![obraz](https://user-images.githubusercontent.com/12548678/160288227-2adec6da-d79a-40c0-9e28-0614645626aa.png)
![obraz](https://user-images.githubusercontent.com/12548678/160288256-49d89d14-177d-4cb7-909a-bcbfc9fa85b6.png)

**Comment by zdenop** [comment] 2022-03-27 16:53
> WIN32 is defined by the SDK or the build environment, so it does not use the implementation reserved namespace

see: https://stackoverflow.com/questions/662084/whats-the-difference-between-the-win32-and-win32-defines-in-c

> The non-underscore WIN32 is not well documented and appears to have no bearing on 32 vs 64 machine type. Standard Visual C++ projects for Windows generally don't appear to use it (it may not be in use at all). 

see: https://stackoverflow.com/questions/17380340/win32-preprocessor-definition-in-64bit-windows-platform/51682888#51682888

Also https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-160 mentions only `_WIN32` / `_WIN64`

**Comment by stweil** [comment] 2022-03-27 17:14
That's right, and it should be sufficient to use only those two official macros (see my previous comment).

**Comment by BJungmann** [comment] 2022-03-27 19:51
> I noticed that after copying the generated Tesseract from a computer without AVX2 support, the problem occurs with copied dll's on a computer that supports AVX2

When I did my tests for #3283, I also tried to disable AVX2 usage with the statement
`avx2_available_ = false;`
in src/arch/simddetect.cpp, line 200. This is where the decision is made at runtime, so it should work on machines that have avx2 available.
This gave good results, and did not slow down that much. So I suggest to enclose this statement in the proper _MSC_VER macros, rather than turning off the optimizations with #pragma optimize.

>  On version 16.11.11 the problem still recurs. I checked it.

Thank you for checking that. So my preferred workaround ist still using VS 2019 with platform toolset v141 (which belongs to VS 2017) - you need no code patch then.

**Comment by krzysiekj94** [comment] 2022-03-27 21:15
Hi @BJungmann,

1). Thanks for the suggestion for the version for VS 2017 version. I made a sample build for version 15.9.45 Community - see below:
![image](https://user-images.githubusercontent.com/12548678/160300836-9360417a-a051-4c35-9ca8-9fc6dc8cd974.png)
2). I did performance tests - here the differences are diametrical excluding optimization in intsimdmatrixavx2.cpp - see below test for 7 page tiff in favor of VS 2017. I haven't checked your patch, but I think it will be above that time as well. 
The OCR results are identical.
![image](https://user-images.githubusercontent.com/12548678/160300870-0c721506-3813-44cb-8025-9700060f1d9a.png)

3). IMO, it seems that any change from #pragma will increase the OCR execution time... 
I saw that you have already reported this problem to the microsoft team, but it has status: "Closed - Not Enough Info" - https://developercommunity2.visualstudio.com/t/1336629. Will you report this issue to microsoft again? I was wondering whether to do it myself, but maybe you already have it in your plans.

**Comment by BJungmann** [comment] 2022-03-28 07:48
Indeed execution time with the avx2_available_ patch is increased, but considerably less than with all optimizations turned off. This is the reason why I still recommend platform toolset v141.
I have no current plans to start a new effort with Microsoft. They like very short demonstration code for bug reports. A short main program and data set that shows wrong results would be feasible. But I do not understand enough details in the tesseract code using the MatrixDotVector functions, to see which call to which function with which data produces different results if executed with AVX2 hardware.

**Comment by amitdo** [comment] 2022-03-30 10:50
@stweil, can you push a workaround for this issue?

**Comment by stweil** [comment] 2022-03-30 14:09
> @stweil, can you push a workaround for this issue?

Something like #3778?

**Comment by amitdo** [comment] 2022-03-30 18:48
Yes :-)

**Closed** 2022-03-31 20:10 UTC
Labels: duplicate, msvc
