### ISSUE TITLE
Document LC_CTYPE for language data

### ISSUE THREAD

**Issue by jeroen** [tesseract-ocr/tesseract#1532] opened 2018-04-26 13:29 UTC
### Environment

* **Tesseract Version**:  any
* **Platform**:  all

There is a [bug report](https://github.com/tesseract-ocr/tesseract/issues/1250) about a problem with loading asian training data, which that might be a bigger problem. It is currently not possible to load asian languages `jpn`, `kor`, etc on a system where `LANG` and locale are set to `en_US.UTF-8`, which is often the default.

A workaround is to set `LC_CTYPE` to `C` before calling `api->Init()` but it is unclear why this is needed and what side effects this has. Also I don't know if it is safe to set it back to `en_US.UTF-8` afterwards.

Some documentation on this would be great.

**Comment by zdenop** [comment] 2018-04-26 13:44
Problem is that people do not read doc. Original issue was documented at ["code.google era":](https://github.com/tesseract-ocr/tesseract/wiki/FAQ#error-illegal-min-or-max-specification)

**Comment by amitdo** [comment] 2018-04-26 14:13
@zdenop, 
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#error-illegal-min-or-max-specification

**Comment by jeroen** [comment] 2018-04-26 14:15
The link you quote talks about `LC_NUMERIC`. I think this is different issue than LC_CTYPE for asian languages?

**Comment by stweil** [comment] 2018-06-22 15:24
Is this a duplicate of issue #1250?

**Closed** 2018-09-30 13:58 UTC
Labels: duplicate
