### ISSUE TITLE
Failed to read continue from: data/checkpoints/MODEL_NAME_checkpoint

### ISSUE THREAD

**Issue by kkanafa** [tesseract-ocr/tesseract#2251] opened 2019-02-16 14:47 UTC
**Tesseract** : 
 tesseract 4.0.0
 Leptonica:  leptonica-1.77.0
 Libs:  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE

**Platform**: Windows 10 , cygwin 64bit

Hello, I was searching for my problem but could not find anything that matches.

While "make training", using OCR-D I got this error :

    Loaded file data/eng/eng.lstm, unpacking...
    Warning: LSTMTrainer deserialized an LSTMRecognizer!
    Code range changed from 111 to 111!
    Num (Extended) outputs,weights in Series:
    1,36,0,1:1, 0
    Num (Extended) outputs,weights in Series:
    C3,3:9, 0
    Ft16:16, 160
    Total weights = 160
    [C3,3Ft16]:16, 160
     Mp3,3:16, 0
     Lfys64:64, 20736
     Lfx96:96, 61824
     Lrx96:96, 74112
     Lfx512:512, 1247232
    Fc111:111, 0
    Total weights = 1404064
    Previous null char=110 mapped to 110
    Continuing from data/eng/eng.lstm
    Loaded 1/1 pages (1-1) of document data/ground-truth/tra1.Arial.exp2.lstmf
    Loaded 1/1 pages (1-1) of document data/ground-truth/tra1.Arial.exp4.lstmf
    Loaded 1/1 pages (1-1) of document data/ground-truth/tra1.Arial.exp1.lstmf
    Loaded 1/1 pages (1-1) of document data/ground-truth/tra1.Arial.exp7.lstmf
    Loaded 1/1 pages (1-1) of document data/ground-truth/tra1.Arial.exp6.lstmf
    Loaded 1/1 pages (1-1) of document data/ground-truth/tra1.Arial.exp0.lstmf
    !int_mode_:Error:Assert failed:in file /cygdrive/d/cyg_pub/devel/tesseract/tesseract-ocr-4.0.0- 
    1.x86_64/src/tesseract-4.0.0/src/lstm/weightmatrix.cpp, line 249
    !int_mode_:Error:Assert failed:in file /cygdrive/d/cyg_pub/devel/tesseract/tesseract-ocr-4.0.0- 
    1.x86_64/src/tesseract-4.0.0/src/lstm/weightmatrix.cpp, line 249
    !int_mode_:Error:Assert failed:in file /cygdrive/d/cyg_pub/devel/tesseract/tesseract-ocr-4.0.0- 
    1.x86_64/src/tesseract-4.0.0/src/lstm/weightmatrix.cpp, line 249
     !int_mode_:Error:Assert failed:in file /cygdrive/d/cyg_pub/devel/tesseract/tesseract-ocr-4.0.0- 
    1.x86_64/src/tesseract-4.0.0/src/lstm/weightmatrix.cpp, line 249
       lstmtraining \
      --stop_training \
      --continue_from data/checkpoints/tra1_checkpoint \
      --traineddata data/tra1/tra1.traineddata \
      --model_output data/tra1.traineddata
       **Failed to read continue from: data/checkpoints/tra1_checkpoint
      make: *** [Makefile:155: data/tra1.traineddata] Error** 1.

Its while executing this command:

	lstmtraining \
	  --traineddata $(PROTO_MODEL) \
          --old_traineddata $(TESSDATA)/$(START_MODEL).traineddata \
	  --continue_from data/$(START_MODEL)/$(START_MODEL).lstm \
	  --net_spec "[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c`head -n1 data/unicharset`]" \
	  --model_output data/checkpoints/$(MODEL_NAME) \
	  --learning_rate 20e-4 \
	  --train_listfile data/list.train \
	  --eval_listfile data/list.eval \
	  --max_iterations 5000

WHERE:

    LOCAL := $(PWD)
    PATH := $(LOCAL)/bin:$(PATH)

    TESSDATA =  $(LOCAL)/data
    MODEL_NAME = tra1
    START_MODEL = eng

     LAST_CHECKPOINT = data/checkpoints/$(MODEL_NAME)_checkpoint
     PROTO_MODEL = data/$(MODEL_NAME)/$(MODEL_NAME).traineddata

I dont know if its neccessary but here is structure of dirs:

    +---ocrd-->makefile and others, eng.traineddata -> **run "make training" from here
    |   +---data        ----->all-lstmf/boxes,list.eval, list.train,unicharset
    |   |   +---checkpoints
    |   |   +---eng   -------->eng. traineddata eng.lstm->files, eng *-dawg->files
    |   |   +---ground-truth-> my unicharset, tif , gt.txt , box , lstm files
    |   |   +---lstmtraining
    |   |   +---output
    |   |   |   \---tra1
    |   |   \---tra1 --> charset size, tra1.traineddata, tra1.unicharset
    |   \---usr

I used chmod 777 and chown on checkpoints (as in Windows changed permissions) but it changed nothing. The eng.traineddata should be new aswell, but it doesnt look like to be a problem if it isnt.
Also changed checkpoints dir location...
Anyone can help with this one please? Fighting with this two days.

I will provide makefile code if neccesary.

**Comment by Shreeshrii** [comment] 2019-02-16 14:54
>!int_mode_:Error:Assert failed:in file /cygdrive/d/cyg_pub/devel/tesseract/tesseract-ocr-4.0.0- 
1.x86_64/src/tesseract-4.0.0/src/lstm/weightmatrix.cpp, line 249

Your old traineddata file needs to be from` tessdata_best` repo. 

If you use the default models from tessdata_fast they will give errors, since they are integerized. So also  the models from tessdata repo which have integerized versions of tessdata_best.

Once the assert is fixed, the checkpoint should be created.

**Comment by kkanafa** [comment] 2019-02-16 15:48
Hah, that's it, thanks a lot, it really helped me.

**Comment by Shreeshrii** [comment] 2019-02-16 15:53
Please close the issue.

**Closed** 2019-02-16 16:52 UTC

**Comment by PoojaKamra** [comment] 2019-05-09 07:45
I am getting the same error. I already have traineddata from best repository. But when i am running the command:
lstmtraining 
--stop_training
 --continue_from /home/administrator/pooja/arafile_checkpoint 
--traineddata /home/administrator/Downloads/tesseract-4.0.0/tessdata/ara.traineddata 
--model_output /home/administrator/pooja/ara.traineddata
It is giving below error:
Loaded file /home/administrator/pooja/arafile_checkpoint, unpacking...
Code range changed from 96 to 85!
Must supply the old traineddata for code conversion!
Failed to read continue from: /home/administrator/pooja/arafile_checkpoint

Please help to resolve it

**Comment by PoojaKamra** [comment] 2019-05-09 12:04
Resolved. I was passing original trained data path in 
--traineddata /home/administrator/Downloads/tesseract-4.0.0/tessdata/ara.traineddata
instead of giving the path of newly created ara.traineddata is given which got generated for my data.

**Comment by cserjam** [comment] 2019-12-02 11:07
I have a similar problem, and I would appreciate any help to solve it.
**Tesseract:**
```
tesseract 5.0.0-alpha
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
```
I tried to train a model from scratch using the instructions from the following two resources.
https://www.endpoint.com/blog/2018/07/09/training-tesseract-models-from-scratch
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#creating-training-data

My unicharset has only 17 characters (since the model I am creating is quite domain specific). But the base language is Japanese.

```
lstmtraining \
 --traineddata ~/tess/scratch/training0/jpn/jpn.traineddata \
 --net_spec "[1,0,0,3 Ct5,5,64 Mp3,3 Lfys128 Lbx256 Lbx256 O1c17]" \
 --model_output ~/tess/scratch/training0/output/jpn/scr \
 --train_listfile ~/tess/scratch/tesst/list.train \
 --eval_listfile ~/tess/scratch/tesst/list.eval \
 --max_iterations 50000
```
The command finished training, and the output was:

```
At iteration 12561/50000/50178, Mean rms=0.4%, delta=0.276%, char train=0.878%, word train=0.808%, skip ratio=0.3%,  New worst char error = 0.878 wrote checkpoint.

Finished! Error rate = 0.087
```
 Then when I try to extract the traineddata file from the final checkpoint file, I get an error message.
```
lstmtraining \
 --stop_training \
 --continue_from ~/tess/scratch/training0/output/jpn/scr_checkpoint \
 --traineddata ~/tess/scratch/training0/jpn/jpn.traineddata \
 --model_output $TESSDATA_PREFIX/scr_jpn_init.traineddata

Loaded file /home/ubuntu/tess/scratch/training0/output/jpn/scr_checkpoint, unpacking...
Failed to read continue from: /home/ubuntu/tess/scratch/training0/output/jpn/scr_checkpoint
```

I tried changing the file permission, but the problem persists.

**Comment by Shreeshrii** [comment] 2019-12-02 14:38
What is the outout of the following?

```
ls -l /home/ubuntu/tess/scratch/training0/output/jpn/scr_checkpoint

lstmeval \
 --traineddata ~/tess/scratch/training0/jpn/jpn.traineddata \
 --model ~/tess/scratch/training0/output/jpn/scr_checkpoint \
 --eval_listfile ~/tess/scratch/tesst/list.eval \
 --verbosity -1

```

**Comment by cserjam** [comment] 2019-12-03 01:13
Here's the output of the commands.
```
ls -l /home/ubuntu/tess/scratch/training0/output/jpn/scr_checkpoint

-rwxrwxr-x 1 ubuntu ubuntu 158540130 Dec  2 09:55 /home/ubuntu/tess/scratch/training0/output/jpn/scr_checkpoint
```

```
lstmeval \
 --traineddata ~/tess/scratch/training0/jpn/jpn.traineddata \
 --model ~/tess/scratch/training0/output/jpn/scr_checkpoint \
 --eval_listfile ~/tess/scratch/tesst/list.eval \
 --verbosity -1

/home/ubuntu/tess/scratch/training0/output/jpn/scr_checkpoint is not a recognition model, trying training checkpoint...
Loaded 1/1 lines (1-1) of document /home/ubuntu/tess/scratch/tesst/image4552.lstmf
Loaded 4/4 lines (1-4) of document /home/ubuntu/tess/scratch/tesst/image3468.lstmf
Deserialize failed
```

**Comment by Shreeshrii** [comment] 2019-12-03 04:50
```
lstmtraining \
 --traineddata ~/tess/scratch/training0/jpn/jpn.traineddata \
 --net_spec "[1,0,0,3 Ct5,5,64 Mp3,3 Lfys128 Lbx256 Lbx256 O1c17]" \
 --model_output ~/tess/scratch/training0/output/jpn/scr \
 --train_listfile ~/tess/scratch/tesst/list.train \
 --eval_listfile ~/tess/scratch/tesst/list.eval \
--debug_interval 1 \
 --max_iterations 50500
```

PLease try the above to continue from your earlier checkpoint at 50000 iteration for another 500 with debug info for every iteration.

**Comment by Shreeshrii** [comment] 2019-12-03 04:52
Also try the following:

```
lstmtraining \
 --stop_training \
 --continue_from ~/tess/scratch/training0/output/jpn/scr_checkpoint \
 --traineddata ~/tess/scratch/training0/jpn/jpn.traineddata \
 --model_output $TESSDATA_PREFIX/scrjpninit.traineddata
```

No `_` in the output traineddata (I remember having had issues when the output file name had _ in it).

**Comment by cserjam** [comment] 2019-12-03 08:47
Hi and thanks again for the reply Shreeshrii. I tried to resume training using your first command, but got the below output, presumably because I don't have java (I am running tesseract on an ec2 instance).
```
lstmtraining \
 --traineddata ~/tess/scratch/training0/jpn/jpn.traineddata \
 --net_spec "[1,0,0,3 Ct5,5,64 Mp3,3 Lfys128 Lbx256 Lbx256 O1c17]" \
 --model_output ~/tess/scratch/training0/output/jpn/scr \
 --train_listfile ~/tess/scratch/tesst/list.train \
 --eval_listfile ~/tess/scratch/tesst/list.eval \
--debug_interval 1 \
 --max_iterations 50500

Loaded file /home/ubuntu/tess/scratch/training0/output/jpn/scr_checkpoint, unpacking...
Num outputs,weights in Series:
  1,0,0,3:3, 0
Num outputs,weights in Series:
  C5,5:75, 0
  Ft64:64, 4864
Total weights = 4864
  [C5,5Ft64]:64, 4864
  Mp3,3:64, 0
  Lfys128:128, 98816
  Lbx256:512, 788480
  Lbx256:512, 1574912
  Fc17:17, 8721
Total weights = 2475793
Built network:[1,0,0,3[C5,5Ft64]Mp3,3Lfys128Lbx256Lbx256Fc17] from request [1,0,0,3 Ct5,5,64 Mp3,3 Lfys128 Lbx256 Lbx256 O1c17]
Training parameters:
  Debug interval = 1, weights = 0.1, learning rate = 0.001, momentum=0.5
null char=2
Loaded 3/3 lines (1-3) of document /home/ubuntu/tess/scratch/tesst/image132.lstmf
.
.
.
Loaded 2/2 lines (1-2) of document /home/ubuntu/tess/scratch/tesst/image1658.lstmf
Starting sh -c "trap 'kill %1' 0 1 2 ; java -Xms1024m -Xmx2048m -jar ./ScrollView.jar & wait"
ScrollView: Waiting for server...
sh: 1: java: not found
sh: 1: kill: No such process

ScrollView: Waiting for server...
ScrollView: Waiting for server...
ScrollView: Waiting for server...
ScrollView: Waiting for server...
ScrollView: Waiting for server...
ScrollView: Waiting for server...
.
.
.
```

I tried by removing the debug_interval command, and it resumed training. I then ran your second command (without the _ in the output traineddata), and it worked!

However, even though the model trained, when I use it with tesseract, it shows the following message.
```
tesseract -l scrjpninit img_002.jpg stdout

Failed to load any lstm-specific dictionaries for lang scrjpninit!!
```
Needless to sat it is not performing any detection. Any clues or help on this?

**Comment by Shreeshrii** [comment] 2019-12-03 09:16
Sorry, typo ..

Please try with `--debug_interval -1 `

Your output should be similar to

```
lstmtraining \
  --debug_interval -1 \
  --traineddata data/araAWN/araAWN.traineddata \
  --net_spec "[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx64 Lrx64 Lfx96 O1c0]" \
  --model_output data/araAWN/checkpoints/araAWNScratch \
  --learning_rate 20e-4 \
  --train_listfile data/araAWN/list.train \
  --eval_listfile data/araAWN/list.eval \
  --max_iterations 15000
Warning: given outputs 0 not equal to unicharset of 64.
Num outputs,weights in Series:
  1,36,0,1:1, 0
Num outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys48:48, 12480
  Lfx64:64, 28928
  Lrx64:64, 33024
  Lfx96:96, 61824
  Fc64:64, 6208
Total weights = 142624
Built network:[1,36,0,1[C3,3Ft16]Mp3,3Lfys48Lfx64Lrx64Lfx96Fc64] from request [1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx64 Lrx64 Lfx96 O1c0]
Training parameters:
  Debug interval = -1, weights = 0.1, learning rate = 0.002, momentum=0.5
null char=2
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_b_200_000784.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnFaqihHamadhani.Buldan_7_final_200_a_000324.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_a_200_000174.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_000143.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_200_000493.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_Jahiz.Hayawan_7_final_b_000618.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_Jahiz.Hayawan_7_final_a_200_000224.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_b_200_000755.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_000440.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnFaqihHamadhani.Buldan_7_final_200_a_000184.lstmf
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnAthir.Kamil_7_final_000455.lstmf
Iteration 0: GROUND  TRUTH : وه « لاقي ،ركذلاو ىثنألل نوكي عونلا اذه نم ركذلا ناكف ،)9(امهركذ ىلع
Iteration 0: BEST OCR TEXT : 727272727272727272727272727272727272727272727272727272727272727272727272727272727272727272
File /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_b_200_000784.lstmf line 0 :
Mean rms=11.959%, delta=100%, train=232.353%(100%), skip ratio=0%
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnQutayba.Adab_7_final_000431.lstmf
Iteration 1: GROUND  TRUTH : .اهعولط دنع اهل ]ب 93[ نودجسيو سمشلا نودبعي ةنيدملا كلت لهأو .ههبشي
Iteration 1: BEST OCR TEXT : ه؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛7؛
File /home/ubuntu/OCR_GS_Data/ara/AWN/book_IbnFaqihHamadhani.Buldan_7_final_200_a_000324.lstmf line 0 :
Mean rms=11.666%, delta=100%, train=267.669%(100%), skip ratio=0%
Loaded 1/1 lines (1-1) of document /home/ubuntu/OCR_GS_Data/ara/AWN/book_Jahiz.Hayawan_7_final_a_000044.lstmf
```

**Comment by cserjam** [comment] 2019-12-03 09:37
I ran the command, and it ran without problem. The ```BEST OCR TEXT``` was way off for every file though, so I dunno if it actually trained that well. Last few lines of output were as follows.
```
File /home/ubuntu/tess/scratch/tesst/image3249.lstmf line 2 :
Mean rms=9.445%, delta=7.182%, train=150.488%(99.292%), skip ratio=0.3%
At iteration 13276/51000/51181, Mean rms=9.445%, delta=7.182%, char train=150.488%, word train=99.292%, skip ratio=0.3%,  New worst char error = 150.488 wrote checkpoint.

Finished! Error rate = 0.087
```
Not sure why all the error values are so high. Is there a setting that I missed out on, or should I probably try some other network architecture?

```
tesseract -l scrjpninit img_002.jpg stdout

Failed to load any lstm-specific dictionaries for lang scrjpninit!!
```
Any  idea about this?

**Comment by Shreeshrii** [comment] 2019-12-03 09:48
>Failed to load any lstm-specific dictionaries for lang scrjpninit!!

https://github.com/tesseract-ocr/langdata_lstm/tree/master/jpn
numbers
punc
wordlist

The above three files are used to create `dawg` dictionary files. 

The msg says that there are no dawg files in your traineddata. These are `optional` in tesseract 4.0x

**Comment by Shreeshrii** [comment] 2019-12-03 09:59
Please share your input files in order to reproduce the problem.

**Comment by cserjam** [comment] 2019-12-04 05:22
> The above three files are used to create `dawg` dictionary files.

Is it possible to create those files superficially? I don't have any numbers or punctuation marks in my unicharset. Can I create wordlist in a text editor and put it somewhere for tesseract to find (or maybe compile it with the traineddata)?

**Comment by Shreeshrii** [comment] 2019-12-04 05:26
See https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#combining-the-output-files

**Comment by DalvinderKaur** [comment] 2022-12-22 10:06
> > !int_mode_:Error:Assert failed:in file /cygdrive/d/cyg_pub/devel/tesseract/tesseract-ocr-4.0.0-
> > 1.x86_64/src/tesseract-4.0.0/src/lstm/weightmatrix.cpp, line 249
> 
> Your old traineddata file needs to be from` tessdata_best` repo.
> 
> If you use the default models from tessdata_fast they will give errors, since they are integerized. So also the models from tessdata repo which have integerized versions of tessdata_best.
> 
> Once the assert is fixed, the checkpoint should be created.



> I am getting the same error. I already have traineddata from best repository. But when i am running the command:
TESSDATA_PREFIX=/home/research/tesseract-main/tessdata make training MODEL_NAME=Apex START_MODEL=eng TESSDATA=/home/research/tesseract-main/tessdata MAX_ITERATIONS=10000

Error:
Makefile:305: recipe for target 'data/Apex/checkpoints/Apex_checkpoint' failed
make: *** [data/Apex/checkpoints/Apex_checkpoint] Segmentation fault (core dumped)

**Comment by dejvizelo** [comment] 2025-03-05 19:17
For anyone still getting the `Failed to read continue from: checkpoint` error, check your `lstmtraining` version. The default package in Ubuntu comes with `lstmtraining v4.1.1`, which was causing the issue for me. I installed the PPA package from [here](https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr-daily), which comes with `lstmtraining v5.5.0`, and it solved the issue for me. You can also just compile from source.
