### ISSUE TITLE
3.05 can't be be built as Standalone Self-contained Tesseract-OCR for Mac

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#830] opened 2017-04-20 09:23 UTC
Please see the discussion at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/b2YFzN7MtJg/dq1-f8JjBgAJ

> I'm pleased to say that I managed to get a build script that works using the following versions of the libs:

>LIBJPEG_VERSION=9b
ZLIB_VERSION=1.2.11
LIBPNG_VERSION=1.6.29
LEPTONICA_VERSION=1.71
TESSERACT_VERSION=3.04.01

>I couldn't get it to work with any later versions of Leptonica (1.74.1 is the latest) or Tesseract (3.05.00 is the latest v3).

**Comment by egorpugin** [comment] 2017-04-20 12:20
We could try to build it with cppan, but I have some libtiff linking issues. One could try to build tess on mac as on windows with cppan guide and see those errors.

**Comment by stweil** [comment] 2017-04-22 18:18
See PR #835. It builds on Linux and macOS, see [Travis log](https://travis-ci.org/tesseract-ocr/tesseract/builds/224732278) for an example using `cmake`. My local test was successful with `configure` and `make`.

**Comment by Shreeshrii** [comment] 2017-04-23 03:49
@stweil Thanks, I will post in forum for the original poster to check once the PR is included.

>-- Looking for include file cairo/cairo-version.h
-- Looking for include file cairo/cairo-version.h - not found
-- Looking for include file CL/cl.h
-- Looking for include file CL/cl.h - not found
-- Looking for include file OpenCL/cl.h
-- Looking for include file OpenCL/cl.h - found
-- Looking for include file pango-1.0/pango/pango-features.h
-- Looking for include file pango-1.0/pango/pango-features.h - not found
-- Looking for include file tiffio.h
-- Looking for include file tiffio.h - found
-- Looking for include file unicode/uchar.h
-- Looking for include file unicode/uchar.h - not found

I am guessing that Travis build does not include training tools.

Do they build locally for you on Mac?

**Comment by stweil** [comment] 2017-04-23 06:23
Yes, Travis CI is currently without the training part. Of course it is possible to add `make training` if that is considered necessary. Travis also does not cover builds based on the `autotools`, as it uses `cmake`.

> My local test was successful with configure and make.

`make training` also was successful on Mac. Tesseract 3.05 uses `PKG_CHECK_MODULES` to detect `pango` and `cairo`, this should be fairly robust.

**Comment by Shreeshrii** [comment] 2017-04-30 08:40
Closing this as @stweil confirms build on mac with the PR and there is no response from original poster.

**Comment by Shreeshrii** [comment] 2017-05-01 04:15
Please see reply and script used for building at

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/b2YFzN7MtJg/HkcTYJyKCQAJ

https://mail.google.com/mail/u/0/#inbox/15b9c152e2a586c3?projector=1

**Comment by stweil** [comment] 2017-05-01 07:21
I had a look on that shell script. The published version does not work because it tries to build Tesseract without building the dependencies (libjpeg, zlib, libpng, leptonica) first. This can be easily fixed in the first lines of the script. Now it builds those dependencies. It also starts building Tesseract 3.05, but fails when linking the `tesseract` executable because of a missing symbol `_fmemopen` in liblept.

This problem is caused by an unusual build of Leptonica: instead of the normal configure / make, the script calls `./make-for-local` which uses a hand-built makefile (maybe made for Linux). I'm also surprised that TIFF support is disabled for the Leptonica build and doubt that this will work with Tesseract.

**Comment by stweil** [comment] 2017-05-01 09:00
See [here](http://digi.bib.uni-mannheim.de/tesseract/mac_standalone/) for a modified build script which produced a stand-alone `tesseract` for macOS. The build protocol shows some remaining errors, like a wrong URL for getting the language model files.

**Comment by reidit** [comment] 2017-05-01 09:09
Thanks Stefan.  Actually the shell script does build the dependencies first if you turn on the switches at the start. They are set to 0 or 1 depending on whether you're trying to rebuild/build some or all of them.  If you set them all to 1, the dependencies are built in the order libjpeg, zlib, libpng, leptonica, followed by tesseract.

I found the original script on github and modified it minimally since I didn't understand it fully. The unusual Leptonica build has come directly from that original script. I didn't understand this, so I left it as I found it!

I agree that HomeBrew/MacPorts is much easier if you are an IT person, but my users are analytical chemists or linguists, etc. who just want to run an app. The coding system I use (LiveCode) generates executables that can be run from anywhere without any installation, you just place the folder containing the app and any supporting files/folders wherever you like (e.g. the desktop for short term use).  I don't want the user to have to run an install process, either directly, or by my app doing an initial install on 1st run.

For Windows users there's a portable Tesseract readily available that works as I intended.  For Mac users, there isn't, which is why I looked for and found the shell script that seemed to offer the prospect of generating a portable Tesseract for Mac users.

You mention that it's possible to generate Tesseract using HomeBrew/MacPorts and then "some libraries can be copied & distributed".  Can you tell me exactly which libraries and where they need to be copied to.  Also, would this mean copying libraries to areas outside the user's filing system, i.e. system areas.  If so this would require admin permissions which I can't rely on being available (sometime my users have locked-down computers).  The shell script can generate a portable Tesseract that is located simply by setting 2 environment variables.  I've tested this and it works for my purposes for both JPEG and PNG graphics, which are all I need. However, I'd happily add TIFF support if I knew how to do it!

Thanks again.

Peter.

**Comment by stweil** [comment] 2017-05-01 09:37
> You mention that it's possible to generate Tesseract using HomeBrew/MacPorts and then "some libraries can be copied & distributed". Can you tell me exactly which libraries and where they need to be copied to. Also, would this mean copying libraries to areas outside the user's filing system, i.e. system areas.

You need to copy all shared libraries which are required by the `tesseract` executable. When you try to run it, macOS will tell you which shared library is missing (only first missing, so repeat until you have found all of them). With MacPorts for example, this means copying 15 files from `/opt/local/lib/*.dylib` (`liblept.5.dylib`, ...). You can choose any destination directory. By setting the environment variable DYLD_LIBRARY_PATH to that directory, Tesseract can find the shared libraries.

**Comment by reidit** [comment] 2017-05-01 11:26
Thanks Stefan, your suggestion works well.  I did the following:
1. using Terminal, install Tesseract using HomeBrew
2. copy the folder "3.05.001" from /usr/local/Cellar/tesseract into a folder on my desktop called "tessport"
3. created a test shell script "tesseract_test.sh":
    #!/bin/bash
    export TESSDATA_PREFIX=/Users/peter/Desktop/tessport/share
    export DYLD_LIBRARY_PATH=/Users/peter/Desktop/tessport/lib
    tessport/bin/tesseract -v
4. ran the test shell script "tesseract_test.sh" to confirm it works
5. uninstalled Tesseract using HomeBrew
6. re-an the test shell script "tesseract_test.sh" to confirm it still works

So I now have a recipe for generating the latest Tesseract in portable form for the Mac!

Thanks again.

Peter

**Closed** 2017-05-02 03:53 UTC
