### ISSUE TITLE
4.1.2: build fails

### ISSUE THREAD

**Issue by kloczek** [tesseract-ocr/tesseract#3642] opened 2021-11-15 02:05 UTC
Looks like paths to some headers are missing
```console
[tkloczko@ss-desktop tesseract-4.1.2]$ make
Making all in src/arch
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/arch'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/arch'
Making all in src/ccutil
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccutil'
/bin/sh ../../libtool  --tag=CXX   --mode=compile /usr/bin/g++ -DHAVE_CONFIG_H   -DTESS_EXPORTS   -I/usr/include/leptonica     -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz  -I/usr/include/cairo  -DTESSDATA_PREFIX=/usr/share -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -std=c++17 -c -o scanutils.lo scanutils.cpp
libtool: compile:  /usr/bin/g++ -DHAVE_CONFIG_H -DTESS_EXPORTS -I/usr/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/cairo -DTESSDATA_PREFIX=/usr/share -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -std=c++17 -c scanutils.cpp  -fPIC -DPIC -o .libs/scanutils.o
scanutils.cpp:16:10: fatal error: config_auto.h: No such file or directory
   16 | #include "config_auto.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:531: scanutils.lo] Error 1
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccutil'
make: *** [Makefile:508: all-recursive] Error 1
```

**Comment by stweil** [comment] 2021-11-15 07:10
Yes, that was also reported [here](https://github.com/tesseract-ocr/tesseract/commit/9dabb7ade303364a237f3d57e6f2e26b74c4b9d6#commitcomment-60258937).

**Comment by stweil** [comment] 2021-11-15 08:00
Fixed in commit 28ad3e8b990e930920d9dac3efca09223a8c3b16.

@AlexanderP, I think we need a new release 4.1.3. Or would it be better to move the 4.1.2 tag?

**Comment by kloczek** [comment] 2021-11-15 10:37
That patch works.
Thx.

However still is another issue with test suite:
```console
[tkloczko@ss-desktop tesseract-4.1.2]$ make check
Making check in src/arch
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/arch'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/arch'
Making check in src/ccutil
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccutil'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccutil'
Making check in src/viewer
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/viewer'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/viewer'
Making check in src/cutil
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/cutil'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/cutil'
Making check in src/opencl
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/opencl'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/opencl'
Making check in src/ccstruct
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccstruct'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccstruct'
Making check in src/dict
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/dict'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/dict'
Making check in src/classify
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/classify'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/classify'
Making check in src/wordrec
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/wordrec'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/wordrec'
Making check in src/textord
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/textord'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/textord'
Making check in src/lstm
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/lstm'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/lstm'
Making check in src/ccmain
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccmain'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/ccmain'
Making check in src/api
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/api'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/src/api'
Making check in .
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2'
make[1]: Nothing to be done for 'check-am'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2'
Making check in tessdata
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata'
Making check in configs
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata/configs'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata/configs'
Making check in tessconfigs
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata/tessconfigs'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata/tessconfigs'
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata'
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/tessdata'
Making check in doc
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/doc'
Making check in unittest
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/unittest'
make  apiexample_test applybox_test baseapi_test  bitvector_test cleanapi_test colpartition_test commandlineflags_test dawg_test denorm_test  fileio_test heap_test imagedata_test indexmapbidi_test intfeaturemap_test intsimdmatrix_test lang_model_test layout_test ligature_table_test linlsq_test lstm_recode_test lstm_squashed_test lstm_test lstmtrainer_test loadlang_test mastertrainer_test matrix_test  normstrngs_test nthitem_test osd_test pagesegmode_test  paragraphs_test params_model_test progress_test qrsequence_test recodebeam_test rect_test resultiterator_test scanutils_test shapetable_test stats_test  stringrenderer_test tablefind_test tablerecog_test tabvector_test  textlineprojection_test tfile_test unichar_test unicharcompress_test unicharset_test validate_grapheme_test validate_indic_test validate_khmer_test validate_myanmar_test validator_test libabseil.la
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/unittest'
make[2]: stat: /home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/test/testing/phototest.tif: Too many levels of symbolic links
mkdir -p ../test/testing
ln -s /home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/test/testing/phototest.tif ../test/testing/phototest.tif
ln: failed to create symbolic link '../test/testing/phototest.tif': File exists
make[2]: *** [Makefile:2886: /home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/test/testing/phototest.tif] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/unittest'
make[1]: *** [Makefile:2556: check-am] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/tesseract-4.1.2/unittest'
make: *** [Makefile:508: check-recursive] Error 1
```

**Comment by kloczek** [comment] 2021-11-15 10:38
After fixing that issue I think that it would be good to release 4.1.3 :)

**Comment by kloczek** [comment] 2021-11-15 10:40
I've checked list of mi patches.
I think that it woud be good to include below patch
```patch
--- a/tesseract.pc.in~  2021-03-18 22:10:10.000000000 +0000
+++ b/tesseract.pc.in   2021-03-18 22:20:15.882236752 +0000
@@ -10,5 +10,5 @@
 Description: An OCR Engine that was developed at HP Labs between 1985 and 1995... and now at Google.
 URL: https://github.com/tesseract-ocr/tesseract
 Version: @VERSION@
-Libs: -L${libdir} -ltesseract @libarchive_LIBS@ @libcurl_LIBS@ @TENSORFLOW_LIBS@
+Libs: -L${libdir} -ltesseract
 Cflags: -I${includedir}
```

**Comment by kloczek** [comment] 2021-11-15 10:42
And before above another one:
```patch
--- a/tesseract.pc.in~  2019-12-26 14:21:51.000000000 +0000
+++ b/tesseract.pc.in   2020-01-01 11:53:13.996057785 +0000
@@ -10,7 +10,5 @@
 Description: An OCR Engine that was developed at HP Labs between 1985 and 1995... and now at Google.
 URL: https://github.com/tesseract-ocr/tesseract
 Version: @VERSION@
-Requires.private: lept
 Libs: -L${libdir} -ltesseract @libarchive_LIBS@ @libcurl_LIBS@ @TENSORFLOW_LIBS@
-Libs.private: -lpthread @OPENCL_LDFLAGS@
 Cflags: -I${includedir}
```

**Comment by stweil** [comment] 2021-11-15 13:36
What is the reason for those changes? Similar code is used in the `main` branch, too.

**Comment by stweil** [comment] 2021-11-15 13:44
> However still is another issue with test suite

That looks like an issue with the build environment.

Did you try a clean build, and have you run `git submodule update --init` before running `make check`?

**Comment by stweil** [comment] 2021-11-15 14:11
`ligature_table_test` and `stringrenderer_test` also fail in release 4.1.1, so that does not look like a regression.

**Closed** 2021-11-15 20:08 UTC

**Comment by AlexanderP** [comment] 2021-11-15 20:14
@stweil thanks. Better new release.
