### ISSUE TITLE
building tesseract under cygwin: training tools don't build

### ISSUE THREAD

**Issue by domasofan** [tesseract-ocr/tesseract#61] opened 2015-07-23 21:28 UTC
Hi,

I just tried to build the training tools using cygwin.
the normal tesseract program seems to work fine.

Thanks for helping.
you are doing all a good job and the recognizationrate is also very nice now in german texts.

that's what it was showing after typing make training:

$ make training
make[1]: Entering directory '/home/Besitzer/tesseractsrc/training'
depbase=`echo boxchar.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT boxchar.lo -MD -MP -MF $depb
ase.Tpo -c -o boxchar.lo boxchar.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT boxchar.lo -MD -MP -MF .deps/boxchar.Tpo -c boxchar.cpp -o b
oxchar.o
depbase=`echo commandlineflags.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT commandlineflags.lo -MD -MP
-MF $depbase.Tpo -c -o commandlineflags.lo commandlineflags.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT commandlineflags.lo -MD -MP -MF .deps/commandlineflags.Tpo -
c commandlineflags.cpp -o commandlineflags.o
depbase=`echo commontraining.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT commontraining.lo -MD -MP -M
F $depbase.Tpo -c -o commontraining.lo commontraining.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT commontraining.lo -MD -MP -MF .deps/commontraining.Tpo -c co
mmontraining.cpp -o commontraining.o
depbase=`echo degradeimage.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT degradeimage.lo -MD -MP -MF
$depbase.Tpo -c -o degradeimage.lo degradeimage.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT degradeimage.lo -MD -MP -MF .deps/degradeimage.Tpo -c degrad
eimage.cpp -o degradeimage.o
depbase=`echo fileio.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT fileio.lo -MD -MP -MF $depba
se.Tpo -c -o fileio.lo fileio.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT fileio.lo -MD -MP -MF .deps/fileio.Tpo -c fileio.cpp -o file
io.o
depbase=`echo ligature_table.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT ligature_table.lo -MD -MP -M
F $depbase.Tpo -c -o ligature_table.lo ligature_table.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT ligature_table.lo -MD -MP -MF .deps/ligature_table.Tpo -c li
gature_table.cpp -o ligature_table.o
depbase=`echo normstrngs.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT normstrngs.lo -MD -MP -MF $d
epbase.Tpo -c -o normstrngs.lo normstrngs.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT normstrngs.lo -MD -MP -MF .deps/normstrngs.Tpo -c normstrngs
.cpp -o normstrngs.o
depbase=`echo pango_font_info.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT pango_font_info.lo -MD -MP -
MF $depbase.Tpo -c -o pango_font_info.lo pango_font_info.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT pango_font_info.lo -MD -MP -MF .deps/pango_font_info.Tpo -c
pango_font_info.cpp -o pango_font_info.o
pango_font_info.cpp: In member function 'bool tesseract::PangoFontInfo::ParseFon
tDescription(const PangoFontDescription*)':
pango_font_info.cpp:223:46: error: 'strcasestr' was not declared in this scope
   is_fraktur_ = (strcasestr(family, "Fraktur") != NULL);
                                              ^
Makefile:875: recipe for target 'pango_font_info.lo' failed
make[1]: *** [pango_font_info.lo] Error 1
make[1]: Leaving directory '/home/Besitzer/tesseractsrc/training'
Makefile:880: recipe for target 'training' failed
make: *** [training] Error 2

Besitzer@simon ~/tesseractsrc
$ make training-install
make[1]: Entering directory '/home/Besitzer/tesseractsrc/training'
depbase=`echo pango_font_info.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -O2
 -DNDEBUG -DUSE_STD_NAMESPACE -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../cc
util -I../ccstruct -I../viewer -I../textord -I../dict -I../classify -I../display
 -I../wordrec -I../cutil -I../vs2010/port -I/usr/include/leptonica -D_REENTRANT
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -I
/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/in
clude/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/f
reetype2 -I/usr/include/libpng16   -std=gnu++11 -MT pango_font_info.lo -MD -MP -
MF $depbase.Tpo -c -o pango_font_info.lo pango_font_info.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -DUSE_STD_NAMESPACE
 -DPANGO_ENABLE_ENGINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewe
r -I../textord -I../dict -I../classify -I../display -I../wordrec -I../cutil -I..
/vs2010/port -I/usr/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 -I/u
sr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/incl
ude/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/
freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng
16 -std=gnu++11 -MT pango_font_info.lo -MD -MP -MF .deps/pango_font_info.Tpo -c
pango_font_info.cpp -o pango_font_info.o
pango_font_info.cpp: In member function 'bool tesseract::PangoFontInfo::ParseFon
tDescription(const PangoFontDescription*)':
pango_font_info.cpp:223:46: error: 'strcasestr' was not declared in this scope
   is_fraktur_ = (strcasestr(family, "Fraktur") != NULL);
                                              ^
Makefile:875: recipe for target 'pango_font_info.lo' failed
make[1]: *** [pango_font_info.lo] Error 1
make[1]: Leaving directory '/home/Besitzer/tesseractsrc/training'
Makefile:882: recipe for target 'training-install' failed
make: *** [training-install] Error 2

Besitzer@simon ~/tesseractsrc
$

**Comment by jimregan** [comment] 2015-07-23 21:31
Can you try the patch in #60 to see if that fixes it?

**Comment by domasofan** [comment] 2015-07-23 22:44
Just tested it with the recent merged pull request.
this is what i get with make training:


g++ -DHAVE_CONFIG_H -I. -I..  -O2 -DNDEBUG -DUSE_STD_NAMESPACE 
-DPANGO_ENABLE_EN
GINE -I../ccmain -I../api -I../ccutil -I../ccstruct -I../viewer 
-I../textord -I.
./dict -I../classify -I../display -I../wordrec -I../cutil 
-I../vs2010/port -I/us
r/include/leptonica -D_REENTRANT -I/usr/include/pango-1.0 
-I/usr/include/glib-2.
0 -I/usr/lib/glib-2.0/include  -I/usr/include/cairo 
-I/usr/include/glib-2.0 -I/u
sr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 
-I/usr/
include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 
-std=gnu++11
  -MT set_unicharset_properties.o -MD -MP -MF $depbase.Tpo -c -o 
set_unicharset_p
roperties.o set_unicharset_properties.cpp &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -std=gnu++11 
-Wl,-no-undefined
-Wl,--as-needed   -o set_unicharset_properties.exe 
set_unicharset_properties.o l
ibtesseract_training.la libtesseract_tessopt.la -licuin -licuuc 
../api/libtesse
ract.la -lws2_32  -llept
libtool: link: g++ -std=gnu++11 -Wl,-no-undefined -Wl,--as-needed -o 
set_unichar
set_properties.exe set_unicharset_properties.o 
./.libs/libtesseract_training.a
./.libs/libtesseract_tessopt.a -licuin -licuuc 
../api/.libs/libtesseract.a -lws2
_32 -llept
/usr/lib/gcc/i686-pc-cygwin/4.9.3/../../../../i686-pc-cygwin/bin/ld: 
cannot find
  -licuin
collect2: error: ld returned 1 exit status
Makefile:805: recipe for target 'set_unicharset_properties.exe' failed
make[1]: *** [set_unicharset_properties.exe] Error 1
make[1]: Leaving directory '/home/Besitzer/tesseractsrc/training'
Makefile:880: recipe for target 'training' failed
make: *** [training] Error 2


Am 23.07.2015 um 23:31 schrieb Jim Regan:
> Can you try the patch in #60 to see if that fixes it?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tesseract-ocr/tesseract/issues/61#issuecomment-124245368
>

-- 
Simon Eigeldinger
Follow me on Twitter: http://www.twitter.com/domasofan/
E-Mail: simon.eigeldinger@vol.at
MSN: simon_eigeldinger@hotmail.com
ICQ: 121823966
Jabber: domasofan@andrelouis.com

**Comment by jimregan** [comment] 2015-07-23 22:58
Ok, that's a different error. Do you have ICU4C installed?

**Comment by jimregan** [comment] 2015-07-23 23:07
Sorry, it only complained about one of the ICU libraries. 

I think that the problem is that the library is named 'libicui18n' under Cygwin, as it is on Linux etc.

**Comment by jimregan** [comment] 2015-07-23 23:18
Can you try with the patch from #62 ?

**Comment by domasofan** [comment] 2015-07-24 06:06
Hi,

yeah its icui18n.
there seem to be 2 versions.
5.4 and 5.5.

greetings,
simon


Am 24.07.2015 um 01:07 schrieb Jim Regan:
> Sorry, it only complained about one of the ICU libraries.
>
> I think that the problem is that the library is named 'libicui18n' under Cygwin, as it is on Linux etc.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tesseract-ocr/tesseract/issues/61#issuecomment-124262453
>

-- 
Simon Eigeldinger
Follow me on Twitter: http://www.twitter.com/domasofan/
E-Mail: simon.eigeldinger@vol.at
MSN: simon_eigeldinger@hotmail.com
ICQ: 121823966
Jabber: domasofan@andrelouis.com

**Comment by jimregan** [comment] 2015-07-24 06:10
Do the training tools build now? (Zdenko merged the pull request, so there's no need to mess around with branches)

**Comment by domasofan** [comment] 2015-07-24 06:36
Hi,

i guess that looks good now.

we have:
ambiguous_words.exe
classifier_tester.exe
cntraining.exe
combine_tessdata.exe
dawg2wordlist.exe
mftraining.exe
set_unicharset_properties.exe
shapeclustering.exe
tesseract.exe
text2image.exe
unicharset_extractor.exe
wordlist2dawg.exe


thanks.
greetings,
simon

Am 24.07.2015 um 01:18 schrieb Jim Regan:
> Can you try with the patch from #62 ?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tesseract-ocr/tesseract/issues/61#issuecomment-124264086
>

-- 
Simon Eigeldinger
Follow me on Twitter: http://www.twitter.com/domasofan/
E-Mail: simon.eigeldinger@vol.at
MSN: simon_eigeldinger@hotmail.com
ICQ: 121823966
Jabber: domasofan@andrelouis.com

**Comment by jimregan** [comment] 2015-07-24 06:45
Ok, I'll close this. Thanks for testing!

**Comment by domasofan** [comment] 2015-07-24 06:46
thanks.
thanks for fixing. :-)


Am 24.07.2015 um 08:45 schrieb Jim Regan:
> Ok, I'll close this. Thanks for testing!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/tesseract-ocr/tesseract/issues/61#issuecomment-124357848
>

-- 
Simon Eigeldinger
Follow me on Twitter: http://www.twitter.com/domasofan/
E-Mail: simon.eigeldinger@vol.at
MSN: simon_eigeldinger@hotmail.com
ICQ: 121823966
Jabber: domasofan@andrelouis.com

**Closed** 2015-07-24 08:19 UTC
