### ISSUE TITLE
"Error in selectDefaultPdfEncoding: type selection failure" when OCR'ing TIFFs to PDF

### ISSUE THREAD

**Issue by 36PopTarts** [tesseract-ocr/tesseract#3838] opened 2022-06-07 14:26 UTC
### Environment

* **Tesseract Version**: 5.1.0, built from source locally and possibly 4.1.1, also built from source
* **Commit Number**: c2a3efe (5.1.0 Release version) and 7510304 (4.1.1 Release version)
* **Platform**: `Linux hostname 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Current Behavior:

Command line used:
`TESSDATA_PREFIX=/opt/.../pdfprocessor/tessdata tesseract -l eng ocrIn_4.tif test pdf`
Some TIFF images when used as input, and converting to an OCR'd PDF, fail with the error message:
```
Error in selectDefaultPdfEncoding: type selection failure
Error during processing.
```
It seems to correlate highly with TIFFs generated by our application pipeline, specifically, since I have tried with TIFFs generated by other applications (i.e. Foxit) and they did not fail, even when generated from the same original document file. This only started happening after I updated the VM hosting Tesseract from Ubuntu 18.04 to 20.04. I can't figure out what the cause is of this. The same document would not throw errors before the update. I have attached a page from a failing document (only a single page, as much of it contains identifying information). If a specific cause can be found, I can change the application which generates the TIFFs to work around this. I received a similar error when passing the document through to our VMs after they were updated to Ubuntu 20.04, but still running Tesseract 4.1.1. It had a bunch of other errors listed (presumably which cascaded from this one) but it still ended with the above error. This leads me to believe the cause is an updated dependency or environmental change. The method name listed (selectDefaultPdfEncoding) is from Leptonica, but that's all I could find searching online. No one else seems to have reported this issue.

### Expected Behavior:

Tesseract should be able to consistently produce an OCR'd PDF from the TIFF image input file.

### Suggested Fix:

Not really applicable as I can't find the underlying cause. Perhaps building with an older version of Leptonica could be a workaround? Or generating the TIFF differently if need be.

### Attached sample data:
[ocrIn_4.zip](https://github.com/tesseract-ocr/tesseract/files/8854043/ocrIn_4.zip)

**Comment by amitdo** [comment] 2022-06-07 14:59
`Error in selectDefaultPdfEncoding: type selection failure`

This error comes from Leptonica.

https://github.com/DanBloomberg/leptonica/search?q=selectDefaultPdfEncoding

**Comment by amitdo** [comment] 2022-06-07 15:13
Pinging @Danbloomberg ...

**Comment by DanBloomberg** [comment] 2022-06-07 16:53
The problem is that the selectDefaultPdfEncoding() neglected to consider the case where the input image is 16 bpp.

This is now fixed with leptonica commit c59d31a

**Comment by 36PopTarts** [comment] 2022-06-07 18:34
Thanks so much for addressing this! But I seem to be running into a new error while building Tesseract. I was able to build Leptonica from source, but when I build Tesseract again, it throws this error on `make`:
```
CXX      src/textord/libtesseract_la-devanagari_processing.lo
src/textord/devanagari_processing.cpp: In member function ‘bool tesseract::ShiroRekhaSplitter::Split(bool, tesseract::DebugPixa*)’:
src/textord/devanagari_processing.cpp:129:19: error: invalid use of incomplete type ‘struct Pixa’
  129 |     Box *box = ccs->boxa->box[i];
      |                   ^~
In file included from /usr/local/include/leptonica/alltypes.h:52,
                 from /usr/local/include/leptonica/allheaders.h:35,
                 from src/textord/devanagari_processing.h:16,
                 from src/textord/devanagari_processing.cpp:24:
```
[make.log](https://github.com/tesseract-ocr/tesseract/files/8855674/make.log)

I have attached a file with a more complete output log. I did check to ensure that `/usr/local/lib` is included in the library path, and Leptonica built successfully anyway so I think that isn't the problem. Running `make check` on Leptonica shows all tests either passed or skipped. Leptonica was installed in the default directory and I didn't run Tesseract's `configure` with any differing paths because everything seemed to be in the place that the build script was looking for it. Am I making a boneheaded mistake here or should I open a new issue for this?

**Comment by zdenop** [comment] 2022-06-07 19:29
You need to use the latest tesseract and the latest leptonica together.

**Comment by DanBloomberg** [comment] 2022-06-07 19:44
We recently made the internal details of the structs that were in pix.h to be non-public.  They are in pix_internal.h.  pix.h now has only typedefs for these structs.

So applications must use the accessors -- they can no longer access the fields directly.

**Closed** 2022-06-07 21:11 UTC
Labels: leptonica
