### ISSUE TITLE
OSD mode (--psm 0) always returns dummy results when language (-l eng, -l pol, etc.) is specified

### ISSUE THREAD

**Issue by Twixes** [tesseract-ocr/tesseract#2931] opened 2020-03-24 01:13 UTC
### Environment

* **Tesseract Version**: 4.1.1 and 5.0.0-alpha-635-g90405
* **Platform**: macOS 10.15.3 (tested with v4) and Ubuntu 18.04 (tested with v4 and v5)

### Current Behavior:
Invocations with options `--psm 0 -l eng` always return the same dummy results for all valid images:
```Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 0.00
Script: Latin
Script confidence: 2.00
```

### Expected Behavior:
Results should contain actual `Orientation degrees`, `Rotate` and `Orientation confidence` values.

**Comment by zdenop** [comment] 2020-03-24 10:51
Solution: do not use language specification when you for osd.

**Comment by Twixes** [comment] 2020-03-24 12:02
I thought it should work with language specification? https://github.com/tesseract-ocr/tesseract/issues/1926#issuecomment-423932013

**Comment by amitdo** [comment] 2020-05-09 16:18
It looks like a duplicate of #2062.

**Closed by amitdo** 2020-05-09 16:18 UTC

**Comment by amitdo** [comment] 2020-05-14 01:27
https://github.com/tesseract-ocr/tesseract/issues/2062#issuecomment-490974756

You need to:
1) Download eng.traineddata from the tessdata repo,
2) Create new `tessdata` directory somewhere.
3) Add `--tessdata-dir /path/to/your/tessdata` to the the tesseract command.
