### ISSUE TITLE
Extra spaces between characters with Japanese and PDF output

### ISSUE THREAD

**Issue by kuro68k** [tesseract-ocr/tesseract#3645] opened 2021-11-16 14:31 UTC
### Environment

* **Tesseract Version**: v5.0.0-alpha.20210811

```
tesseract v5.0.0-alpha.20210811
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0
```

* **Platform**: Windows 8.1 x64

### Current Behavior:

When converting an image to a PDF file, extra spaces are inserted between characters.

Using `-c preserve_interword_spaces=1` does not prevent this. However, if the output format is changed to text this option is effective.

`tesseract scan0005.jpg test -l jpn -c preserve_interword_spaces=1`

PDF file copied text: `日 本 に お け る ウ ォ ーSLG の 代 名 詞`
Text file output: `日本におけるウォーSLGの代名詞`

### Expected Behavior:

Embedded text in PDF should be the same as the text file output, without spaces.

### Suggested Fix:

Make this setting affect PDF output too.

**Comment by amitdo** [comment] 2021-11-16 15:05
Duplicate of #2702.

**Closed by amitdo** 2021-11-16 15:05 UTC
