### ISSUE TITLE
LSTM Training: Can't encode transcription ERROR (for Korean)

### ISSUE THREAD

**Issue by godofcheerup** [tesseract-ocr/tesseract#1384] opened 2018-03-13 17:05 UTC
![cantencode](https://user-images.githubusercontent.com/25732817/37357598-33104c06-272c-11e8-8db4-adb67995ce6d.png)

------------------------

### Environment

* **Tesseract Version**:  tesseract 4.00 alpha
* **Commit Number**:  
* **Platform**:  ubuntu 16.04.03 LTS

**Comment by Shreeshrii** [comment] 2018-03-14 04:05
Duplicate of https://github.com/tesseract-ocr/tesseract/issues/1012

@zdenop Please close.

@godofcheerup  Please try with latest version of tesseract from github master (beta.1) and post feedback under earlier issue 1012.

**Comment by godofcheerup** [comment] 2018-03-14 04:49
Thank U Shreeshrii

**Closed** 2018-03-14 04:49 UTC
