### ISSUE TITLE
PDF problems on raspi

### ISSUE THREAD

**Issue by mblascht** [tesseract-ocr/tesseract#181] opened 2015-12-27 01:31 UTC
I would like to get running tesseract on raspi (rasbian wheezy) for creating searchable pdf's from scanned tiffs. 

For me pdf output contains no text just "empty" boxes:
`pi@raspberrypi ~/tesseract/testing $ tesseract eurotext.tif eurotext -l eng+deu pdf`
`Tesseract Open Source OCR Engine v3.05.00dev with Leptonica`
`Page 1`
`Warning in pixReadMemTiff: tiff page 1 not found`
results ins [eurotext.pdf](https://github.com/tesseract-ocr/tesseract/files/72560/eurotext.pdf) with no searchable or copy/pasteble text.

Ocr itself is working fine, even hocr result seems to be correct:
`pi@raspberrypi ~/tesseract/testing $ tesseract eurotext.tif eurotext -l eng+deu hocr'
results in [eurotext.txt](https://github.com/tesseract-ocr/tesseract/files/72565/eurotext.txt) (.hocr renamed to .txt for uploading)

What did I missed up?

I builded tesseract from scratch with latest sources and latest leptonica:
`pi@raspberrypi ~/tesseract/testing $ tesseract -v`
`tesseract 3.05.00dev`
` leptonica-1.72`
`  libjpeg 8d : libpng 1.2.49 : libtiff 3.9.6 : zlib 1.2.7`
Then I copied the files `eng.traindata, deu.traindata, osd.traindata`in to directory `/usr/local/share/tessdata/'

**Comment by stweil** [comment] 2015-12-27 08:34
Your PDF looks good here, and I can extract this text:

    The (quick) [brown] {fox} jumps!
    Over the $43,456.78 <lazy> #90 dog
    & duck/goose, as 12.5% of E-mail
    from aspammer@website.com is spam.
    Der „schnelle” braune Fuchs springt
    über den faulen Hund. Le renard brun
    «rapide» saute par-dessus le chien
    paresseux. La volpe marrone rapida
    salta sopra il cane pigro. El zorro
    marrön räpido salta sobre el perro
    perezoso. A raposa marrom räpida
    salta sobre o cäo preguieoso.

**Comment by mblascht** [comment] 2015-12-27 13:59
Yes, you're right. Just tested this generated pdf in windows: selection/copy/paste is working.
But on OS X or iOS the selection and search is not working. Maybe a codepage issue on my raspi?

I have an early 2015 installation of tesseract (before it moved to github) on a different small raspi sd card:
`pi@raspberrypi ~ $ tesseract -v`
`tesseract 3.04.00`
` leptonica-1.71`
`  libjpeg 8d : libpng 1.2.49 : libtiff 3.9.6 : zlib 1.2.7`
and here pdf creation
`pi@raspberrypi /nas $ tesseract eurotext.tif eurotext_old -l deu pdf`
`Tesseract Open Source OCR Engine v3.04.00 with Leptonica`
`Page 1`
`Warning in pixReadMemTiff: tiff page 1 not found`
works fine for me, pdf is searchable on OS X and iOS:
[eurotext_old.pdf](https://github.com/tesseract-ocr/tesseract/files/72688/eurotext_old.pdf)
I already moved the my old working tesseract binaries to the new raspi installation, but the issue is still the same, no searchable pdf on OS X.
Any ideas where I can look at?

**Comment by jbreiden** [comment] 2016-01-05 04:06
issue 181 and 182 are duplicates. Your evidence suggests a compatibility regression when we changed the invisible font for http://bugs.ghostscript.com/show_bug.cgi?id=695869

**Comment by SimonAdameit** [comment] 2016-01-18 09:24
I'm experiencing the same issue on OSX 10.11.2, using tesseract version
```
tesseract 3.04.00
 leptonica-1.72
  libjpeg 8d : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.5
```

It works fine in Chrome, but in Preview, the selected Text is empty and Search also doesn't work. I'd really like to help solve this issue. So if there is anything I can do that doesn't involve intimate knowledge of the inner workings of tesseract, like testing etc., please feel free to contact me.

**Comment by jbreiden** [comment] 2016-01-18 18:58
See issue #182.

**Comment by jbreiden** [comment] 2016-02-13 01:40
Duplicate of #182 so closing.

**Closed** 2016-02-13 01:40 UTC
