### ISSUE TITLE
Chinese recognition was incorrectly segmented by spaces

### ISSUE THREAD

**Issue by sxgkwei** [tesseract-ocr/tesseract#2814] opened 2019-12-11 09:01 UTC
### Environment

* **Tesseract Version**: 4.1.1-rc2 , language data: chi_sim.traineddata 
* **Commit Number**: 
* **Platform**: Windows 7 64-bit

### Current Behavior:
Chinese recognition results were intentionally added with spaces between scattered words
### Expected Behavior:
Recognized text can be normal and continuous without gaps
### Suggested Fix:
Chinese and English are different languages, and Chinese should not be understood at intervals of English words.
In Apache Lucene, the phrase search based on the Chinese word breaker (usually, a two-word phrase in Chinese, meaning a word meaning), because each word is separated by a space, completely invalid.

**Comment by bertsky** [comment] 2019-12-12 17:44
Sure, there is not a clear cut definition of a _word_ in Chinese. (You could find diverging criteria on the morphological, the syntactic and the semantic level, not even mentioning the various statistical/engineering approximations that exist.) But for a practical system, you have to use _some_ notion of a word, or you won't be able to incorporate statistics on that level – like a dictionary.

So the bug here is not that Tesseract manages a word level internally, but that it outputs Chinese in space-delimited fashion without being asked for.

IIRC this is merely a matter of the configuration of `chi_sim.traineddata`. @Shreeshrii can you confirm this?

Probably related to https://github.com/tesseract-ocr/tesseract/issues/2760#issuecomment-560372382.

**Comment by amitdo** [comment] 2020-04-23 22:08
Which output option did you use?
Which traineddata, best or fast?

According to other reports the issue should not occur with txt output, but it still occurs with other outputs like hocr.

See #991 and 2702.

**Comment by Lin-Buo-Ren** [comment] 2020-05-02 14:03
@amitdo As I can reproduce this issue, here's the info for my case:

> Which output option did you use?

* txt (not reproduced)
* pdf (reproduced)

> Which traineddata, best or fast?

* Both tessdata_best and tessdata_fast can reproduce this issue for the LSTM recognizer
* Can't reproduce the issue with the legacy models and the legacy recognizer(`--oem 0`)

**Comment by amitdo** [comment] 2020-05-02 14:20
@Lin-Buo-Ren,

Thanks for your report.

I'm closing this issue since it's the same as #2702.

**Closed by amitdo** 2020-05-02 14:20 UTC
