### ISSUE TITLE
LSTM: traineddata seem to be missing the lstm version of unicharset

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#527] opened 2016-12-03 17:21 UTC
Using dawg2wordlist on lstm-word-dawg with the unicharset in the traineddata files creates a wordlist with 'junk' words (similar to what one gets when cube-word-dawg is processed with unicharset instead of cube-unicharset).

So either the lstm-unicharset has not been included in the traineddata or the lstm version of unicharset has not been included in the traineddata.

e.g. for English, see the commands and a sample of resulting wordlist ..

dawg2wordlist eng.unicharset eng.word-dawg eng.word.txt

e
en
entrepreneur
entrepreneurs
entrepreneurship
entrepreneurial
entrepreneur's
entrenched

dawg2wordlist eng.cube-unicharset eng.cube-word-dawg eng.cube.cube-word.txt

t
tATu
tBlog
tCK
tHE
tHe
tHeM
tMP
tO
tPA
tRNA
ta
tab
tabbed

However, using the following gives incorrect wordlists ..

dawg2wordlist eng.unicharset eng.lstm-word-dawg eng.lstm-word.txt

5
5h
5hr
5hrh
5hrh0
5hrh0%
5hrh0%bTIr
5hrh0%bTIr1
5hrh0%bTIrM
5hrh0%bTIrO
5hrh0%bTIr%v

Similar to the erroneous wordlist, if the cube dawg is processed with the regular unicharset

dawg2wordlist eng.unicharset eng.cube-word-dawg eng.cube-word.txt

Joined
Joined|Ph
JoinedBAe1
Joined-6
Joined°R
Joined°v
Joined°vg
Joinedg%
JoinedX
Joined%|
Joined]a|

**Comment by Shreeshrii** [comment] 2016-12-03 17:55
However, removal of all dawg files from the traineddata does not seem to degrade the accuracy - tested with the phototest.tif and eurotext.tif test files.

https://github.com/Shreeshrii/tessdata4alpha/blob/master/en4.traineddata has this smaller minimal LSTM traineddata for English, used for the test.

**Comment by theraysmith** [comment] 2016-12-14 16:41
So here's how it works:
The LSTM unicharset is embedded inside the .lstm component itself. That enables it to be different from the unicharset for base tesseract, without a proliferation of new traineddata components.
It was convenient at the time for the trainer to be able to save and load checkpoints in a single file.
The dawgs offer only a slight improvement over the LSTM model itself, as that is very good on its own, and will easily nail phototest.tif without the language models. (Even the vie lstm model will nail phototest.tif.)

Closing as working as intended. Reopen if you really need to get at the unicharset for some reason.

**Closed by theraysmith** 2016-12-14 16:41 UTC

**Comment by Shreeshrii** [comment] 2016-12-16 17:24
Unicharset was used for converting by dawg2wordlist. Will there be a new version of the program using LSTM instead of unicharset for viewing the wordlist, numbers and punctuation lists?
