### ISSUE TITLE
Tesseract contains_unichar_id error

### ISSUE THREAD

**Issue by psinger** [tesseract-ocr/tesseract#1237] opened 2017-12-19 10:31 UTC
Hi,

I have image files that fail with the following error:

> contains_unichar_id(unichar_id):Error:Assert failed:in file ../ccutil/unicharset.h, line 513                                                                                                      Segmentation fault (core dumped)    

I am running it with

> -l deu -c preserve_interword_spaces=1 -psm 3

I know that similar questions have been asked, but I have not seen an applicable solution yet.

I tried different languages, which did not help.

------------------------

### Environment

* **Tesseract Version**: v4.00.00alpha
* **Platform**: Ubuntu 64bit

**Comment by amitdo** [comment] 2017-12-19 14:04
https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+%22contains_unichar_id%28unichar_id%22+is%3Aopen

**Comment by Shreeshrii** [comment] 2018-03-30 09:25
@zdenop  Please close this issue.

**Closed** 2018-03-30 09:31 UTC

**Comment by stweil** [comment] 2018-10-01 15:13
This is a duplicate of issue #1205.
