### ISSUE TITLE
Cannot reproduce inline spacing in pytesseract

### ISSUE THREAD

**Issue by kylefoley76** [tesseract-ocr/tesseract#3193] opened 2020-12-25 12:03 UTC
------------------------

### Environment

Pytesseract 0.3.7
Pillow 6.2.1
tesseract 4.1.1.
Python 3.8
Mac Os 10.14.4

### Current Behavior:

When I scan the attached image I get the output:

OBSCURE DISTANCES
Whenever my hands gather her things
and bend like wheat stalks,
like a horizon unharvested,
a light passes through me silken-stepped,
its path studded with thorns,
and silence begins to call out my name.
My house and I in midmorning light,
a flower grown old
and a dead swallow’s beak.

### Expected Behavior:

I should be getting:

[there are spaces in the text below but github is not able to preserve them.  You would think github would be able to master such a small bug.  But you can see the space in the image attached anyway.]

OBSCURE DISTANCES
Whenever my hands gather her things
           and bend like wheat stalks,
           like a horizon unharvested,
a light passes through me silken-stepped,
          its path studded with thorns,
and silence begins to call out my name.
My house and I in midmorning light,
          a flower grown old
          and a dead swallow’s beak.

### Suggested Fix:

I have already read this thread here:
https://github.com/tesseract-ocr/tesseract/issues/781

I was also told here
https://github.com/tesseract-ocr/tesseract/issues/3185#issuecomment-748669202
that the issue was solved in the current version, so I'm not sure what I'm doing wrong. If someone could scan the attached image and tell me if they get the expected the output then I would greatly appreciate it. 

Here is the code I'm using:

```
    p = print
    img1 = 'adonis.jpg'
    c1 = '--psm 4'
    c4 = r'-c preserve_interword_spaces=1 --psm 4'
    c5 = r'-c preserve_interword_spaces=1 --psm 6'
    c6 = r'-c preserve_interword_spaces=1 --psm 11'

    img1 = Image.open(img1)
    for c in [c1, c4, c5, c6]:
        str4 = pytesseract.image_to_string(img1, config=c)
        str4 = str4.replace('\n\n', '\n')
        lst = str4.split('\n')
        for x in lst:
            p (x)
```

Image attached here:

![adonis](https://user-images.githubusercontent.com/16620676/103134453-249fe800-4666-11eb-9fce-dfd41179dc8d.jpg)

**Comment by Shreeshrii** [comment] 2020-12-25 12:30
I think there are problems related to recognizing spaces at beginning of lines, like the indentation here, which have been documented in other issues.

**Comment by kylefoley76** [comment] 2020-12-25 14:05
Ok I tried the following config: 'r'--oem 1 --psm 6 -l eng -c preserve_interword_spaces=1' - That didn't work for me.

**Comment by kylefoley76** [comment] 2020-12-25 14:06
Do I have to apply some special patch with this?
https://github.com/tesseract-ocr/tesseract/commit/e62e8f5f802c0d8f3dd67da993327cdafaee9763

I rarely do that sort of thing.

**Comment by Shreeshrii** [comment] 2020-12-25 14:55
Current code will still not recognise the space at beginning of line. That patch has already been applied.

**Comment by kylefoley76** [comment] 2020-12-25 15:38
So your saying that the problem has never been fixed?

**Comment by amitdo** [comment] 2020-12-25 16:49
Interword means 'between words' (in the same line).

You didn't told me in your previous question that you're asking about preserving indentation (a whitespace at beginning of a line).

interword spaces and indentation are two different things.

Tesseract does not insert spaces to represent indention. 

Indention is considered a layout information. If you need layout information, you should ask Tesseract to output a hocr file. This output will give you block and line coordination as boundind boxes.

**Comment by kylefoley76** [comment] 2020-12-25 17:10
Can pytesseract communicate that info the tesseract?

**Comment by amitdo** [comment] 2020-12-25 17:20
>Can pytesseract communicate to tesseract that it wants to ouput an hocr file?

I don't know.

**Comment by amitdo** [comment] 2020-12-25 17:21
Duplicate of #2071.

**Closed by amitdo** 2020-12-25 17:21 UTC

**Comment by kylefoley76** [comment] 2020-12-26 02:43
Well, actually regarding the comment on 
https://github.com/tesseract-ocr/tesseract/issues/2071#issuecomment-441349690
where the poster comments that he knows of no OCR software that preserves leading white space or tab identation.  ABBYY Fine Reader Express does.  However, I would prefer to do everything with Python.  I would probably have to do about a 5 hour research project to figure out how to translate a .rtf file with indentation preserved into a .txt document with indentation preserved.  i prefer to use .txt files, they're just easier.

**Comment by Shreeshrii** [comment] 2020-12-26 04:23
See https://medium.com/@neemagaurav1996/ocring-identifying-page-structure-tesseract-hocr-760f3031f3ac

**Comment by amitdo** [comment] 2020-12-26 19:32
hocr is based on html, not rtf. There is also a xml file output.
