### ISSUE TITLE
Using a list of image files which doesn't end with a newline fails

### ISSUE THREAD

**Issue by so-o** [tesseract-ocr/tesseract#3298] opened 2021-02-12 17:34 UTC
$ tesseract -v -c page_separator="" -l eng --psm 4 img.list -
tesseract 5.0.0-alpha-20201231-204-g01550
 leptonica-1.81.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1
 Found AVX2
 Found AVX
 Found SSE
 Found OpenMP 201511
Error during processing.

The input file with the list of image files, in this case just one file, is generated in PHP with `file_put_contents`. Adding a `PHP_EOL` - a newline - at the end the file solves the problem.

Put a _file.jpg_ in a directory. Create _img.list_ with `echo -n file.jpg > img.list`.

**Comment by zdenop** [comment] 2021-02-13 10:13
Can you please elaborate why you create issue here?
1. We do not support 3rd party project. 
2. What you wrote: I created wrong input file. When I corrected it - it worked => that is not tesseract issue.

**Comment by stweil** [comment] 2021-02-13 10:30
Tesseract can run OCR on a list of files. This test case fails because the line with the filename is not terminated by LF:

    $ echo -n test/testing/eurotext.tif  >/tmp/list
    $ tesseract /tmp/list -
    Error during processing.

This is unexpected behaviour and should be fixed in the code.

**Comment by stweil** [comment] 2021-02-13 10:46
Commit 65053890d77cbadd369348173f798154bcb472bc implements support for a last line without terminating linefeed and fixes this issue.

**Comment by stweil** [comment] 2021-02-13 10:47
@so-o, please test again with the latest code.

**Comment by zdenop** [comment] 2021-02-13 10:55
@stweil:  Problem is not in tesseract, but in how filelist is created. Try:
```
echo -n test/testing/eurotext.tif  >/tmp/list
echo -n test/testing/eurotext.tif  >>/tmp/list
echo -n test/testing/eurotext.tif  >>/tmp/list
```
Will `tesseract /tmp/list -`  work with your modification?

**Comment by stweil** [comment] 2021-02-13 11:16
@zdenop, that would create a single line.

Not all text editors add a terminating line feed for the last line automatically when users enter a list of lines.
We could consider that as a bug of the text editor, but it's more user friendly to just accept that the last line might miss the LF.

**Comment by so-o** [comment] 2021-02-13 15:08
Thanks stweil for your openness. Note that if the file with the missing EOL at the end of the file contains only 1 line, an error is reported, but if the file contains more than one line, the last one is just skipped silently. By the way, do you deal with the different combinations of characters for an EOL found on Linux, Windows and Max systems?

**Comment by stweil** [comment] 2021-02-13 16:53
Mac used CR. That's not supported.

Nowadays Mac uses LF like Linux and similar operating systems, so that works.

Windows also can work with LF, but CR-LF is more common. That works, too.

**Comment by zdenop** [comment] 2021-02-13 16:53
@stweil : he is not using editor  - he is generating with php. So it is the same as somebody generate wrong png, tiff or other input format.

@so-o : tesseract accepts only '\n' (unix) as EOL - on input and output.

**Comment by stweil** [comment] 2021-02-13 16:54
> if the file contains more than one line, the last one is just skipped silently

That's fixed in the latest code, too.

**Comment by stweil** [comment] 2021-02-13 17:01
@zdenop, I know. I also think that ideally the list of files should terminate with a LF, but it's a very common problem that it is missing, even in Tesseract code as you can see for example in commit dabf3c299f24595436e5915e034d9d6f0755185f.

Silently ignoring the last line just because of a missing LF was bad, and fixing the problem was easy. So hopefully we have now a better "user experience" here.

**Closed** 2021-02-23 13:56 UTC
Labels: feature request
