### ISSUE TITLE
rupee training 

### ISSUE THREAD

**Issue by madhuri140** [tesseract-ocr/tesseract#2198] opened 2019-01-25 10:11 UTC
I'm training for rupee symbol 
While executing ,
 sudo lstmtraining --model_output /home/linux/Tesseract_folders/trainRupee   --continue_from /home/linux/Tesseract_folders/trainRupee/eng.lstm   --traineddata /home/linux/Tesseract_folders/trainRupee/eng/eng.traineddata   --old_traineddata /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata   --train_listfile /home/linux/Tesseract_folders/trainRupee/eng.training_files.txt   --max_iterations 3600

Error:
-ocr/4.00/tessdata/eng.traineddata   --train_listfile /home/linux/Tesseract_folders/trainRupee/eng.training_files.txt   --max_iterations 3600
Loaded file /home/linux/Tesseract_folders/trainRupee/eng.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 111 to 110!
Num (Extended) outputs,weights in Series:
  1,36,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys48:48, 12480
  Lfx96:96, 55680
  Lrx96:96, 74112
  Lfx192:192, 221952
  Fc110:110, 0
Total weights = 364384
Previous null char=110 mapped to 109
Continuing from /home/linux/Tesseract_folders/trainRupee/eng.lstm
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Arial_Bold.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Arial.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Century_Schoolbook_L_Bold_Italic.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Century_Schoolbook_L_Bold.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Century_Schoolbook_L_Medium.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Arial_Bold_Italic.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Arial_Italic.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.DejaVu_Sans_Ultra-Light.exp0.lstmf
Loaded 72/72 pages (1-72) of document /home/linux/Tesseract_folders/trainRupee/eng.Century_Schoolbook_L_Italic.exp0.lstmf
!int_mode_:Error:Assert failed:in file weightmatrix.cpp, line 268
!int_mode_:Error:Assert failed:in file weightmatrix.cpp, line 268

**Comment by Shreeshrii** [comment] 2019-01-25 14:03
>!int_mode_:Error:Assert failed:in file weightmatrix.cpp, line 268

You need to extract eng.lstm from tessdata_best. The models in tessdata_fast are integer models and can't be used for training.

**Comment by madhuri140** [comment] 2019-01-28 07:19
Thankyou. now there is an error which comes up wherever rupee symbol occurs.


Encoding of string failed! Failure bytes: ffffffe2 ffffff82 ffffffb9 33 2c 30 30 30 2e 38 30 20 55 6e 69 74 65 64 20 69 6e 20 70 6f 73 74 20 50 6f 70 75 6c 61 72 20 68 65 72 65 20 76 42 75 6c 6c 65 74 69 6e ffffffc2 ffffffae 20 52 65 76 69 65 77 73 20 6d 61 6e 79 20 ffffffc2 ffffffa9 20 4f 66 66 69 63 65 20 56 69 65 77 20 62 65 63 61 75 73 65 20 73 75 63 68 20 53 45 41 52 43 48
Can't encode transcription: 'Books ₹3,000.80 United in post Popular here vBulletin® Reviews many © Ofﬁce View because such SEARCH' in language ''
2 Percent improvement time=38, best error was 100 @ 0
At iteration 38/500/506, Mean rms=0.204%, delta=0.062%, char train=0.194%, word train=0.58%, skip ratio=1.2%,  New best char error = 0.194 wrote best model:/home/linux/Tesseract_folders/trainRupee0.194_38.checkpoint wrote checkpoint.

This error repeats for each line whereever ₹ this symbol occured in the eng.training_text

**Comment by Shreeshrii** [comment] 2019-01-28 11:23
@madhuri140  Please make sure that the fonts that you are using for trainiing have the rupee symbol in it, otherwise those words will get dropped as unrenderable.

You can use the following command to get a list of fonts - modify it to match your paths and training text.

```
text2image --find_fonts \
--fonts_dir /usr/share/fonts \
--text ../langdata/eng/eng.rupeenew.training_text  \
--min_coverage 1  \
--outputbase ../langdata/eng/eng \
|& grep raw \
 | sed -e 's/ :.*/@ \\/g' \
 | sed -e "s/^/  '/" \
 | sed -e "s/@/'/g" >../langdata/eng/rupeenewfontslist.txt
```

**Comment by madhuri140** [comment] 2019-01-28 13:59
I've added the rupee symbol to the training text. As specified in the tutorial https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#fine-tuning-for--a-few-characters.

Here is the file that i changed
[eng.training_text.txt](https://github.com/tesseract-ocr/tesseract/files/2803242/eng.training_text.txt)

**Comment by madhuri140** [comment] 2019-01-29 05:44
@Shreeshrii Also i cannot find the new training_text. But I've added the rupee symbol before training to the original eng.training_text. Anything else that i missed?

**Comment by Shreeshrii** [comment] 2019-01-29 16:53
Please see https://github.com/Shreeshrii/tessdata_engrupee

I am not able to reproduce the problem, even when using your training text.

```
tesseract -v
tesseract 4.0.0-246-g4d9bc
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

```

**Comment by Shreeshrii** [comment] 2019-02-18 13:37
@madhuri140 Is your issue solved. If so, please close it.

**Comment by Shreeshrii** [comment] 2019-04-13 08:21
@zdenop This issue can be closed.

**Closed** 2019-04-13 09:03 UTC
