### ISSUE TITLE
--user-patterns is not respected

### ISSUE THREAD

**Issue by eihli** [tesseract-ocr/tesseract#2941] opened 2020-04-02 21:05 UTC
This is either a bug, or the documentation needs to be clarified to say that patterns are merely suggestions to Tesseract and that the patterns may not be respected (if that is the case). 

### Environment

* **Tesseract Version**: 
tesseract 5.0.0-alpha-647-g4a00b
leptonica-1.80.0

* **Platform**: 

Linux 4.19.113-1-MANJARO x86_64 GNU/Linux

### Current Behavior:

![14](https://user-images.githubusercontent.com/1719584/78298934-32b24500-74e8-11ea-961c-1c8265759c3b.png)

I have a patterns file of 5 digits.

`\d\d\d\d\d`

`tesseract 14.png - --oem 3 --psm 7 -l eng --user-patterns /tmp/2294/patterns.txt`

Tesseract recognizes the comma.

### Expected Behavior:

I expect the pattern to be respected.

I've tried with a every option for `--oem` and I've tried specifying a pattern suffix in a bazaar file and moving my patterns file to my tessdata directory. Same results.

I cannot find anything in the manpage or other documentation that says how strictly patterns are respected.

https://tesseract-ocr.github.io/tessdoc/ImproveQuality#dictionaries-word-lists-and-patterns
https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#CONFIGFILE

### Suggested Fix:

I don't know. If this is expected behavior and patterns are mere suggestions that are not necessarily respected, then updating the documentation is the fix. If someone can confirm this, I'll see if I can understand the code well enough to write accurate documentation around it.

**Comment by amitdo** [comment] 2020-04-03 23:59
Duplicate of #2940

**Closed by amitdo** 2020-04-03 23:59 UTC
