### ISSUE TITLE
Actions CI failing for autotools-macos

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#3551] opened 2021-09-06 13:33 UTC
[Last working CI - two months ago](https://github.com/tesseract-ocr/tesseract/actions/runs/1046494204)

brew (macos-10.15-clang-12-autotools, macos-10.15, clang++) 
and
ports (macos-10.15-clang-12-autotools, macos-10.15, clang++)
is failing with
```

Run export "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig"
  export "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig"
  cd test
  clang++ -o basicapitest testing/basicapitest.cpp -I/usr/local/include -L/usr/local/lib `pkg-config --cflags --libs tesseract lept ` -pthread -std=c++11
  ./basicapitest
  shell: /bin/bash -e {0}
Undefined symbols for architecture x86_64:
  "_vDSP_dotprD", referenced from:
      tesseract::DotProductAccelerate(double const*, double const*, int) in libtesseract.a(libtesseract_la-simddetect.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: Process completed with exit code 1.
```

brew (macos-10.15-gcc-10-autotools, macos-10.15, g++-10) is failing in make tesseract phase

```
in file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework/Headers/../Frameworks/vecLib.framework/Headers/vecLib.h:25,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20,
                 from src/arch/simddetect.cpp:33:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h: In function 'vUInt16 vU16HalfMultiply(vUInt16, vUInt16)':
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h:379:84: note: use '-flax-vector-conversions' to permit conversions between vectors with differing element types or numbers of subparts
  379 |   vUInt16   __vbasicops_vB) { return _mm_mullo_epi16(__vbasicops_vA, __vbasicops_vB); }
      |                                                                                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/vBasicOps.h:379:54: error: cannot convert 'vUInt16' to '__m128i'
  379 |   vUInt16   __vbasicops_vB) { return _mm_mullo_epi16(__vbasicops_vA, __vbasicops_vB); }
      |                                                      ^~~~~~~~~~~~~~
      |                                                      |
      |                                                      vUInt16
```

**Comment by stweil** [comment] 2021-09-06 13:51
Commit 3ab8dcbf72e00981272d6f3ecd072655614baee4 added [vDSP_dotprD](https://developer.apple.com/documentation/accelerate/1450330-vdsp_dotprd).

**Comment by stweil** [comment] 2021-09-06 14:06
`basicapitest` now requires linker flag `-framework Accelerate` (which provides the missing symbol).

**Comment by stweil** [comment] 2021-09-06 14:11
It looks like `gcc` does not like the Apple header files for the Accelerate framework. To fix the gcc build on MacOS, we could add a new configure option `--disable-accelerate` and use that in CI.

**Comment by stweil** [comment] 2021-09-06 15:35
I made [fixes](https://github.com/stweil/tesseract/tree/issue3551) which are currently tested: https://github.com/stweil/tesseract/runs/3526147331.

**Comment by stweil** [comment] 2021-09-06 20:22
The issue is now fixed in Git master (a little bit too late for todays CI).

**Comment by amitdo** [comment] 2021-09-09 10:08
`note: use '-flax-vector-conversions' to permit conversions between vectors with differing element types or numbers of subparts`

https://reviews.llvm.org/D67678

**Comment by stweil** [comment] 2021-09-09 10:18
We could use that compiler option, but I don't know whether it is sufficient to support g++ with Accelerate framework.

I think that the current workaround to deactivate Accelerate code with g++ is sufficient. The default C++ compiler for MacOS is clang and has no such restrictions.

So I suggest to close this issue.

**Closed** 2021-09-09 10:28 UTC
Labels: bug, CI
