### ISSUE TITLE
Bad .box in tesseract 4

### ISSUE THREAD

**Issue by int255** [tesseract-ocr/tesseract#1448] opened 2018-04-03 03:38 UTC
------------------------

### Environment

* tesseract 4.00.00alpha
* **Commit Number**: 
* macOS High Sierra (10.13.4)
Darwin ****** 17.5.0 Darwin Kernel Version 17.5.0: Tue Mar 13 20:39:15 PDT 2018; root:xnu-4570.51.1~36/RELEASE_X86_64 x86_64

### Current Behavior:
1. Run the tesseract to generate .box file
tesseract -l chi_sim --oem 1 raster_20.png a -c tessedit_create_boxfile=1
(using tessdata_best)
2. use jTextBoxEditor to check the bounding boxes (see attached screenshot)
Although characters are correctly recognized, the bounding boxes are very wrong. 
Result much worse than tesseract 3.05.0, and is not usable at all.
<img width="1248" alt="screen shot 2018-04-03 at 11 34 08" src="https://user-images.githubusercontent.com/24381544/38227904-0f0b9894-3733-11e8-88e9-1869c7767b8c.png">

### Expected Behavior:
The bounding boxes should be tightly surrounding the glyph. My input is a super clean binary image already.
The problem is that bounding box is much worse than tesseract 3.05.00, and is totally unusable.

### Suggested Fix:
N/A

Also attached the raw png
![raster_20](https://user-images.githubusercontent.com/24381544/38227939-44a7caf4-3733-11e8-994c-52938a2260f9.png)

**Comment by Shreeshrii** [comment] 2018-04-03 05:30
tesseract 4, --oem 1 uses a line recogniser. It does not need accurate
boxes.

If boxes are important to you, you have to use --oem 0, only available with
files from tessdata repo.

**Comment by Shreeshrii** [comment] 2018-04-03 08:15
Duplicate of https://github.com/tesseract-ocr/tesseract/issues/1276

@zdenop Please close.

**Closed** 2018-04-03 09:05 UTC

**Comment by sagimann** [comment] 2018-10-03 14:50
problem is, when using oem 0, that OCR does not work well with non-solid backgrounds. The point is: if bboxes are not used by line recognizer, what other kind of data is available to correctly find the symbol on the image in terms of location?

**Comment by Shreeshrii** [comment] 2018-10-03 14:56
@sagimann Please post your comment under https://github.com/tesseract-ocr/tesseract/issues/1276 so that all related discussion about incorrect box coordinates is at one place. Thanks!
