### ISSUE TITLE
[macos] unsupported argument '-q' to option 'Wa,'

### ISSUE THREAD

**Issue by jeroen** [tesseract-ocr/tesseract#1500] opened 2018-04-20 19:08 UTC
Installing master from source on MacOS fails with: __configure: error: Your compiler does not have the necessary c++11 support! Cannot proceed.__ Looking at `config.log` the actual problem is 

```
configure:17144: result: no
configure:17149: checking whether compiler supports C++11
configure:17163: clang++ -c -g -O2 -Wa,-q -std=c++11  conftest.cpp >&5
clang: error: unsupported argument '-q' to option 'Wa,'
```

**Comment by amitdo** [comment] 2018-04-20 19:29
https://github.com/tesseract-ocr/tesseract/pull/1474
The cl passed.

**Comment by stweil** [comment] 2018-04-20 20:37
See my comments for PR #1474 which introduced this regression.

**Comment by stweil** [comment] 2018-04-23 20:10
@ic: The issue is still open after #1516.

**Comment by ic** [comment] 2018-04-23 23:42
@amitdo @stweil #1522 reverts the commits---sorry as I cannot handle the case more this week.

**Comment by amitdo** [comment] 2018-04-24 08:55
@zdenop, please close this issue.

**Closed** 2018-04-24 09:52 UTC

**Comment by jmercouris** [comment] 2018-06-01 21:42
This is still an issue on the latest release of master, with Macports

**Comment by stweil** [comment] 2018-06-02 07:19
Don't use gcc, then latest code from git should work. And update the Wiki if it gives wrong advice.

**Comment by ic** [comment] 2018-06-02 12:03
@jmercouris Can you give more details? My comments on the wiki apply to building with `g++`, MacPorts packaging, and the `Makefile`. As far as I know, the main stream is to use `CMake`.

The recent changes I have tried for building with `g++` with MacPorts and the `Makefile` worked at the time of my last changes (commit `4ded0d066e640e60e1640722860fc73d5838befb`).

As this issue is closed and the main stream is on a different toolchain, feel free to get in touch directly ([email?](https://github.com/ic)). Perhaps I can share more details on how I have it working here, and we can strengthen the wiki on this scenario.

**Comment by jmercouris** [comment] 2018-06-02 12:18
Hi, sorry for the delay in replying! I used @stweil's advice and was able to get it to compile without complaint on MacOS. Apparently issues in my compiled version (4.0) were due to incompatible lang training data (from 3.5) rather than compilation issues.

As per why I posted in this thread, if you attempt to use cc that ships with Xcocde, and you do follow the wiki advice about the flags for g++ from macports, you'll see this error come up. My fault for not reading clearly.

Lastly, I did also attempt to compile with gcc7 from Macports, but it didn't work, and I don't have the log anymore. I hope that all made sense!

**Comment by ic** [comment] 2018-06-02 13:37
Great you could solve your problem.

Now I see the `gcc` and `g++` issue. It turns out that the Xcode toolchain uses these names, but the actual tool is `clang`:

    > /usr/bin/g++
    clang: error: no input files

The wiki is really about the GNU tools, installed with MacPorts (but the problem would be the same with other packaging software). The fix for `g++` uses a flag that `clang` does not know.

As for your last comment on trying `gcc7`, this is an open problem. You mentioned using `master`, and I guess it is way behind the commit hash I gave above. As the team focuses on `CMake` and `clang`, I guess the other build options will slowly fade away. Perhaps a good thing---a simpler sofware is easier to maintain and debug ;-)

**Comment by Shreeshrii** [comment] 2018-06-02 13:44
It would be great if you can update the wiki home page
https://github.com/tesseract-ocr/tesseract/wiki
for correct steps to be followed for building on macos

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment] 2018-06-02 20:12
For Linux and macOS the mainstream build tool is the Autotools suite.
