### ISSUE TITLE
How to fine tunely tesseract 4.00 Beta.1 (by using Not text But exisiting images ?

### ISSUE THREAD

**Issue by godofcheerup** [tesseract-ocr/tesseract#1411] opened 2018-03-23 00:09 UTC
------------------------

### Environment

* **Tesseract Version**:  4.00 Beta 1.
* **Commit Number**:  
* **Platform**:  Ubuntu 16.04.03 LTS
In the wiki passage

![default](https://user-images.githubusercontent.com/25732817/37804954-787eac56-2e7a-11e8-8a6c-bc124ff36940.PNG)

### Current Behavior: 
In the tesseract 4.00 Beta.1 
I know the way to fine tunely with the text, But I don't know how to fine tunely with the exisiting images I have 

### Expected Behavior: 
I could train tesseract 4.00 by using exisiting images

**Comment by stweil** [comment] 2018-03-23 06:45
Is this a duplicate of #1172? Then please close it.

**Comment by godofcheerup** [comment] 2018-03-23 07:42
@stweil Really ? I could n't agree with you. Could you tell me more in detail~ plz

**Closed** 2018-03-26 00:32 UTC
