### ISSUE TITLE
user_words_suffix not working

### ISSUE THREAD

**Issue by TAQBIBT** [tesseract-ocr/tesseract#2584] opened 2019-07-21 21:25 UTC
We are trying to provide a user words file via available control params. Unfortunately I am getting below error : Error: failed to load user-words

Environment
tesseract v5.0.0-alpha.20190708
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
 Found libarchive 3.3.2 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5

tesseract eng.exp0697.tif out -l eng --dpi 300 --psm 8 --oem 1 bazaar

and bazaar file in the directory tessdata/configs

**Comment by bertsky** [comment] 2019-09-19 15:15
I believe I can confirm this. Tesseract does not bother to look for the user words and patterns files in tessdata anymore, or globbing the configured suffix. It just looks for the values configured as `user_words_suffix` and `user_patterns_suffix` verbatim in the CWD. This is a regression. Trying to find out more...

**Comment by bertsky** [comment] 2019-09-19 16:08
It seems that the only part _not_ working is the `_suffix` mechanism – whereas the `_file` mechanism does work (both via config file and with the CLI options `--user-patterns` and `--user-words`.

It looks like the `CCUtil` instance in `LSTMRecognizer` does not get the same `language_data_path_prefix` as in the `Tesseract`...

**Comment by bertsky** [comment] 2019-09-19 18:09
Found it: In 297d7d86ceb3b3365876b56f08a18cba066bf23f, I forgot to also bridge the non-LSTM CCUtil's runtime knowledge of `language_data_path_prefix` (which is used to concatenate with suffixes for additional files).

**Comment by stweil** [comment] 2019-10-06 20:41
@TAQBIBT, could you please try the latest code and close the issue if it was fixed?

**Comment by anergui** [comment] 2019-10-09 16:37
close #2584

**Closed** 2019-10-09 16:50 UTC
Labels: question
