### ISSUE TITLE
can not link tesseract built with cmake to my app

### ISSUE THREAD

**Issue by avestnik** [tesseract-ocr/tesseract#1256] opened 2018-01-02 18:07 UTC
I am working on large research project and need to run the same app on different platforms, so I have to use cmake. the problem is I fail to link tesseract with my app, it complains about missing tesseract lib.

I built up virtual machine with ubuntu 17.10 to demonstrate the problem
```
root@tess:~/w/test/build# cmake ..
-- The C compiler identification is GNU 7.2.0
... [cmake output skipped]
-- Build files have been written to: /root/w/test/build
root@tess:~/w/test/build# make
Scanning dependencies of target testtess
[ 50%] Building CXX object CMakeFiles/testtess.dir/main.cpp.o
[100%] Linking CXX executable testtess
/usr/bin/ld: cannot find -ltesseract
collect2: error: ld returned 1 exit status
CMakeFiles/testtess.dir/build.make:94: recipe for target 'testtess' failed
make[2]: *** [testtess] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/testtess.dir/all' failed
make[1]: *** [CMakeFiles/testtess.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

tesseract built from most recent source with cmake and installed to ~/local

app is quite simple:
main.cpp
```
#include <iostream>
#include <tesseract/baseapi.h>

int main() {
    tesseract::TessBaseAPI tess;
    tess.Init("/tmp/tessdata", "eng");

    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.9)
project(testtess)

set(CMAKE_CXX_STANDARD 11)

set(CMAKE_PREFIX_PATH $ENV{HOME}/local)

find_package(Tesseract CONFIG REQUIRED)
include_directories(${Tesseract_INCLUDE_DIRS})

add_executable(testtess main.cpp)

target_link_libraries(testtess ${Tesseract_LIBRARIES})
```

I guess the problem lies in descrepancies between TesseractConfig.cmake which uses tessaract for the library name
```
set(Tesseract_LIBRARIES tesseract)
```
and TesseractTargets-noconfig.cmake which uses libtesseract
```
set_property(TARGET libtesseract APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(libtesseract PROPERTIES
```

as a workaround I use target_link_libraries(testtess libtesseract), but I think problem should be fixed in source code

**Comment by egorpugin** [comment] 2018-01-05 14:19
So, changing the string to `target_link_libraries(testtess libtesseract)` works for you?

**Comment by egorpugin** [comment] 2018-01-05 15:52
Fixed in https://github.com/tesseract-ocr/tesseract/commit/000d027a9f40e17c9a90a907fa9e4a16616e61a0
Please, check and report any issues.

**Closed by egorpugin** 2018-01-05 15:52 UTC

**Comment by avestnik** [comment] 2018-01-05 17:27
thanks Egor, it works now

**Comment by timijntema** [comment] 2019-03-28 16:42
I am facing an issue that seems to have something to do with the fix for this issue @avestnik and @egorpugin . When trying to use `${Tesseract_LIBRARIES}` now it replaces the variable with `libtesseract`, which I think was intended in this fix. But if I use that variable in the `target_link_libraries()` function in cmake I end up with linker errors. If I then manually insert tesseract, which makes it `target_link_libraries(some_executable tesseract)` the linking process finishes without issue. Did I do something wrong?

I provided the CMakeLists.txt with this comment. Maybe you could have a look?
[CMakeLists.txt](https://github.com/tesseract-ocr/tesseract/files/3019154/CMakeLists.txt)

My environment:
CMake: 3.13.4
Tesseract: 4.1.0-rc1
Leptonica: 1.79.0
OS: Ubuntu 19.04 (Docker container)
G++: 8.3.0

**Comment by zdenop** [comment] 2019-03-29 09:48
How did you install tesseract? I just test it on windows and this works for me:

CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8.9)

# Specify minimum version
set(MINIMUM_TESSERACT_VERSION 4.1.0)
set(MINIMUM_LEPTONICA_VERSION 1.74)

set(PROJECT_NAME "tesseract-application")
project(${PROJECT_NAME} CXX)

# Include subdirectories
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/include)

# Check if libraries exist
find_package(Tesseract ${MINIMUM_TESSERACT_VERSION} REQUIRED)
message("Found ${Tesseract_LIBRARIES}")
find_package(Leptonica ${MINIMUM_LEPTONICA_VERSION} REQUIRED)
message("Found ${Leptonica_LIBRARIES}")

# Include directories
include_directories(${Tesseract_INCLUDE_DIRS})
include_directories(${Leptonica_INCLUDE_DIRS})

FILE(GLOB SRC_FILES src/*.cpp)

# The main program
add_executable(${PROJECT_NAME} ${SRC_FILES})

# Link with libraries
target_link_libraries(${PROJECT_NAME} ${Leptonica_LIBRARIES})
target_link_libraries(${PROJECT_NAME} ${Tesseract_LIBRARIES})
```
Build:
```
f:\Project-Personal\clang_shared\testtess\build64.clang> cmake .. -G Ninja  -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DCMAKE_BUILD_TYPE=Release
-- The CXX compiler identification is Clang 9.0.0
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang-cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Found libtesseract
Found leptonica
-- Configuring done
-- Generating done
-- Build files have been written to: F:/Project-Personal/clang_shared/testtess/build64.clang

f:\Project-Personal\clang_shared\testtess\build64.clang>cmake --build . --config Release
[2/2] Linking CXX executable tesseract-application.exe
```

**Note:** You can use other compilers too, but if you want to use cmake, tesseract and leptonica should be build by cmake too, because autotools build and cmake build does not provide the same output (e.g. library names).

**Comment by timijntema** [comment] 2019-03-29 10:09
I used the following commands for both leptonica and tesseract:
mkdir build
cd build
cmake ..
make install

**Comment by agiokas-dbg** [comment] 2020-03-02 17:55
On Ubuntu 18.04 having installed tesseract using `apt` this problem still exists. I suppose that the dpkg does not contain a cmake find?

**Comment by lucaszanella** [comment] 2020-03-04 19:05
I also can't find. I installed the tesseract dev package but it still wouldn't work

**Comment by lucaszanella** [comment] 2020-03-04 19:28
this `CMakeLists.txt` worked for me on Ubuntu. Please remove the noise, I don't have the time now.

I looked into the installation folder for `libtesseract-dev` and there's no cmake support, you gotta do it by hand.

```
cmake_minimum_required(VERSION 3.5)

project(roseek LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)

#set(CMAKE_AUTOUIC ON)
#set(CMAKE_AUTOMOC ON)
#set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
include_directories(/usr/include/tesseract/)
include_directories(/usr/include/leptonica/)
#find_package(Qt5 COMPONENTS Core Quick REQUIRED)

find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()
link_directories(
  ${CMAKE_CURRENT_SOURCE_DIR}/mingw-w64-x86_64-static-tesseract/lib/
)
SET(CMAKE_INSTALL_RPATH "${CMAKE_CURRENT_SOURCE_DIR}/libs/linux/")
add_executable(roseek
  main.cpp
  qml.qrc
  ImageStream.cpp
  YuvUtils.cpp
  #jpeg2rgb/src/jpeg_file.cpp
  #jpeg2rgb/src/rgb_file.cpp

  #CameraView.cpp
)

add_library(ctmedia_codec MODULE IMPORTED)
add_library(ctstream MODULE IMPORTED)
add_library(maincore MODULE IMPORTED)
add_library(jpegutil MODULE IMPORTED)




include_directories(${CMAKE_CURRENT_SOURCE_DIR}/mingw-w64-x86_64-static-tesseract/include/tesseract)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/mingw-w64-x86_64-static-tesseract/include/leptonica)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/jpeg2rgb/include)

IF (WIN32)
  set_target_properties(ctmedia_codec PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/win/lib/x64/CTMedia.lib)
  set_target_properties(ctstream PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/win/lib/x64/CTStream.lib)
  set_target_properties(maincore PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/win/lib/x64/WPMainCore.lib)

  include_directories(${CMAKE_CURRENT_SOURCE_DIR}/mingw-w64-x86_64-static-tesseract/include/)
ELSE()
  set_target_properties(ctmedia_codec PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/linux/libCTMedia_codec.so)
  set_target_properties(ctstream PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/linux/libCTStream.so)
  set_target_properties(maincore PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/linux/libWPMainCore.so)
  set_target_properties(jpegutil PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/linux/libRSJpegUtil.so)

ENDIF()


include_directories("include")
#target_compile_definitions(roosek2
#  PRIVATE $<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:QT_QML_DEBUG>)
#target_link_libraries(roosek2
#  PRIVATE Qt5::Core Qt5::Quick ctmedia_codec ctstream maincore ${Tesseract_LIBRARIES})
target_link_libraries(roseek ctmedia_codec ctstream maincore jpegutil tesseract lept)
#target_link_libraries(roseek ${CMAKE_CURRENT_SOURCE_DIR}/win_bin/lib/x64/WPMainCore.lib ${CMAKE_CURRENT_SOURCE_DIR}/mingw-w64-x86_64-static-tesseract/lib/libtesseract.a)


```

**Comment by Robyer** [comment] 2021-09-13 17:04
I have same problem as timijntema in https://github.com/tesseract-ocr/tesseract/issues/1256#issuecomment-477676729
The ${Tesseract_LIBRARIES} is "libtesseract" but when I use it in `target_link_libraries()` I end up with linker errors. I must manually use "tesseract" instead, then it works correctly.

I built Leptonica and Tesseract from source via CMake. I'm on Ubuntu 20.04.

Can someone verify the correctness of CMake configuration on Linux and whether the "fix" should be reverted? Perhaps avestnik had something wrong on his side, because I and others here (lucaszanella, timijntema, probably also agiokas-dbg) experience the problem **because** of the fix (or maybe something else has been changed somewhere else that made this change wrong). What do you think, @egorpugin ?

**Comment by egorpugin** [comment] 2021-09-13 19:48
Hi,

I do not use cmake setup and do not know cmake installation procedures well.

**Comment by Robyer** [comment] 2021-09-13 21:19
@egorpugin I looked into it a bit and I believe it must be changed back.

- Since commit https://github.com/tesseract-ocr/tesseract/commit/52cac3a42ef2b823b9367b9ee2d1d84f8eda4ea0 the name of the library file is just `tesseract`. This commit is few months older than the original issue, but the explanation may be that original poster had used older version that was previously really named "liblibtesseract" so in the config file he needed to use "libtesseract".
- He says that `I guess the problem lies in descrepancies between TesseractConfig.cmake which uses tessaract for the library name (...) and TesseractTargets-noconfig.cmake which uses libtesseract` but I can't find such file TesseractTargets-noconfig.cmake anywhere. Not even the `set_property(TARGET libtesseract` line in whole project.
- Leptonica also use just `leptonica` in that file (without the lib prefix).
- As I stated in previous comment, with current version is my experience (+ experience of others in previous comments) that it doesn't work with current `libtesseract` name and it must be renamed to just `tesseract` to make it work, as it was before the "fix".

So could you revert the https://github.com/tesseract-ocr/tesseract/commit/000d027a9f40e17c9a90a907fa9e4a16616e61a0 commit?

**Comment by egorpugin** [comment] 2021-09-14 01:13
> So could you revert the 000d027 commit?

Not sure.
We have "tesseract library" named `libtesseract`. `tesseract` is the name of command line tool.

**Comment by stweil** [comment] 2021-09-14 05:09
Simply reverting 000d027a9f40e17c9a90a907fa9e4a16616e61a0 would result in a buggy setting: repeated builds always rebuild `libtesseract` then:

```
$ make
[ 77%] Built target libtesseract
[ 78%] Built target tesseract
[ 82%] Built target common_training
[ 87%] Built target unicharset_training
[ 89%] Built target pango_training
[...]
```

**Comment by Robyer** [comment] 2021-09-14 07:25
@stweil No, look at the file that is being changed in that commit. It is `cmake/templates/TesseractConfig.cmake.in` which is **not** used for compilation of the Tesseract itself, but is copied at install time into system. This file is then used by CMake when someone uses Tesseract in their project and uses [`find_package()`](https://cmake.org/cmake/help/v3.0/command/find_package.html) command in their `CMakeLists.txt` to find the Tesseract library in system. Like this:

```
cmake_minimum_required(VERSION 3.10)

project(myapp)

find_package(Tesseract REQUIRED)

include_directories(${Tesseract_INCLUDE_DIRS})

add_executable(myapp main.cpp)

target_link_libraries(myapp ${Tesseract_LIBRARIES})
```

In current state `${Tesseract_LIBRARIES}` contains value `libtesseract`. This value is propagated to linker and it end up with this error when building the "myapp" project:

```
[build] Consolidate compiler generated dependencies of target myapp
[build] [ 50%] Linking CXX executable myapp
[build] /usr/bin/ld: cannot find -llibtesseract
[build] collect2: error: ld returned 1 exit status
```

You see that value is transformed into parameter "-llibtesseract" which is wrong as it has to be just "-ltesseract". And indeed, as commented also by the others in this thread, when we manually use:

```
target_link_libraries(myapp tesseract)
```

then it works without problem.

**Comment by egorpugin** [comment] 2021-09-14 10:51
@Robyer

You should use libtesseract target in your scripts. Not library name.
And when you use it, cmake will do everything for you.

**Comment by Robyer** [comment] 2021-09-14 11:05
@egorpugin Can you give me example of what you mean? E.g. update my example CMake code above.

But even if it's just different way of including the library, it doesn't change the fact that the ${Tesseract_LIBRARIES} is wrong and should contain name "tesseract" and not "libtesseract".

**Comment by zdenop** [comment] 2021-09-14 17:42
If I got right remark from [template](https://github.com/tesseract-ocr/tesseract/blob/main/cmake/templates/TesseractConfig.cmake.in), your configuration should looks like this:


```
cmake_minimum_required(VERSION 3.10)

project(myapp)

find_package(Tesseract REQUIRED)

include_directories(${Tesseract_INCLUDE_DIRS})

add_executable(myapp main.cpp)
target_link_libraries(myapp Tesseract::libtesseract)
```

**Comment by Robyer** [comment] 2021-09-14 19:37
@zdenop Yes, this works, but this is just different (perhaps more recent) way how to include the library. But the old way should still work, don't you agree? With Leptonica it works. With OpenCV it works. This is just issue in Tesseract and it should be fixed (especially before 5.0.0 release, imho).

See different tutorials where they use it the `${<name>_LIBRARIES}` way to see that it is legal way to do it:
- JetBrains tutorial example - https://www.jetbrains.com/help/clion/quick-cmake-tutorial.html#boost
  - `target_link_libraries(cmake_testapp_boost ${Boost_LIBRARIES})`
- Old CMake tutorial - https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Find-Libraries#using-external-libraries
  - `target_link_libraries (helloworld ${BZIP2_LIBRARIES})`
- OpenCV tutorial - https://docs.opencv.org/master/db/df5/tutorial_linux_gcc_cmake.html
  - `target_link_libraries( DisplayImage ${OpenCV_LIBS} )`

**Comment by egorpugin** [comment] 2021-09-14 20:01
`target_link_libraries(myapp Tesseract::libtesseract)` is the preferred modern way.
We should use it. Old cmake is for tess4 mostly.

**Comment by Robyer** [comment] 2021-09-16 09:26
@egorpugin It may be used as preferred way in documentation, but the `${<name>_LIBRARIES}` must still hold correct value. It is **not** deprecated. And you can see that basically every library defined by CMake itself provides BOTH imported targed AND these variables. Every library is linked correctly when you use this variable, only Tesseract is broken.

Just some examples from **current** CMake documentation:
- https://cmake.org/cmake/help/v3.21/module/FindBoost.html
- https://cmake.org/cmake/help/v3.21/module/FindALSA.html
- https://cmake.org/cmake/help/v3.21/module/FindBZip2.html
- https://cmake.org/cmake/help/v3.21/module/FindCURL.html
- https://cmake.org/cmake/help/v3.21/module/FindGIF.html
- https://cmake.org/cmake/help/v3.21/module/FindLibArchive.html
- ...

All of them provide both variables and the imported target. For FindBoost they provide also examples where you can see that both ways are valid and being used.

I really don't understand what is the problem with fixing the variable that Tesseract defines wrongly. Also note that it was defined correctly when that code was first introduced, but because of bug in different place (that created the library as "liblibtesseract") this issue was originally created and (wrong) fix was introduced. But since the other bug was fixed (https://github.com/tesseract-ocr/tesseract/commit/52cac3a42ef2b823b9367b9ee2d1d84f8eda4ea0), this "fix" now makes it broken (for more than 2.5 years already). So again, commit https://github.com/tesseract-ocr/tesseract/commit/000d027a9f40e17c9a90a907fa9e4a16616e61a0 must be reverted to make it correct.

**Comment by egorpugin** [comment] 2021-09-16 12:10
> must still hold

Who says that?

> ...

Can you send a PR?

**Comment by Robyer** [comment] 2021-09-17 19:42
PR created.
