### ISSUE TITLE
configure fails to test -mavx* with user CXXFLAGS

### ISSUE THREAD

**Issue by luke-jr** [tesseract-ocr/tesseract#3891] opened 2022-08-05 20:14 UTC
configure tests -mavx512f (and other variants) with `$CXX $CXXFLAGS -mavx512f` (simplified) which detects compiler AVX512F support, but then builds with `$CXX -mavx512f $CXXFLAGS` which fails because my CXXFLAGS includes `-mno-avx512f`.

Probably the configure check should be adjusted so it detects no AVX512F support when the user specifies -mno-avx512f in CXXFLAGS. Or at the very least (if there's reason to enforce runtime detection even when the user has said "no"), building should use the same order so AVX512F is force-enabled for the files that use it.

**Comment by stweil** [comment] 2022-08-05 20:25
Why do you need that very special value of `CXXFLAGS`? Without `-mno-avx512f` there would be no problem, and I don't see a good reason why it should be useful.

**Comment by stweil** [comment] 2022-08-05 20:28
Technically this issue is a duplicate of #2841, so let's discuss it further there. I close it here.

**Closed by stweil** 2022-08-05 20:28 UTC
Labels: duplicate
