### ISSUE TITLE
wrong box sizes in box file

### ISSUE THREAD

**Issue by xwodas** [tesseract-ocr/tesseract#1939] opened 2018-10-02 11:43 UTC
At least since tesseract 4.0.0-beta.1, I find grossly wrong box sizes for some letters in a box file. I guess that impacts all who use box files that are written out by the program, e.g., in order to create training sets.

I have only seen this with  wtidth's and only for some letters, not all in a box file.

I only found it since I have some after-burner code that uses box sizes for further improvement. of the OCR text. This stopped working not so long ago but I cannot say whether that includes any earlier versions than 4.0.0-beta.1. On Ubuntu, stuff is updated almost daily and I do not exactly recall when it stopped working since I looked into it only the other day.

I attach a complete example. Look at line 757 in the box file (003.box). The letter "e" is only 11 pixels wide. This is much less than the average character width. Cf. letter "i" in the next line which is 26 pixels wide and the "e" looks about 2-3 times its width. This has started to happen in this or in recent tesseract versions. It happens not to all but to enough letters on a page in order to be annoying.

[width_problem.zip](https://github.com/tesseract-ocr/tesseract/files/2437653/width_problem.zip) (The box file is converted to Latin-1)

The command line I use is:

tesseract 003.tif box -l deu batch makebox

**Comment by stweil** [comment] 2018-10-02 12:33
Which `deu.traineddata` did you use? My resulting box file looks different

**Comment by amitdo** [comment] 2018-10-02 12:44
Duplicate of #1276 and #1448.

**Comment by xwodas** [comment] 2018-10-02 13:08
I use nowadays the default language files provided by the apt-get mechanism on Ubuntu. Can I find out from the file itself in some way which version it is?

I guess, you will see the same in any box file for other versions of the German language data. It is not totally reproducible anyway. If I, e.g., use the same image in another color or differently filtered (full color vs, grey scale) I also get different result. But always with the same problem, just different characters on the page.

Thanks that you responded so quickly and that you look into it!

--------------------------------------------
On Tue, 10/2/18, Stefan Weil <notifications@github.com> wrote:

 Subject: Re: [tesseract-ocr/tesseract] wrong box sizes in box file (#1939)
 To: "tesseract-ocr/tesseract" <tesseract@noreply.github.com>
 Cc: "xwodas" <jens.sadowski@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, October 2, 2018, 2:35 PM
 
 Which
 deu.traineddata did you use? My resulting box
 file looks different
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by stweil** [comment] 2018-10-02 13:10
Debian / Ubuntu provide traineddata from http://github.com/tesseract-ocr/tessdata_fast.

Get traineddata from http://github.com/tesseract-ocr/tessdata and add `--oem 0` for the legacy OCR engine. That should give better results.

**Comment by stweil** [comment] 2018-10-02 13:13
I close this issue as it is a duplicate of #1276 where it can be discussed further.

**Closed by stweil** 2018-10-02 13:13 UTC
Labels: duplicate

**Comment by stweil** [comment] 2018-10-02 13:52
It also looks at `/usr/share/tesseract-ocr/4.00/tessdata/`, but your `deu.traineddata` does not support `--oem 0`. Get a new one from http://github.com/tesseract-ocr/tessdata.
