### ISSUE TITLE
CMake currently does not support Tesseract builds for non Intel hosts (Android cross-build error)

### ISSUE THREAD

**Issue by Bleach665** [tesseract-ocr/tesseract#2337] opened 2019-03-19 14:25 UTC
Host OS: Linux xubuntu64 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux; CMake GUI 3.10.2; Android toolchain - android-ndk-r15c; gcc version 7.3.0; Tesseract rev. ac7ea4322a23af46fa6ddccf23497bd06f1e2d38.
CMake GUI changes: CMAKE_PREFIX_PATH:PATH="/home/bleach/Lib/leptonica/build_arm" specified.
Build error received:
<details>
  <summary>make output</summary>
  
````clang++: warning: argument unused during compilation: '-mavx' [-Wunused-command-line-argument]
/home/bleach/Lib/tesseract/source/src/arch/dotproductavx.cpp:20:2: error: Implementation only for AVX capable architectures
#error Implementation only for AVX capable architectures
 ^
In file included from /home/bleach/Lib/tesseract/source/src/arch/dotproductavx.cpp:23:
In file included from /home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/immintrin.h:28:
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:47:5: error: use of undeclared identifier '__builtin_ia32_emms'; did you mean
      '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:47:5: note: '__builtin_isless' declared here
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:47:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:64:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:81:12: error: use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:143:19: error: use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:173:19: error: use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:203:19: error: use of undeclared identifier '__builtin_ia32_packuswb'
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:230:19: error: use of undeclared identifier '__builtin_ia32_punpckhbw'
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:253:19: error: use of undeclared identifier '__builtin_ia32_punpckhwd'
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:274:19: error: use of undeclared identifier '__builtin_ia32_punpckhdq'
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:301:19: error: use of undeclared identifier '__builtin_ia32_punpcklbw'
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:324:19: error: use of undeclared identifier '__builtin_ia32_punpcklwd'
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:345:19: error: use of undeclared identifier '__builtin_ia32_punpckldq'
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:366:19: error: use of undeclared identifier '__builtin_ia32_paddb'; did you mean
      '__builtin_arm_qadd'?
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:366:19: note: '__builtin_arm_qadd' declared here
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:366:40: error: cannot initialize a parameter of type 'int' with an rvalue of type
      '__v8qi' (vector of 8 'char' values)
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                                       ^~~~~~~~~~~~
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:387:19: error: use of undeclared identifier '__builtin_ia32_paddw'; did you mean
      '__builtin_arm_qadd'?
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:366:19: note: '__builtin_arm_qadd' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:387:40: error: cannot initialize a parameter of type 'int' with an rvalue of type
      '__v4hi' (vector of 4 'short' values)
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
                                       ^~~~~~~~~~~~
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:408:19: error: use of undeclared identifier '__builtin_ia32_paddd'; did you mean
      '__builtin_arm_qadd'?
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
/home/bleach/Lib/android-ndk-r15c/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/5.0.300080/include/mmintrin.h:366:19: note: '__builtin_arm_qadd' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
CMakeFiles/libtesseract.dir/build.make:86: recipe for target 'CMakeFiles/libtesseract.dir/src/arch/dotproductavx.cpp.o' failed
make[2]: *** [CMakeFiles/libtesseract.dir/src/arch/dotproductavx.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/libtesseract.dir/all' failed
make[1]: *** [CMakeFiles/libtesseract.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
````
</details>

Please advise how to quickly remove AVX(2) support from the code or Cmake config. I tried
<details>
  <summary>my changes</summary>

````--------------------------------- configure.ac ---------------------------------
index ef5d1b47..3afc4275 100644
@@ -117,14 +117,14 @@ AM_CONDITIONAL([AVX2_OPT], false)
 AM_CONDITIONAL([SSE41_OPT], false)
 AM_CONDITIONAL([MARCH_NATIVE_OPT], false)
 
-AX_CHECK_COMPILE_FLAG([-mavx], [avx=true], [avx=false])
+AX_CHECK_COMPILE_FLAG([-mavx], [avx=false], [avx=false])
 if $avx; then
-    AM_CONDITIONAL([AVX_OPT], true)
+    AM_CONDITIONAL([AVX_OPT], false)
 fi
 
-AX_CHECK_COMPILE_FLAG([-mavx2], [avx2=true], [avx2=false])
+AX_CHECK_COMPILE_FLAG([-mavx2], [avx2=false], [avx2=false])
 if $avx2; then
-    AM_CONDITIONAL([AVX2_OPT], true)
+    AM_CONDITIONAL([AVX2_OPT], false)
 fi
 
 AX_CHECK_COMPILE_FLAG([-msse4.1], [sse41=true], [sse41=false])

---------------------------- src/arch/simddetect.h ----------------------------
index def66896..c137e118 100644
@@ -31,12 +31,12 @@ extern DotProductFunction DotProduct;
 class SIMDDetect {
  public:
   // Returns true if AVX is available on this system.
-  static inline bool IsAVXAvailable() { return detector.avx_available_; }
+  static inline bool IsAVXAvailable() { return false; }
   // Returns true if AVX2 (integer support) is available on this system.
-  static inline bool IsAVX2Available() { return detector.avx2_available_; }
+  static inline bool IsAVX2Available() { return false; }
   // Returns true if AVX512 Foundation (float) is available on this system.
   static inline bool IsAVX512FAvailable() {
-    return detector.avx512F_available_;
+    return false;
   }
   // Returns true if AVX512 integer is available on this system.
   static inline bool IsAVX512BWAvailable() {
````
</details>
, but it did not help.

**Comment by stweil** [comment] 2019-03-19 14:58
Is this a duplicate of issue #2334? All errors shown in your make output are in files which are not part of the Tesseract sources. Those files obviously are for the Intel architecture, so they should not be included by ARM toolchains. This looks like a wrong build setting.

**Comment by zdenop** [comment] 2019-03-19 15:32
@stweil: this is cmake related related issue while 2334 is autotools related, so from perspective of build toots it is not duplicate.
I am not sure if our current cmake configuration will work for android build without modification, but just setting CMAKE_PREFIX_PATH [seems to be not sufficient](https://groups.google.com/d/msg/tesseract-ocr/zuZYuz12oQc/VCavzreVCQAJ)...

**Comment by stweil** [comment] 2019-03-19 15:39
Thank you, @zdenop. Yes, the current CMake has [fixed unconditional settings for Intel builds](https://github.com/tesseract-ocr/tesseract/blob/master/CMakeLists.txt#L325) and cannot support cross builds for other architectures like ARM. I update the summary.

**Comment by Bleach665** [comment] 2019-03-19 15:49
Sorry, I forgot to mention that host os is running under VirtualBox, which in turn is running under Win10. CPU Intel Xeon X.

**Comment by zdenop** [comment] 2019-04-22 07:07
@Bleach665 : try current master - there is detection of available features in cmake.

**Comment by Bleach665** [comment] 2019-04-22 10:23
@zdenop.
I do not have at fingertips Linux, therefore I try to build in Windows 10.
I configure Tesseract via CMake with Android 16 toolchain and MinGW makefile. MinGW was taken from Qt distrib. 
Leptonica configured in such way was build successfully. Tesseract CMake configuration performed well (with minimal changes CMakeList.txt), but on build I receive errors:
````
In file included from E:\Lib_prebuild\tesseract\source\src\ccmain\adaptions.cpp:26:
E:\Lib_prebuild\tesseract\source\src\ccmain/tesseractclass.h:30:10: fatal error: 'allheaders.h' file not found
#include "allheaders.h"             // for pixDestroy, pixGetWidth, pixGetHe...
````

**Comment by zdenop** [comment] 2019-04-22 11:15
Seems like missing include path for leptonica. How did you run
configuration?

Dňa po 22. 4. 2019, 12:24 Bleach665 <notifications@github.com> napísal(a):

**Comment by Bleach665** [comment] 2019-04-22 11:24
Just run path-to\mingw32-make.exe in CMake build directory.

**Comment by zdenop** [comment] 2019-04-22 11:49
Make does not start configuration....


Dňa po 22. 4. 2019, 13:24 Bleach665 <notifications@github.com> napísal(a):

**Comment by Bleach665** [comment] 2019-04-22 12:30
Oh, I did not read carefully. I wrote a little of text, maybe it would helpfully to draw up instruction in future.
CMake GUI was used. After 'configure' button was pressed next parameters were specified:
Specify the generator for this project - MinGW Makefile
Specify toolchain file for cross-compiling was selected
![qqq1](https://user-images.githubusercontent.com/6595124/56500208-9aa78f80-6512-11e9-8928-1612834261cf.png)
On the next page toolchain file was specified.
![qqq2](https://user-images.githubusercontent.com/6595124/56500234-a4c98e00-6512-11e9-8aa4-b8157c9bfad1.png)
In my case CMAKE_SH was defined, because msys64\usr was in my PATH envinronment variable. So we undefine it to perform success configure.
After that we need to specify CMAKE_MAKE_PROGRAM with mingw32-make.exe path. MinGW was taken from Qt distribution.
![qqq3](https://user-images.githubusercontent.com/6595124/56500261-b57a0400-6512-11e9-9241-c8b79d092f91.png)

Configure button pressed again.
Next, let's point out the path to Leptonica - Leptonica_DIR must point to Leptonica install CMake folder.
Configure, Generate.
Open command prompt, go to CMake configure output folder. Type path-to-mingw\mingw32-make.exe install.
Done.

**Comment by Bleach665** [comment] 2019-04-22 17:12
In xubuntux64 I receive same error:
````
[ 32%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/elst2.cpp.o
[ 32%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/errcode.cpp.o
[ 33%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/fileio.cpp.o
/home/bleach/Lib/Tesseract/source/src/ccutil/fileio.cpp:23:10: fatal error: 'glob.h' file not found
#include <glob.h>
         ^~~~~~~~
1 error generated.
CMakeFiles/libtesseract.dir/build.make:1958: recipe for target 'CMakeFiles/libtesseract.dir/src/ccutil/fileio.cpp.o' failed
make[2]: *** [CMakeFiles/libtesseract.dir/src/ccutil/fileio.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/libtesseract.dir/all' failed
make[1]: *** [CMakeFiles/libtesseract.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by Shreeshrii** [comment] 2019-04-22 18:15
Configure button pressed again.
Next, let's point out the path to Leptonica - Leptonica_DIR must point to Leptonica install CMake folder.
Configure, Generate.
Open command prompt, go to CMake configure output folder. Type path-to-mingw\mingw32-make.exe install.
Done.

Are you building leptonica after tesseract?

You need to build it before.

**Comment by Bleach665** [comment] 2019-04-22 21:59
Leptonica was build before Tesseract. As far as I remember in CMake config Leptonica find_package is with REUARED flag, so Leptonica_DIR should point to right dir (cmake dir in our install dir), if not then we get an error while configuring.

And maybe that's important, `TARGET_ARCHITECTURE` was set to `armeabi-v7a`.

**Comment by zdenop** [comment] 2019-04-23 21:29
@Bleach665 : `glob.h` is provided by os ([linux ](http://man7.org/linux/man-pages/man3/glob.3.html) or [android](https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6/+/refs/heads/tools_r20/sysroot/usr/include/glob.h)) so this is not tesseract issue anymore. Seems like you need to setup include path for cmake, so compiler finds all needed system header files.

**Comment by Bleach665** [comment] 2019-04-24 16:27
@zdenop . Yes, 
> if(ANDROID_TOOLCHAIN)
>   include_directories(${ANDROID_TOOLCHAIN}/sysroot/usr/include)
> endif()
> 
fix it.
But after fix we have another error:
````
[ 19%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/errcode.cpp.o
[ 20%] Building CXX object CMakeFiles/libtesseract.dir/src/ccutil/fileio.cpp.o
E:\Lib_prebuild\tesseract\source\src\ccutil\fileio.cpp:121:7: error: use of undeclared identifier 'glob'
  if (glob(pattern, 0, nullptr, &pglob) == 0) {
      ^
E:\Lib_prebuild\tesseract\source\src\ccutil\fileio.cpp:125:5: error: use of undeclared identifier 'globfree'
    globfree(&pglob);
    ^
2 errors generated.
CMakeFiles\libtesseract.dir\build.make:1088: recipe for target 'CMakeFiles/libtesseract.dir/src/ccutil/fileio.cpp.o' failed
mingw32-make[2]: *** [CMakeFiles/libtesseract.dir/src/ccutil/fileio.cpp.o] Error 1
CMakeFiles\Makefile2:71: recipe for target 'CMakeFiles/libtesseract.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/libtesseract.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
````

**Comment by zdenop** [comment] 2019-04-24 18:16
Sorry, but this is not tesseract related. You should go to some android forum.

**Comment by Bleach665** [comment] 2019-04-24 18:40
Ok.
Only for testing i directly define `__ANDROID_API_FUTURE__`:
`add_compile_definitions(__ANDROID_API_FUTURE__)` added to CMake config file.

So, with all of the above described changes we have successful CMake configuration and build for Android cross build in Widows using android NDK toolchain and MinGW32.
Patch:
[0001-fix-Android-cross-build-in-Windows-and-Linux.zip](https://github.com/tesseract-ocr/tesseract/files/3113709/0001-fix-Android-cross-build-in-Windows-and-Linux.zip)

**Comment by zdenop** [comment] 2019-04-24 19:43
thanks

**Closed** 2019-04-24 19:43 UTC
Labels: bug, build_process

**Comment by ismail** [comment] 2019-04-29 11:32
This breaks the normal Linux build:

```
CMake Error at CMakeLists.txt:151 (find_package):
  Could not find a package configuration file provided by "Leptonica"
  (requested version 1.74) with any of the following names:

    LeptonicaConfig.cmake
    leptonica-config.cmake

  Add the installation prefix of "Leptonica" to CMAKE_PREFIX_PATH or set
  "Leptonica_DIR" to a directory containing one of the above files.  If
  "Leptonica" provides a separate development package or SDK, be sure it has
  been installed.
```

This is because

```
-    if (NOT Leptonica_DIR AND NOT MSVC)
+    if (NOT Leptonica_DIR AND NOT MSVC AND COMMAND pkg_check_modules)
```

checks for ```pkg_check_modules``` but this function is not defined until you require ```PkgConfig``` hence creating a chicken-egg problem.

**Comment by zdenop** [comment] 2019-04-29 16:04
thanks for report. should be fixed.

**Comment by gorankarlic** [comment] 2019-05-06 16:54
Commit 0fe9290 actually fixed cmake based build on macOS, which I could not make work otherwise (missing `-lleptonica` although `libleptonica` present in `/usr/local/lib`). d5f23a6 makes it fail again.

**Comment by gorankarlic** [comment] 2019-05-06 19:56
### 0fe9290 works on MacOS 10.14.4
```bash
git clone https://github.com/tesseract-ocr/tesseract.git target/tesseract
cd tesseract
git reset --hard 0fe929010a09c99ec8bf0c25ad89d2872454ffd0
mkdir build && cd build
cmake ..
make -j8
```
```bash
...
[100%] Built target tesseract
```
### 7a5b9b8 fails

```bash
git clone https://github.com/tesseract-ocr/tesseract.git target/tesseract
cd tesseract
mkdir build && cd build
cmake ..
```
```bash
...
Configuring tesseract version 5.0.0-alpha-45-g7a5b...
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at CMakeLists.txt:149 (message):
  Missing required pkg-config


-- Configuring incomplete, errors occurred!
```

Although `which pkgconf` outputs `/usr/local/bin/pkgconf` - but this error is fixable by specifying the `pgkconf` path explicitly:
```bash
cmake .. -D PKG_CONFIG_EXECUTABLE=/usr/local/bin/pkgconf
make -j8
```
```bash
...
[ 99%] Linking CXX shared library libtesseract.dylib
ld: library not found for -lleptonica
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libtesseract.5.0.0.dylib] Error 1
make[1]: *** [CMakeFiles/libtesseract.dir/all] Error 2
make: *** [all] Error 2
```

Altough Leptonica is present in `/usr/local/lib`:
```bash
ls /usr/local/lib/liblept*
```
```bash
/usr/local/lib/liblept.dylib -> libleptonica.1.79.0.dylib
/usr/local/lib/libleptonica.1.79.0.dylib
/usr/local/lib/libleptonica.5.3.0.dylib -> libleptonica.1.79.0.dylib
/usr/local/lib/libleptonica.dylib -> libleptonica.5.3.0.dylib
```
Thanks for the quick reply.

**Comment by zdenop** [comment] 2019-05-07 06:54
How did you install leptonica? Leptonica cmake build also requires pkg-config.

**Comment by gorankarlic** [comment] 2019-05-07 10:01
Leptonica seems to be able compile even without `pkgconfig`:
```bash
git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica && mkdir build && cd build
cmake ..
```
```bash
...
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
...
-- Generating done
```

`Makefile` is created and `make` works just fine.

My approach is a bit unusual, as I am compiling everything from source, as most users seem to install it using `brew` or `port`.

**Comment by zdenop** [comment] 2019-05-08 16:52
@Bleach665: can you please test the latest code if it works for you?

**Comment by Bleach665** [comment] 2019-05-10 09:04
@zdenop. I will be able to do it from the middle of next week.

**Comment by Bleach665** [comment] 2019-05-15 08:57
@zdenop. I try perform cross build in Windows 10, mingw32, CMake 3.13.4, android ndk r16b (a few commits ago build with this configuration was successful) and get CMake configuration error:

<details>
  <summary>CMake gui output:</summary>

````
fatal: not a git repository (or any of the parent directories): .git

Configuring tesseract version 5.0.0-alpha...
CMake Error at CMakeLists.txt:165 (add_subdirectory):
  add_subdirectory given source ".cppan" which is not an existing directory.


Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR) 
No support for auto-detection of the target instruction set/extension

General configuration for Tesseract 5.0.0-alpha
--------------------------------------------------------
Build type: 
Compiler: Clang
Used standard: C++14
CXX compiler options:  -isystem E:/Lib_prebuild/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   --std=c++11
Linker options: -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot E:/Lib_prebuild/android-ndk-r16b/platforms/android-14/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc  
Install directory: E:/Lib_prebuild/tesseract/build_arm7
Architecture flags: 
Vector unit list: 
AVX_OPT: OFF
AVX2_OPT: OFF
SSE41_OPT: OFF
MARCH_NATIVE_OPT: OFF
sim_flags: 

Build with cppan [CPPAN_BUILD]: OFF
Build with openmp support [OPENMP_BUILD]: OFF
Disable disable graphics (ScrollView) [GRAPHICS_DISABLED]: OFF
Enable embedded build [EMBEDDED]: OFF
Disable the legacy OCR engine [DISABLED_LEGACY_ENGINE]: OFF
Build training tools [BUILD_TRAINING_TOOLS]: ON
Build tests [BUILD_TESTS]: OFF
--------------------------------------------------------

Configuring incomplete, errors occurred!
See also "E:/Lib_prebuild/tesseract/prebuild_arm7/CMakeFiles/CMakeOutput.log".
See also "E:/Lib_prebuild/tesseract/prebuild_arm7/CMakeFiles/CMakeError.log".
````
</details>

[CMakeError.log](https://github.com/tesseract-ocr/tesseract/files/3181711/CMakeError.log)

It look like problem is with using OpenCL.

**Comment by zdenop** [comment] 2019-06-07 06:16
@Bleach665 can you please do check once more time?

**Comment by Bleach665** [comment] 2019-06-07 18:21
@zdenop.
Tested on 
Winsows 10 x64, CMake gui 3.13.4, MinGW 530_32 (from Qt lib), Android NDK r16b toolchain, rev 17c8ac29a261c352b9868c3d716fa293f6910cf5.
Tesseract was configured with CMake GUI and Android toolchain and built with MinGW.
Build errors:
```
[ 99%] Built target libtesseract
[100%] Linking CXX executable bin\tesseract
E:/Lib_prebuild/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lpvt.cppan.demo.gif
E:/Lib_prebuild/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lpvt.cppan.demo.jpeg
E:/Lib_prebuild/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lpvt.cppan.demo.png
E:/Lib_prebuild/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lpvt.cppan.demo.tiff
E:/Lib_prebuild/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lpvt.cppan.demo.webmproject.webp
E:/Lib_prebuild/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lpvt.cppan.demo.openjpeg.openjp2
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles\tesseract.dir\build.make:87: recipe for target 'bin/tesseract' failed
mingw32-make.exe[2]: *** [bin/tesseract] Error 1
CMakeFiles\Makefile2:108: recipe for target 'CMakeFiles/tesseract.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/tesseract.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```

CMake changes:
```
BUILD_TRAINING_TOOLS:BOOL=0
OPENMP_BUILD:BOOL=0
CMAKE_INSTALL_PREFIX:PATH=E:/Lib_prebuild/tesseract/build_arm7
Leptonica_DIR:PATH=E:/Lib_prebuild/leptonica/build_arm7/cmake
CPPAN_BUILD:BOOL=0
TARGET_ARCHITECTURE:STRING=armeabi-v7a
CMAKE_MAKE_PROGRAM:FILEPATH=C:/Lib/Qt/Tools/mingw530_32/bin/mingw32-make.exe
```

**Comment by zdenop** [comment] 2019-06-07 18:48
Can you please make a clean build (maybe including git cloning).
Because `cannot find -lpvt.cppan.demo.tiff` indicate you run cppan build...

**Comment by Bleach665** [comment] 2019-06-07 18:51
Build was clean and repo cloned from scratch.

**Comment by zdenop** [comment] 2019-06-07 19:10
than please provide full log from configuration.

**Comment by Bleach665** [comment] 2019-06-07 19:12
```
Configuring tesseract version 5.0.0-alpha-152-g17c8a...
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
Could NOT find LibArchive (missing: LibArchive_LIBRARY LibArchive_INCLUDE_DIR) 
No support for auto-detection of the target instruction set/extension

General configuration for Tesseract 5.0.0-alpha-152-g17c8a
--------------------------------------------------------
Build type: 
Compiler: Clang
Used standard: C++17
CXX compiler options:  -isystem E:/Lib_prebuild/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  
Linker options: -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot E:/Lib_prebuild/android-ndk-r16b/platforms/android-14/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc  
Install directory: O:/21/tesseract_arm_inst
Architecture flags: 
Vector unit list: 
AVX_OPT: OFF
AVX2_OPT: OFF
SSE41_OPT: OFF
MARCH_NATIVE_OPT: OFF
sim_flags: 

Build with cppan [CPPAN_BUILD]: OFF
Build with openmp support [OPENMP_BUILD]: OFF
Disable disable graphics (ScrollView) [GRAPHICS_DISABLED]: OFF
Enable embedded build [EMBEDDED]: OFF
Disable the legacy OCR engine [DISABLED_LEGACY_ENGINE]: OFF
Build training tools [BUILD_TRAINING_TOOLS]: OFF
Build tests [BUILD_TESTS]: OFF
--------------------------------------------------------

Configuring done
Generating done
```

**Comment by zdenop** [comment] 2019-06-09 19:23
1. I downloaded the latest ndk (r20) and it provide make tool \android-ndk-r20\prebuilt\windows-x86_64\bin\make.exe ), so there is not need to use Qt mingw make file. IMO it is better to use tools from one source instead of multiple sources/providers.
2. Your output is reconfigure output from cmake-gui!  Full/clean configure seems like this:
```
ANDROID_PLATFORM not set. Defaulting to minimum supported version
16.
Check for working C compiler: F:/0Android/android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
Check for working C compiler: F:/0Android/android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: F:/0Android/android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
Check for working CXX compiler: F:/0Android/android-ndk-r20/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
```
And I guess problem is that you first (clean) run is started as cppan build and then you try to reconfigure at non cppan build, but is does not work (cmake uses cached results during reconfiguration!)
So you either remove` .cppan` dir (and probably cppan tool from path) or you correcting initialize cmake variables **before running initial cmake configuration**:

![image](https://user-images.githubusercontent.com/574156/59163122-b4ba2300-8afc-11e9-99e3-61d60a10ae5a.png)
