### ISSUE TITLE
tesseract 4 android build issue

### ISSUE THREAD

**Issue by romaderi** [tesseract-ocr/tesseract#875] opened 2017-05-04 10:49 UTC
Hi I have juste replaced the jni\com_googlecode_tesseract_android\src in the tess two project with 4.0 tesseract src and try to compile it with ndkbuild. I'm facing an issue with the following error ...
[armeabi] Install        : libjpgt.so => libs/armeabi/libjpgt.so
[armeabi] Install        : liblept.so => libs/armeabi/liblept.so
[armeabi] Install        : libpngt.so => libs/armeabi/libpngt.so
[armeabi] Compile++ thumb: tess <= lstm.cpp
jni/com_googlecode_tesseract_android/src/lstm/lstm.cpp:85:64: error: use of
      undeclared identifier 'log2'
    nf_ = type_ == NT_LSTM_SOFTMAX ? no_ : IntCastRounded(ceil(log2(no_)));
                                                               ^
jni/com_googlecode_tesseract_android/src/lstm/lstm.cpp:183:31: error: use of
      undeclared identifier 'log2'
    nf_ = IntCastRounded(ceil(log2(no_)));
                              ^
2 errors generated.
make: *** [obj/local/armeabi/objs/tess/src/lstm/lstm.o] Error 1

Any idea ?

**Comment by stweil** [comment] 2017-05-04 15:08
It looks like `log2` is not provided by Android. See [this discussion](http://stackoverflow.com/questions/11080118/does-android-support-log2) which also includes valid solutions.

Tesseract already uses its own `log2` for Android in [`wordrec/language_model.cpp`](https://github.com/tesseract-ocr/tesseract/blob/master/wordrec/language_model.cpp#L34).

**Comment by raulcorreia1** [comment] 2017-08-26 17:20
Hi romaderi, I am also trying to build tesseract 4 using the base of tess-two, to prevent the log2 issue I think you need to add the code below before the namespace in lstm.cpp and weightmatrix.cpp:
```
#if (defined(_MSC_VER) && _MSC_VER < 1900) || defined(ANDROID)
double log2(double n) {
  return log(n) / log(2.0);
}
#endif  // _MSC_VER
```
Now after doing that I found some other errors:

Error:error: assigning to 'PROGRESS_FUNC' (aka 'bool (*)(int, int, int, int, int)') from incompatible type 'bool (void *, int, int, int, int, int)': different number of parameters (5 vs 6)

Not sure how to solve this one...

**Comment by avestnik** [comment] 2018-02-14 19:47
hi! I faced the same problem, was able to fix it inserting log2() implementation into lstm.cpp and weightmatrix.cpp. I guess it would be nice if source code maintainers fix it in upstream

**Comment by Shreeshrii** [comment] 2018-02-28 07:16
@stweil

Can this be fixed in the repo?

Related issue posted in the forum

https://groups.google.com/d/msgid/tesseract-ocr/bdf690c6-7979-4ed6-a62d-f8b67853c6c0%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by stweil** [comment] 2018-02-28 08:09
Sure. The easy solution would use the code shown above, but I want to replace the log function by faster pure integer calculations here (which needs a little bit more time to implement it).

**Comment by Shreeshrii** [comment] 2018-02-28 08:50
@stweil Would it make sense to implement the easy solution now and revert it when you replace the log function later?

**Comment by amitdo** [comment] 2018-02-28 08:54
Related: https://github.com/android-ndk/ndk/issues/82

**Comment by stweil** [comment] 2018-03-01 21:59
The issue is addressed by pull request #1353.

**Comment by rezaee** [comment] 2018-03-14 04:28
Hi there,
May you tell me where can I get the tesseract-4 source and which folder exactly should replace with which one?
I am newbie and want to use tesseract-4 on my Android applications!

**Comment by amitdo** [comment] 2018-08-31 13:17
Android have log2() now.
https://developer.android.com/ndk/guides/cpp-support#libc

**Comment by stweil** [comment] 2018-09-09 06:46
That's good. And the Tesseract code has code which supports older installations without `log2` since some time. @romaderi,  could you please close this issue, or do you think there is still a problem?

**Closed** 2018-09-28 10:59 UTC

**Comment by amitdo** [comment] 2021-01-14 22:43
I think the log2() for android is obsolete.

The older NDKs that needed that custom code are not supported anymore by Google. AFAIK, new NDKs can be used to build apps for old android releleases.
