### ISSUE TITLE
Need a free call to match  GetUTF8Text();

### ISSUE THREAD

**Issue by LeifUK** [tesseract-ocr/tesseract#1030] opened 2017-07-11 08:05 UTC
### Environment

Tessearct 4.00.00alpha
Windows 10 64 bit Visual Studio 2013 Win32 build. 

This issue is also present in earlier versions of Tesseract including 3.0.4 (which I fixed for our own use). 

### Current Behavior:

The GetUTF8Text() method (and other similar methods) allocates a buffer, but there is no call to free the memory, and it cannot be freed by the caller without heap corruption. 

### Suggested Fix:

Add a method called FreeXXText() (or whatever name is preferred) which does no more than free the memory along these lines: 

void TessBaseAPI::FreeXXText(char *text)
{
	delete[] text;
}

Deleting a null pointer is not a problem (on Windows anyway).

**Comment by amitdo** [comment] 2017-07-11 12:09
https://github.com/tesseract-ocr/tesseract/blob/10779bd9e50d/api/baseapi.cpp#L1273

I assume it is a Windows only issue similar to https://github.com/tesseract-ocr/tesseract/issues/1029#issuecomment-314152843, right?

**Comment by vidiecan** [comment] 2017-07-11 12:50
This happens when you do **not** use CRT dynamic link and the heaps get confused. In projects using many dependencies, this can get tricky because all the dependencies should use the same (unless you really know what you are doing).

See https://msdn.microsoft.com/en-us/library/abx4dbyh(v=vs.80).aspx but also 
https://stackoverflow.com/questions/10820114/do-statically-linked-dlls-use-a-different-heap-than-the-main-program

In vsprops (or directly in GUI) you should use something like
```
    <ClCompile>
      <RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>
    </ClCompile>
```

**Comment by amitdo** [comment] 2017-07-11 13:21
Another link:
https://msdn.microsoft.com/en-us/library/ms235460.aspx

**Comment by LeifUK** [comment] 2017-07-11 13:51
That's right, the app and DLL have their own heaps.

**Comment by egorpugin** [comment] 2017-07-11 16:30
+1
Never like this allocated `char *` value.
It's better to return `std::string`.

**Comment by amitdo** [comment] 2017-07-11 16:44
You mean `STRING`? :-)

That's what Tesseract uses in the API.

**Comment by stweil** [comment] 2017-07-16 09:31
I'm afraid that you will get an endless list of problems as long as your program uses more than one C runtime library on Windows. With only a single runtime library, all those problems should be solved.

It is possible to force the MS linker to always use the same msvcrt(d).dll.

You could also consider building Leptonica and Tesseract with Mingw-w64. With that combination I never had such problems.

**Comment by LeifUK** [comment] 2017-07-21 07:09
I only use one C runtime library, multithreaded DLL for release builds and multithreaded debug DLL for debug builds.

**Comment by LeifUK** [comment] 2017-07-21 07:10
"It's better to return std::string"

Surely that has the same issue if it is allocated in the library, but freed in the application.

**Comment by amitdo** [comment] 2017-07-21 07:57
https://msdn.microsoft.com/en-us/library/ms235460.aspx

>The DLL and .exe file are built with /MD, so they share a single copy of the CRT.
>
>If you rebuild with /MT so that they use separate copies of the CRT, running the resulting test1Main.exe results in an access violation.

How do you build the dll and exe?

**Comment by stweil** [comment] 2017-07-21 08:07
> I only use one C runtime library

Nevertheless your program uses more than one C runtime library if it crashes. Use the [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) to see which DLLs are used at runtime. For command line programs which run very short, you'll have to add a `sleep` in the `main()` function to delay the execution.

**Comment by amitdo** [comment] 2017-07-21 09:10
I believe the same issue will occur in linux with static linking to glibc/libstdc++.

**Comment by amitdo** [comment] 2017-07-21 09:12
... but that's not common on linux.

**Comment by LeifUK** [comment] 2017-07-21 11:58
dumpbin provides an alternative way to see the linkage of statically linked DLLs. For example:  

**dumpbin /IMPORTS libtesseract304.dll**

All my components use msvcr120.dll.

**Comment by amitdo** [comment] 2018-09-20 09:03
@stweil, should we close this issue?

What about #1201?

**Comment by zdenop** [comment] 2018-09-28 11:49
I am closing this as correct setting of VS/compiler should solve the issue.

**Closed by zdenop** 2018-09-28 11:49 UTC

**Comment by davetclark** [comment] 2019-02-19 18:37
Hi,

With respect, there's no such thing as the "correct setting" of VS/compiler. Compiling against the dynamic runtime does solve the issue but using a static runtime is a valid usecase, even if it's not your preferred method, and it's not something that can be changed in some cases. There are tradeoffs for both methods.

This really should be fixed in the Tesseract interface, it's not usable for certain applications due to this bug. Being a library it's not up to Tesseract to decide which runtime the client should use.

**Comment by stweil** [comment] 2019-02-20 08:18
A static runtime should work, too – as long as it is also used by the Tesseract code. The simple rule is to use only a single C runtime library. With more than one, not only memory allocation / deallocation will cause problems, but also mechanisms like `atexit` calls will break.

**Comment by davetclark** [comment] 2019-02-21 15:24
If the -exact- same static C runtime is built into both the Tesseract DLL and the client, it -should- work. That would be brittle and tough to maintain. You couldn't mix a debug and release build during development for example. Either way, Microsoft says not to do this.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=vs-2017
"However, even when the CRT code is identical, you can't hand off memory allocated in one heap to a component that uses a different heap."

The correct practice in Windows world, unfortunately, is to provide a Free function. That's why every single Win32 API that allocates memory provides a Free function (not counting GlobalAlloc or something like that).  It's just part of supporting Windows builds.

**Comment by M1chae1** [comment] 2019-10-23 03:22
I think the C++ implement is missing this free API because C interface contains it
void  TESS_CALL TessDeleteText(char* text);
https://github.com/tesseract-ocr/tesseract/blob/10779bd9e50de527c4eb8b49cbd04618ed67367f/api/capi.h#L111

**Comment by stweil** [comment] 2019-10-23 04:54
In C++ you can just use `delete [] text`, so there is no need for a special API.

On MS Windows the situation is a bit complicated (see discussion above) and you must take care that all of your code uses the same C runtime library.

**Comment by M1chae1** [comment] 2019-10-23 05:47
I understand. 

However, it is unreasonable to assume the CRT of different dependent libraries in a large project to be the same because some of them may be developed by another parties or without source code. (especially using VSC++ and Windows as development platform)

I suggest it returns STRING* as what ProcessPage does to avoid this problem.

**Comment by stweil** [comment] 2019-10-23 06:14
`STRING` is a proprietary data type. I'd like to replace such types by standard types where possible, in this case by `std::string`.

And I really don't want to waste my time with bad system designs from Microsoft. Mixing different CRTs causes much more problems than just unmatched new / delete. File I/O (stdin, stdout, stderr) and `atexit` are just two more examples of such problems. The Tesseract part should work as long as the code which uses the Tesseract API uses the same CRT, so you can use third party DLLs with a different CRT as long as those DLLs don't use Tesseract.

**Comment by essamzaky** [comment] 2019-11-01 18:24
@stweil  , I read the discussion and the problem is very common in windows , i need to use tesseract and i have some 3rd parties are closed source , how to merge them in my application , the application crash if i used delete [] , adding function inside tesseract to free what tesseract allocated is required .
now i use tess.Clear(); as a work arround is that correct
suppose i have 100 images to be recognized is the following code correct denario

for (int i = 0; i < 100; i++) {
	auto pixs = pixRead(argv[1]);	
	tess.SetImage(pixs);
	tess.Recognize(0);
	char* outText = tess.GetUTF8Text();	
	std::cout << outText;
	// cleanup
	// delete[] outText;//this sould be done from tesseract from dll to avoid  runtime conflects
	pixDestroy(&pixs);
	tess.Clear();
}

**Comment by tomatniy** [comment] 2020-02-19 02:05
Is this only me who have same CRTs for tesseract and exe and still having crashes? In my case for Release build only.
