### ISSUE TITLE
Quality of OCR - Example 

### ISSUE THREAD

**Issue by KKHAN1991** [tesseract-ocr/tesseract#1931] opened 2018-09-25 18:03 UTC
I am trying to extract data from a driving license or passport.

I have an example here. https://jsfiddle.net/8aL31upr/105 and i am using the following image https://www.eufakes.com/products/uk-unionflag.jpg. 

I think the quality of the image is quite good however the result is not good.

> nmvms Luczucz I. $23133 1:“;73"*W m a a 1' “tyiﬁmwmmn Vii—x! ) w! Mk

What can i do to improve this?

### Environment

* **Tesseract Version**: 1

### Current Behavior:

OCR not working as expected

### Expected Behavior:

For it to extract text.

### Suggested Fix:

-

**Comment by CanadianHusky** [comment] 2018-09-26 14:20
Respectfully, I dont think the problem is the quality of the OCR Engine, but the quality of your image and how you use the OCR Engine.

with your Image as is, my OCR Result is 

![image](https://user-images.githubusercontent.com/35332003/46084765-1758d200-c1ad-11e8-872a-32cb57625840.png)

maybe not perfect but definatly not the garbage output you are getting,

with your image enlarged by 200% the result is over 95% accurate already

![image](https://user-images.githubusercontent.com/35332003/46084843-48390700-c1ad-11e8-84c7-f148c0e63a9e.png)

with your image at 300% the result is 

![image](https://user-images.githubusercontent.com/35332003/46085050-c9909980-c1ad-11e8-9f00-2681075cb34a.png)

there are still some minor mistakes but considering there is no other effort other than resizing the image, my test is intended to prove that the problem is the image you feed into the OCR Engine.

To answer your question how you should improve the result;
- check your OCR Version code. I have no idea what version 1 is.
- resize the image to a suitable size that works better with the OCR Engine (trial error)
- apply image cleanup logic, convert to monochrome with bitonal threshold or convert to grayscale which will get rid of that nasty background
- change brightness and contrast to get rid of that background

+40% Brightness and +100% contrast and convert to grayscale with suitable threshold change do this to your image

![image](https://user-images.githubusercontent.com/35332003/46086001-efb73900-c1af-11e8-9326-1061984908cc.png)

![image](https://user-images.githubusercontent.com/35332003/46085309-65220a00-c1ae-11e8-8fdf-7e872c8f245e.png)

all of the transformations I did can be done with code, but you need to know what the optimum values are which can be found out by testing a range of images and trial/error

Final comment : Preparing image for OCR detection is more of an ART, rather than Science in my opinion. There are endless possibilities to prepare the image for OCR and it is not easy for novice users.

Regards

**Comment by amitdo** [comment] 2018-09-26 14:30
@zdenop, please close this issue.

**Closed** 2018-09-26 16:52 UTC

**Comment by ttbuffey** [comment] 2021-07-08 09:36
@CanadianHusky 

could you please  help to share the apis and parameters you used for the image preprocessing. I tried the methods(resize, grascale etc) you mentioned, but didn't get the same result,

Could you please help to point out if i used the wrong one or missed any, or used the wrong parameters
 image = np.array(image)
 image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
 image = cv2.resize(image, None, fx=2, fy=2, interpolation=cv2.INTER_CUBIC)
 image = cv2.adaptiveThreshold(image, 255, cv2.ADAPTIVE_THRESH_MEAN_C,
                                  cv2.THRESH_BINARY, 15, 30)
 image = cv2.addWeighted(image, 1, image, 0.5, 0)
