### ISSUE TITLE
Can't Install Latest Head With Brew

### ISSUE THREAD

**Issue by jsl303** [tesseract-ocr/tesseract#864] opened 2017-05-02 14:42 UTC
I was able to install head with brew before, but now I get this error. :(
Could someone help?
Thanks!
$ brew install tesseract --HEAD
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Using the sandbox
==> Cloning https://github.com/tesseract-ocr/tesseract.git
Cloning into '/Users/user/Library/Caches/Homebrew/tesseract--git'...
remote: Counting objects: 724, done.
remote: Compressing objects: 100% (694/694), done.
remote: Total 724 (delta 88), reused 163 (delta 12), pack-reused 0
Receiving objects: 100% (724/724), 3.74 MiB | 0 bytes/s, done.
Resolving deltas: 100% (88/88), done.
Checking connectivity... done.
==> Checking out branch master
==> Downloading https://github.com/tesseract-ocr/tesseract/commit/b18cad4.patch
######################################################################## 100.0%
==> Patching
==> Applying b18cad4.patch
patching file configure.ac
Hunk #1 FAILED at 220.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
patching file api/Makefile.am
Hunk #1 FAILED at 45.
1 out of 1 hunk FAILED -- saving rejects to file api/Makefile.am.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/tesseract--patch-20170502-16295-cpuv7w/b18cad4.patch

**Comment by Shreeshrii** [comment] 2017-05-02 14:57
Try without the patch. Maybe that change has already been applied.

**Comment by jsl303** [comment] 2017-05-02 15:34
Thanks, do you know how to tell brew to skip the patch?

**Comment by amitdo** [comment] 2017-05-02 15:36
The brew formulae is for version 3.05, while the HEAD is 4.00 (alpha).

**Comment by jsl303** [comment] 2017-05-02 15:39
Thanks, wouldn't adding --head option like "brew install tesseract 
--HEAD" download the latest head from the Github?
I'm wondering how to tell brew to skip the patch...

**Comment by amitdo** [comment] 2017-05-02 16:05
Dunno. I don't have a a Mac...

**Comment by Shreeshrii** [comment] 2017-05-04 17:02
see https://github.com/Homebrew/homebrew-core/blob/master/Formula/tesseract.rb

**Comment by stweil** [comment] 2017-05-04 20:07
@zdenop, maybe a new release 3.05.01 would help making such patches unnecessary.

**Comment by amitm02** [comment] 2017-05-12 14:53
same here

**Comment by atuyosi** [comment] 2017-05-16 12:37
@jsl303,

As you might already know, Homebrew's Formula can edit locally.

```
$ brew edit tesseract
```

If you want to skip the patch, comment out line 71-74, and save it.

( /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tesseract.rb )

```
$ brew install tesseract --HEAD
```

or, wrapping patch block with 'if-end' block such like below.

```
--- a/Formula/tesseract.rb
+++ b/Formula/tesseract.rb
@@ -68,10 +68,12 @@ class Tesseract < Formula
   # remove on next release, > 3.05.00
   # upstream fix for building with OpenCL enabled
   # https://github.com/tesseract-ocr/tesseract/pull/814
+  if !build.head?
   patch do
     url "https://github.com/tesseract-ocr/tesseract/commit/b18cad4.patch"
     sha256 "10c59baa54c3406fcd03f36cd0f1e3cc2ba150f082d14f919274a541b3cff7b2"
   end
+  end

   def install
     if build.head?
```

**Comment by atuyosi** [comment] 2017-05-17 03:20
My PR got merged. So, no need to edit Formula.

@jsl303, It should work with the following command.

```
$ brew update
$ brew install tesseract --HEAD
```

**Comment by stweil** [comment] 2017-05-17 05:09
This issue can be closed. `brew install tesseract --HEAD` now works.

**Closed** 2017-05-17 17:51 UTC

**Comment by Shreeshrii** [comment] 2017-07-31 08:13
@stweil Please see the recent post at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/H9JmIRU2dQk/oMtSIvtHAwAJ regarding problem with install of training tools on mac os. Thanks!

**Comment by stweil** [comment] 2017-07-31 19:45
> Please see the recent post ...

I need more information because I currently cannot reproduce the build problem (building training tools works for me with MacPorts and with Homebrew).
