### ISSUE TITLE
core dumped with Too few characters

### ISSUE THREAD

**Issue by RobinFrcd** [tesseract-ocr/tesseract#3863] opened 2022-07-07 17:27 UTC
### Environment

**Tesseract Version**:
```
tesseract 5.1.0
 leptonica-1.79.0
  libgif 5.1.9 : libjpeg 6b (libjpeg-turbo 2.0.6) : libpng 1.6.37 : libtiff 4.2.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.4.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.4.3 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.4.8
 Found libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
```

**Platform**: 
Docker container with `PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"` running on `Linux fae9a7697442 4.14.281-212.502.amzn2.x86_64 #1 SMP Thu May 26 09:52:17 UTC 2022 x86_64 GNU/Linux`

### Current Behavior:
If I run `tesseract test.jpg /tmp/tess_86qu567o --psm 12 txt` on ![test](https://user-images.githubusercontent.com/29704178/177833532-20973269-bb6d-4ce4-862b-fa33480598af.jpg) tesseract crashes with

```
Estimating resolution as 2131
Too few characters. Skipping this page
OSD: Weak margin (0.00) for 0 blob text block, but using orientation anyway: 0
Floating point exception (core dumped)
```

### Expected Behavior:
Shouldn't crash.

However, if run the same command with the same version of tesseract but on Ubuntu or MacOS, it doesn't crash.

______

Here's the Dockerfile to reproduce the issue:

```
# syntax=docker/dockerfile:experimental
FROM python:3.9-slim-bullseye

# https://notesalexp.org/tesseract-ocr/
RUN apt-get update && \
    apt-get install -y gnupg wget && \
    wget -O - https://notesalexp.org/debian/alexp_key.asc | apt-key add - && \
    echo "deb https://notesalexp.org/tesseract-ocr5/bullseye/ bullseye main" | tee /etc/apt/sources.list.d/notesalexp.list > /dev/null && \
    apt-get update && \
    apt-get install -y tesseract-ocr tesseract-ocr-fra  && \
    rm -rf /var/lib/apt/lists/*

RUN wget -O test.jpg https://user-images.githubusercontent.com/29704178/177833532-20973269-bb6d-4ce4-862b-fa33480598af.jpg
RUN tesseract test.jpg /tmp/tmp --psm 12 txt
```

The build should raise:
```
 > [4/4] RUN tesseract test.jpg /tmp/tmp --psm 12 txt:                                                                                       
#9 0.430 Estimating resolution as 2131                                                                                                       
#9 0.430 Too few characters. Skipping this page                                                                                              
#9 0.430 OSD: Weak margin (0.00) for 0 blob text block, but using orientation anyway: 0                                                      
#9 0.482 Floating point exception (core dumped)
```

**Comment by stweil** [comment] 2022-07-07 17:48
This looks like a duplicate of this report: #3859.

**Comment by RobinFrcd** [comment] 2022-07-07 17:52
So the fix would be to rebuild leptonica from source ?

**Closed** 2022-07-07 17:56 UTC
Labels: duplicate
