### ISSUE TITLE
Error in Training Tesseract LSTM 4.0

### ISSUE THREAD

**Issue by am0awad** [tesseract-ocr/tesseract#819] opened 2017-04-12 05:52 UTC
Hello All,

I want to train tesseract as [](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00---Finetune), But I got this error, Any help
```
 tesstrain.sh --fonts_dir /usr/share/fonts --lang ara  --training_text ../../tesserac-ocr/langdata/ara.training_text   --langdata_dir ../langdata --tessdata_dir ./tessdata   --fontlist "Arial"   --output_dir ~/tesstutorial/aratest
=== Starting training for language 'ara'
[ر أبر 12 07:48:58 EET 2017] /usr/bin/text2image --fonts_dir=/usr/share/fonts --font=Arial --outputbase=/tmp/font_tmp.Rj3QkZFztb/sample_text.txt --text=/tmp/font_tmp.Rj3QkZFztb/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.Rj3QkZFztb
Rendered page 0 to file /tmp/font_tmp.Rj3QkZFztb/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using Arial
[ر أبر 12 07:49:17 EET 2017] /usr/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.Rj3QkZFztb --fonts_dir=/usr/share/fonts --strip_unrenderable_words --fontconfig_refresh_config_file=false --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.XBcy4TVQwb/ara/ara.Arial.exp0 --font=Arial --text=../../tesserac-ocr/langdata/ara.training_text
ERROR: Non-existent flag --fontconfig_refresh_config_file=false
ERROR: /tmp/tmp.XBcy4TVQwb/ara/ara.Arial.exp0.box does not exist or is not readable
ERROR: /tmp/tmp.XBcy4TVQwb/ara/ara.Arial.exp0.box does not exist or is not readable
```

**Comment by Shreeshrii** [comment] 2017-04-12 08:10
--training_text ../../tesserac-ocr/langdata/ara.training_text 

is there a typo in your folder name tesserac instead of tesseract?

**Comment by Shreeshrii** [comment] 2017-04-12 09:29
```
$ training/tesstrain.sh  \
   --fonts_dir /usr/share/fonts/ \
  --lang ara   \
  --linedata_only \
  --noextract_font_properties \
  --exposures "0"    \
  --langdata_dir ../langdata \
  --tessdata_dir ../tessdata  \
  --output_dir ~/tesstutorial/ara  \
  --fontlist "Arial"

=== Starting training for language 'ara'
[Wed Apr 12 14:55:47 DST 2017] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts/ --font=Arial --outputbase=/tmp/font_tmp.OIUrMxATnl/sample_text.txt --text=/tmp/f
ont_tmp.OIUrMxATnl/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.OIUrMxATnl
Rendered page 0 to file /tmp/font_tmp.OIUrMxATnl/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using Arial
[Wed Apr 12 14:56:35 DST 2017] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.OIUrMxATnl --fonts_dir=/usr/share/fonts/ --strip_unrenderable_words --leadin
g=32 --xsize=2550 --ptsize=16 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0 --font=Arial --text=../langdata/ara/ara.training_text
0
Rendered page 0 to file /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0.tif
/tmp/tmp.xPjs35P5oP/ara/gt/ara.Arial.exp0.txt

=== Phase UP: Generating unicharset and unichar properties files ===
[Wed Apr 12 14:56:38 DST 2017] /usr/local/bin/unicharset_extractor -D /tmp/tmp.xPjs35P5oP/ara/ /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0.box
Extracting unicharset from /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0.box
Wrote unicharset file /tmp/tmp.xPjs35P5oP/ara//unicharset.
[Wed Apr 12 14:56:39 DST 2017] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.xPjs35P5oP/ara/ara.unicharset -O /tmp/tmp.xPjs35P5oP/ara/ara.unicharset -X /tmp/tmp
.xPjs35P5oP/ara/ara.xheights --script_dir=../langdata
Loaded unicharset of size 187 from file /tmp/tmp.xPjs35P5oP/ara/ara.unicharset
Setting unichar properties
Writing unicharset to file /tmp/tmp.xPjs35P5oP/ara/ara.unicharset

=== Phase D: Generating Dawg files ===
Generating word Dawg
[Wed Apr 12 14:56:41 DST 2017] /usr/local/bin/wordlist2dawg -r 1 ../langdata/ara/ara.wordlist /tmp/tmp.xPjs35P5oP/ara/ara.word-dawg /tmp/tmp.xPjs35P5oP/ara/ara.unichar
set
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.xPjs35P5oP/ara/ara.unicharset'
Reading word list from '../langdata/ara/ara.wordlist'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.xPjs35P5oP/ara/ara.word-dawg'
Generating frequent-word Dawg
[Wed Apr 12 14:56:46 DST 2017] /usr/local/bin/wordlist2dawg -r 1 /tmp/tmp.xPjs35P5oP/ara/ara.wordlist.clean.freq /tmp/tmp.xPjs35P5oP/ara/ara.freq-dawg /tmp/tmp.xPjs35P
5oP/ara/ara.unicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.xPjs35P5oP/ara/ara.unicharset'
Reading word list from '/tmp/tmp.xPjs35P5oP/ara/ara.wordlist.clean.freq'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.xPjs35P5oP/ara/ara.freq-dawg'
[Wed Apr 12 14:56:47 DST 2017] /usr/local/bin/wordlist2dawg -r 2 ../langdata/ara/ara.punc /tmp/tmp.xPjs35P5oP/ara/ara.punc-dawg /tmp/tmp.xPjs35P5oP/ara/ara.unicharset
Set reverse_policy to RRP_FORCE_REVERSE
Loading unicharset from '/tmp/tmp.xPjs35P5oP/ara/ara.unicharset'
Reading word list from '../langdata/ara/ara.punc'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.xPjs35P5oP/ara/ara.punc-dawg'
[Wed Apr 12 14:56:47 DST 2017] /usr/local/bin/wordlist2dawg -r 0 ../langdata/ara/ara.numbers /tmp/tmp.xPjs35P5oP/ara/ara.number-dawg /tmp/tmp.xPjs35P5oP/ara/ara.unicha
rset
Set reverse_policy to RRP_DO_NO_REVERSE
Loading unicharset from '/tmp/tmp.xPjs35P5oP/ara/ara.unicharset'
Reading word list from '../langdata/ara/ara.numbers'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.xPjs35P5oP/ara/ara.number-dawg'
[Wed Apr 12 14:56:47 DST 2017] /usr/local/bin/wordlist2dawg -r 1 ../langdata/ara/ara.word.bigrams /tmp/tmp.xPjs35P5oP/ara/ara.bigram-dawg /tmp/tmp.xPjs35P5oP/ara/ara.u
nicharset
Set reverse_policy to RRP_REVERSE_IF_HAS_RTL
Loading unicharset from '/tmp/tmp.xPjs35P5oP/ara/ara.unicharset'
Reading word list from '../langdata/ara/ara.word.bigrams'
Reducing Trie to SquishedDawg
Writing squished DAWG to '/tmp/tmp.xPjs35P5oP/ara/ara.bigram-dawg'

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=../tessdata
[Wed Apr 12 14:57:00 DST 2017] /usr/local/bin/tesseract /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0.tif /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0 lstm.train ../langdata/ara/ar
a.config
Tesseract Open Source OCR Engine v4.00.00alpha-361-g1477e17 with Leptonica
Page 1

=== Constructing LSTM training data ===
Creating new directory /home/shree/tesstutorial/ara
Copying ../langdata/ara/ara.config to /home/shree/tesstutorial/ara
Moving /tmp/tmp.xPjs35P5oP/ara/ara.unicharset to /home/shree/tesstutorial/ara
Moving /tmp/tmp.xPjs35P5oP/ara/ara.number-dawg to /home/shree/tesstutorial/ara/ara.lstm-number-dawg
Moving /tmp/tmp.xPjs35P5oP/ara/ara.punc-dawg to /home/shree/tesstutorial/ara/ara.lstm-punc-dawg
Moving /tmp/tmp.xPjs35P5oP/ara/ara.word-dawg to /home/shree/tesstutorial/ara/ara.lstm-word-dawg
Moving /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0.box to /home/shree/tesstutorial/ara
Moving /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0.tif to /home/shree/tesstutorial/ara
Moving /tmp/tmp.xPjs35P5oP/ara/ara.Arial.exp0.lstmf to /home/shree/tesstutorial/ara
Moving /tmp/tmp.xPjs35P5oP/ara/gt/ara.Arial.exp0.txt to /home/shree/tesstutorial/ara

Completed training for language 'ara'

shree@ALL-IN-1-TOUCH:/mnt/c/Users/User/shree/tesseract-ocr$
```

**Comment by am0awad** [comment] 2017-04-12 09:32
@Shreeshrii Thanks a lot, one more question please to get full understanding of it` --langdata_dir` parameter is the directory of [](https://github.com/tesseract-ocr/langdata/tree/master/ara)
again thanks for replying!

**Comment by Shreeshrii** [comment] 2017-04-12 09:33
Put Arabic langdata files under ara folder in langdata - similar to 
https://github.com/tesseract-ocr/langdata

so that you have

./langdata
./langdata/ara
./tessdata
./tesseract
./tesseract/tessdata
./tesseract/training

etc

**Comment by am0awad** [comment] 2017-04-12 09:34
I got it, Thanks @Shreeshrii

**Comment by amitdo** [comment] 2017-04-12 09:39
Shree, please redirect people that ask questions about the training process to the forum.

Thanks!

**Comment by yoyoshuang** [comment] 2017-08-03 07:36
Hello,@Shreeshrii 
I have the same problem like @am0awad . 

` training/tesstrain.sh  \
>    --fonts_dir /Library/Fonts \
>   --lang chi_sim   \
>   --linedata_only \
>   --noextract_font_properties \
>   --exposures "0"    \
>   --langdata_dir ./langdata \
>   --tessdata_dir ./tessdata  \
>   --output_dir ./tesstutorial/chi_sim `

I have already download the [https://github.com/tesseract-ocr/langdata](url) to my folder, and I have all the folders:

./langdata
./langdata/chi_sim 
./tessdata
 
but I still got this:
`=== Starting training for language 'chi_sim'
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
training/tesstrain_utils.sh: line 189: /sample_text.txt: Permission denied
[2017年 8月 3日 星期四 15时23分24秒 CST] /usr/local/bin/text2image --fonts_dir=/Library/Fonts --font=AR PL UKai CN Light --outputbase=/sample_text.txt --text=/sample_text.txt --fontconfig_tmpdir=

=== Phase I: Generating training images ===
Rendering using Arial Unicode MS
Rendering using AR PL UKai CN Light
[2017年 8月 3日 星期四 15时23分25秒 CST] /usr/local/bin/text2image --fontconfig_tmpdir= --fonts_dir=/Library/Fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/var/folders/br/xq_2dfh91y1gdd90lny2501w0000gn/T/tmp.NTXG7RhZ/chi_sim/chi_sim.AR_PL_UKai_CN_Light.exp0 --font=AR PL UKai CN Light --text=./langdata/chi_sim/chi_sim.training_text
[2017年 8月 3日 星期四 15时23分25秒 CST] /usr/local/bin/text2image --fontconfig_tmpdir= --fonts_dir=/Library/Fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/var/folders/br/xq_2dfh91y1gdd90lny2501w0000gn/T/tmp.NTXG7RhZ/chi_sim/chi_sim.Arial_Unicode_MS.exp0 --font=Arial Unicode MS --text=./langdata/chi_sim/chi_sim.training_text
ERROR: /var/folders/br/xq_2dfh91y1gdd90lny2501w0000gn/T/tmp.NTXG7RhZ/chi_sim/chi_sim.Arial_Unicode_MS.exp0.box does not exist or is not readable
ERROR: /var/folders/br/xq_2dfh91y1gdd90lny2501w0000gn/T/tmp.NTXG7RhZ/chi_sim/chi_sim.AR_PL_UKai_CN_Light.exp0.box does not exist or is not readable
ERROR: /var/folders/br/xq_2dfh91y1gdd90lny2501w0000gn/T/tmp.NTXG7RhZ/chi_sim/chi_sim.AR_PL_UKai_CN_Light.exp0.box does not exist or is not readable`

would anyone like to help me?

Thank you very much!

**Comment by Shreeshrii** [comment] 2017-08-03 09:22
​​
Ray has updated the LSTM training process.

Please install the latest code from github.

Please read the wiki again for the new instructions and try.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by yoyoshuang** [comment] 2017-08-14 08:23
Thank you @Shreeshrii I solved my problem by your help! Thank you very much!

**Comment by amitdo** [comment] 2017-08-17 19:41
@zdenop, please close this issue.

**Closed** 2017-08-17 20:37 UTC

**Comment by hanikh** [comment] 2017-10-17 12:29
@Shreeshrii at Phase I,  I got this error:
Rendered page 2 to file /tmp/tmp.GZVqm2mm3D/fas/fas.Times_New_Roman.exp0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!
 but the process did not stop. and it got this error:
ERROR: /tmp/tmp.GZVqm2mm3D/fas/fas.Times_New_Roman.exp0.lstmf does not exist or is not readable
probably, the problem is in the very first phase. would you please help me solve it?

**Comment by Shreeshrii** [comment] 2017-10-17 13:58
Look at the tif file in question in tmp folder. Looks like first line has
nulls in it.

**Comment by hanikh** [comment] 2017-10-17 15:27
yes. you're right. in fact, there are just numbers and some marks in tif
file. why is that happening?

**Comment by Shreeshrii** [comment] 2017-10-18 02:25
Does Times New Roman font support Farsi? You should use fonts that have
support for your training_text language.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by hanikh** [comment] 2017-10-18 07:27
Times New Roman is in the list of Persian fonts in
training/language_specific.sh. Doesn’t it mean that the Farsi trained model
is trained for Times New Roman?Or the listed fonts are just recommended?

**Comment by KevinZhuYF** [comment] 2018-01-11 23:06
I also have this problem...and I don't know what is the correct fontlist here....
tesseract-ocr/training/tesstrain.sh 
--fonts_dir /usr/share/fonts 
--lang eng 
--linedata_only 
--noextract_font_properties 
--langdata_dir ./langdata 
--tessdata_dir ./tessdata 
--output_dir ~/tesstutorial/engtrain 
--fontlist "Arial"


=== Starting training for language 'eng'
[Thu Jan 11 17:02:51 CST 2018] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts --font=Arial --outputbase=/tmp/font_tmp.hklbdU1PL0/sample_text.txt --text=/tmp/font_tmp.hklbdU1PL0/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.hklbdU1PL0
Could not find font named Arial.
Pango suggested font FreeMono.
Please correct --font arg.

=== Phase I: Generating training images ===
Rendering using Arial
[Thu Jan 11 17:03:04 CST 2018] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.hklbdU1PL0 --fonts_dir=/usr/share/fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.WslM8FLtqt/eng/eng.Arial.exp0 --max_pages=3 --font=Arial --text=./langdata/eng/eng.training_text
Could not find font named Arial.
Pango suggested font FreeMono.
Please correct --font arg.
ERROR: /tmp/tmp.WslM8FLtqt/eng/eng.Arial.exp0.box does not exist or is not readable
ERROR: /tmp/tmp.WslM8FLtqt/eng/eng.Arial.exp0.box does not exist or is not readable

**Comment by Shreeshrii** [comment] 2018-01-12 04:04
>Pango suggested font FreeMono.

Looks like you do not have Arial font on  /usr/share/fonts

You could try the following command to list fonts that support English and use them.

fc-list :lang=en

**Comment by KevinZhuYF** [comment] 2018-01-12 04:07
cool....I'll try that to see if it works. And I can install whatever font I need as well right?

**Comment by KevinZhuYF** [comment] 2018-01-12 20:55
I got another problem shows here:

=== Starting training for language 'eng'
[Fri Jan 12 14:42:13 CST 2018] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts/truetype/msttcorefonts --font=arial --outputbase=/tmp/font_tmp.nvTPBv5Smx/sample_text.txt --text=/tmp/font_tmp.nvTPBv5Smx/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.nvTPBv5Smx
Rendered page 0 to file /tmp/font_tmp.nvTPBv5Smx/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using arial
[Fri Jan 12 14:42:14 CST 2018] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.nvTPBv5Smx --fonts_dir=/usr/share/fonts/truetype/msttcorefonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0 --max_pages=3 --font=arial --text=./langdata/eng/eng.training_text
Rendered page 0 to file /tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0.tif
Rendered page 1 to file /tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0.tif

=== Phase UP: Generating unicharset and unichar properties files ===
[Fri Jan 12 14:42:15 CST 2018] /usr/local/bin/unicharset_extractor --output_unicharset /tmp/tmp.kbD3GZolxX/eng/eng.unicharset --norm_mode 1 /tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0.box
Extracting unicharset from box file /tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0.box
Other case É of é is not in unicharset
Wrote unicharset file /tmp/tmp.kbD3GZolxX/eng/eng.unicharset
[Fri Jan 12 14:42:15 CST 2018] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.kbD3GZolxX/eng/eng.unicharset -O /tmp/tmp.kbD3GZolxX/eng/eng.unicharset -X /tmp/tmp.kbD3GZolxX/eng/eng.xheights --script_dir=./langdata
Loaded unicharset of size 111 from file /tmp/tmp.kbD3GZolxX/eng/eng.unicharset
Setting unichar properties
Other case É of é is not in unicharset
Setting script properties
Warning: properties incomplete for index 25 = ~
Writing unicharset to file /tmp/tmp.kbD3GZolxX/eng/eng.unicharset

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=./tessdata
[Fri Jan 12 14:42:15 CST 2018] /usr/local/bin/tesseract /tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0.tif /tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0 lstm.train
read_params_file: Can't open lstm.train
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Page 1
Page 2
ERROR: /tmp/tmp.kbD3GZolxX/eng/eng.arial.exp0.lstmf does not exist or is not readable

**Comment by Shreeshrii** [comment] 2018-01-13 01:44
read_params_file: Can't open lstm.train

You need this config file. Check that it is there under your subfolders in
your tessdata directory.

**Comment by KevinZhuYF** [comment] 2018-01-13 03:05
Im sure I have this file...double checked.

**Comment by Shreeshrii** [comment] 2018-01-13 04:15
Is it in

--tessdata_dir ./tessdata

the folder used in your training command?

**Comment by KevinZhuYF** [comment] 2018-01-13 14:37
I have checked that and the file is in....and now the error disappears somehow....and I'm able to finish the whole procedure, but there is a failure there which seems important.:
=== Constructing LSTM training data ===
[Fri Jan 12 15:24:16 CST 2018] /usr/local/bin/combine_lang_model --input_unicharset /tmp/tmp.lvf5eRK7qu/eng/eng.unicharset --script_dir tesseract-ocr/langdata --words tesseract-ocr/langdata/eng/eng.wordlist --numbers tesseract-ocr/langdata/eng/eng.numbers --puncs tesseract-ocr/langdata/eng/eng.punc --output_dir /home/kevin/tesstutorial/engtrain --lang eng
Loaded unicharset of size 111 from file /tmp/tmp.lvf5eRK7qu/eng/eng.unicharset
Setting unichar properties
Other case É of é is not in unicharset
Setting script properties
Config file is optional, continuing...
Failed to read data from: tesseract-ocr/langdata/eng/eng.config
Null char=2
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Reducing Trie to SquishedDawg
Moving /tmp/tmp.lvf5eRK7qu/eng/eng.arial.exp0.lstmf to /home/kevin/tesstutorial/engtrain

Completed training for language 'eng'


Here is says failed to read data from the direction that I entered and the file is missing. So do I need to generate this file by myself or I need to create it?

**Comment by Shreeshrii** [comment] 2018-01-13 14:45
Config file is optional, continuing...
Failed to read data from: tesseract-ocr/langdata/eng/eng.config

It is Optional.

**Comment by KevinZhuYF** [comment] 2018-01-13 14:52
Okay..... So after I created the training data by using tesstrain.sh, I started to use lstmtraining to do Training From Scratch. and the log file keep showing ScrolView: waiting for server...

Does that mean I have to use  ScrollView.jar for it?

**Comment by Shreeshrii** [comment] 2018-01-13 14:55
Don't use debug level 100. 

Use -1. It will show you debug text info for every iteration.

Or use 0. It will show info every 100 iterations.

**Comment by KevinZhuYF** [comment] 2018-01-13 15:03
Cool....Im trying it now

**Comment by KevinZhuYF** [comment] 2018-01-13 15:52
Im able to have the output from the Training From Scratch. So now, if I want to customize the train data, what should I do? I have a tiff file with several pages of training samples, and corresponding box file. However, the box file is in format of old version of tesseract. So for 4.0 lstm training, what do I need to create a train data by myself?

**Comment by Shreeshrii** [comment] 2018-01-13 16:49
Read the training 4.0 wiki page. Try out the fine-tune tutorial.

Training from box-tiff pairs is not supported in 4.00.00alpha. Create
synthetic training data using unicode fonts and training text.

**Comment by KevinZhuYF** [comment] 2018-01-13 17:09
wait... I thought Tesseract 4.0 is still using box-tiff file pair for training? It is written on the wiki page.
[https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#lstmtraining-command-line](url)

**Comment by Shreeshrii** [comment] 2018-01-13 17:58
Yes, it uses synthetic box/tiff pairs generated by text2image. The format
of box files is different from the ones generated by tesseract.

The procedure of training using scanned images and corresponding box files
has not been defined for 4.00alpha.

**Comment by KevinZhuYF** [comment] 2018-01-14 16:23
Im currently working on training chi_sim with a specific font type, and I got an error for make eval data for the 'Impact' font


tesseract-ocr/training/tesstrain.sh --fonts_dir /usr/share/fonts/truetype/msttcorefonts --lang chi_sim --linedata_only --noextract_font_properties --langdata_dir tesseract-ocr/langdata --tessdata_dir tesseract-ocr/tessdata --output_dir ~/tesstutorial/chieval --fontlist "Impact Condensed"

=== Starting training for language 'chi_sim'
[Sun Jan 14 10:19:18 CST 2018] /usr/local/bin/text2image --fonts_dir=/usr/share/fonts/truetype/msttcorefonts --font=Impact Condensed --outputbase=/tmp/font_tmp.RaRKXKggCB/sample_text.txt --text=/tmp/font_tmp.RaRKXKggCB/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.RaRKXKggCB
Rendered page 0 to file /tmp/font_tmp.RaRKXKggCB/sample_text.txt.tif

=== Phase I: Generating training images ===
Rendering using Impact Condensed
[Sun Jan 14 10:19:18 CST 2018] /usr/local/bin/text2image --fontconfig_tmpdir=/tmp/font_tmp.RaRKXKggCB --fonts_dir=/usr/share/fonts/truetype/msttcorefonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0 --max_pages=3 --font=Impact Condensed --text=tesseract-ocr/langdata/chi_sim/chi_sim.training_text
Stripped 250 unrenderable words
Rendered page 0 to file /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.tif
Stripped 270 unrenderable words
Rendered page 1 to file /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.tif
Stripped 249 unrenderable words
Rendered page 2 to file /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.tif
Null box at index 0
Error: Call PrepareToWrite before WriteTesseractBoxFile!!

=== Phase UP: Generating unicharset and unichar properties files ===
[Sun Jan 14 10:19:20 CST 2018] /usr/local/bin/unicharset_extractor --output_unicharset /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.unicharset --norm_mode 1 /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.box
Failed to read data from: /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.box
Wrote unicharset file /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.unicharset
[Sun Jan 14 10:19:20 CST 2018] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.unicharset -O /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.unicharset -X /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.xheights --script_dir=tesseract-ocr/langdata
Loaded unicharset of size 3 from file /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.unicharset
Setting unichar properties
Setting script properties
Writing unicharset to file /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.unicharset

=== Phase E: Generating lstmf files ===
Using TESSDATA_PREFIX=tesseract-ocr/tessdata
[Sun Jan 14 10:19:20 CST 2018] /usr/local/bin/tesseract /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.tif /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0 lstm.train tesseract-ocr/langdata/chi_sim/chi_sim.config
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Page 1
Failed to read boxes from /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.tif
Page 2
Deserialize header failed: /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.lstmf
Failed to read training data from /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.lstmf!
Page 3
Deserialize header failed: /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.lstmf
Failed to read training data from /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.lstmf!
ERROR: /tmp/tmp.KxphgKYS8k/chi_sim/chi_sim.Impact_Condensed.exp0.lstmf does not exist or is not readable

**Comment by Shreeshrii** [comment] 2018-01-14 16:32
Impact font probably does not support Chinese script. Hence there are large
number of unrenderable words on each page.
Use a font that supports your script.

Also note that tesstrain.sh only creates training data from the first three
pages of text.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by KevinZhuYF** [comment] 2018-01-14 16:34
So....what is your suggestion of Font type at this step?

**Comment by KevinZhuYF** [comment] 2018-01-14 16:40
so....can I use the same font type which is used in training step?

**Comment by huanpenglee** [comment] 2018-01-15 04:52
换个中文字体试试
Try another font please. for example  simsun.

**Comment by KevinZhuYF** [comment] 2018-01-15 15:29
Hmm...wait, if my target font is STZhongsong, I should use it to train the data and I need to use another similar font to evaluate the training?

**Comment by huanpenglee** [comment] 2018-01-16 03:36
是的，训练字体和评估字体建议使用不同的，这样才能测试模型的泛化能力。如果训练集和测试集都使用同样的字体，结果肯定是拟合的很好，那这样的评估还有什么意义。建议流程是选择多个中文字体进行训练，然后选择一个其他字体进行评估。

**Comment by Rajat1409** [comment] 2018-04-27 07:53
still getting getting this error

-e
=== Starting training for language 'hin'
-e [Fri Apr 27 13:21:33 IST 2018] /usr/local/bin/text2image --fonts_dir=/Users/ReveriePC/Library/Fonts --font=Aparajita Bold Italic --outputbase=/var/folders/b_/kz0byg9j4mv9snmglhny3d_80000gp/T/font_tmp.XXXXXXXXXX.btO1NzLv/sample_text.txt --text=/var/folders/b_/kz0byg9j4mv9snmglhny3d_80000gp/T/font_tmp.XXXXXXXXXX.btO1NzLv/sample_text.txt --fontconfig_tmpdir=/var/folders/b_/kz0byg9j4mv9snmglhny3d_80000gp/T/font_tmp.XXXXXXXXXX.btO1NzLv
-e
=== Phase I: Generating training images ===
-e Rendering using Aparajita Bold Italic
-e [Fri Apr 27 13:21:35 IST 2018] /usr/local/bin/text2image --fontconfig_tmpdir=/var/folders/b_/kz0byg9j4mv9snmglhny3d_80000gp/T/font_tmp.XXXXXXXXXX.btO1NzLv --fonts_dir=/Users/ReveriePC/Library/Fonts --strip_unrenderable_words --leading=32 --char_spacing=0.0 --exposure=0 --outputbase=/var/folders/b_/kz0byg9j4mv9snmglhny3d_80000gp/T/tmp.JHxdRWug/hin/hin.Aparajita_Bold_Italic.exp0 --max_pages=0 --font=Aparajita Bold Italic --text=../langdata/hin/hin.training_text
-e ERROR: /var/folders/b_/kz0byg9j4mv9snmglhny3d_80000gp/T/tmp.JHxdRWug/hin/hin.Aparajita_Bold_Italic.exp0.box does not exist or is not readable
-e ERROR: /var/folders/b_/kz0byg9j4mv9snmglhny3d_80000gp/T/tmp.JHxdRWug/hin/hin.Aparajita_Bold_Italic.exp0.box does not exist or is not readable

**Comment by Rajat1409** [comment] 2018-04-30 04:31
Tried with just `Aparajita`, same error!

**Comment by Shreeshrii** [comment] 2018-04-30 05:09
Do you have the font in --fonts_dir=/Users/ReveriePC/Library/Fonts --font=Aparajita 

Try to rebuild font cache and try.

fc-cache -vf

Do other devanagari fonts work with same training text?

**Comment by Rajat1409** [comment] 2018-04-30 05:50
Yes, fonts are in that directory .

Tried rebuilding font cache , it said : "fish: The file '/Users/ReveriePC/Library/Fonts' is not executable by this user"

It isn't working for any other devanagari fonts. 

I am building it in a mac-os ? do I need to change some config ?

**Comment by Rajat1409** [comment] 2018-04-30 07:15
Tried on ubuntu machine , working  !

**Comment by Naojen** [comment] 2018-07-21 16:57
shree please help me out. I got an error that says  " Unrecognized argument --linedata_only--noextract_font_properties" when i try create the training data
the command that i used is
  /usr/share/tesseract-ocr/./tesstrain.sh \
--fonts_dir  /usr/share/fonts \
--lang	ben \
--linedata_only\
--noextract_font_properties \
--langdata_dir	/home/jennil/Desktop/pro/langdata-master/ben\
--tessdata_dir /usr/share/tesseract-ocr/4.00/tessdata –output_dir 
 /home/jennil/Desktop/pro/output/ben_output\
--fontlist  “Lohit Bengali”

please someone hep me out

**Comment by rajulg78** [comment] 2019-06-04 11:01
Hi @Shreeshrii ,

I am unable to extract the lstm component from eng.traineddata in tessdata_best. I have tried a lot but unable to gain any success in this. Could you help me please.

**Comment by Shreeshrii** [comment] 2019-06-04 12:07
What command did you try? What error do you get?

**Comment by rajulg78** [comment] 2019-06-04 12:46
I have downloaded eng.traineddata from wget https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata as mentioned in https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#creating-training-data.

I tried the following command ./src/training/combine_tessdata -e tessdata/eng.traineddata \
  ~/tesstutorial/finetuning/eng.lstm and got the message that their is no lstm component.
and got these:

17:lstm:size=11689099, offset=192
18:lstm-punc-dawg:size=4322, offset=11689291
19:lstm-word-dawg:size=3694794, offset=11693613
20:lstm-number-dawg:size=4738, offset=15388407
21:lstm-unicharset:size=6360, offset=15393145
22:lstm-recoder:size=1012, offset=15399505
23:version:size=80, offset=15400517

I don't know what is going wrong over here.

**Comment by Shreeshrii** [comment] 2019-06-04 16:17
```
cd tesseract/tessdata
mkdir best
cd best
wget https://github.com/tesseract-ocr/tessdata_best/raw/master/eng.traineddata
```

This will put eng.traineddata in   tesseract/tessdata/best 

You are extracting from  tessdata/eng.traineddata 

```
./src/training/combine_tessdata -e tessdata/eng.traineddata ~/tesstutorial/finetuning/eng.lstm 
```
