### ISSUE TITLE
Tesseract hangs

### ISSUE THREAD

**Issue by vmato** [tesseract-ocr/tesseract#3960] opened 2022-11-09 05:29 UTC
### Environment

* **Tesseract Version**: 

tesseract 5.2.0
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.37+apng : libtiff 4.4.0 : zlib 1.2.12 : libwebp 1.2.4
 Found OpenMP 201811
 Found libarchive 3.6.1 zlib/1.2.12 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.2
 Found libcurl/7.85.0 OpenSSL/1.1.1o zlib/1.2.12 libpsl/0.21.1 (+libidn2/2.3.3) libssh2/1.10.0 nghttp2/1.48.0

* **Platform**: 
FreeBSD hostname.com 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64

### Current Behavior:

Tesseract hangs without any result. Hanged process even can not be killed.
Commands like ` tesseract anyimage.png stdout` or ` tesseract -l eng+rus anyimage.png stdout`

### Expected Behavior:

Tesseract works (produces result and exits)

**Comment by stweil** [comment] 2022-11-09 07:06
Did you install the Tesseract which is provided by FreeBSD?

Can you run it with a debugger and get a stack trace when it is hanging? Or build it from source and debug the hanging process?

**Comment by vmato** [comment] 2022-11-10 07:35
Yes, Tesseract is from binary packages (pkg install tesseract-5.2.0_1)

It's not possible to attach debugger or dump process with kill -QUIT.
Related discussion https://forums.freebsd.org/threads/process-hangs-in-run-state-and-can-not-be-killed-or-debugged.87035/

**Comment by amitdo** [comment] 2022-11-10 09:00
>Commands like tesseract anyimage.png stdout or tesseract -l eng+rus anyimage.png stdout

Does this hang happen with any image (as the name of the image indicates)?

Does this hang happen with this command:

`Tesseract /path/to/myimage.png /path/to/output_filename_without_extension`
?

**Comment by amitdo** [comment] 2022-11-10 09:08
You can also try to prepend this to the tesseract command:

`OMP_THREAD_LIMIT=1`

**Comment by amitdo** [comment] 2022-11-10 09:21
Another thing I just noticed.

According to your `tesseract -v` output, tesseract does not detect any SIMD instruction. not even SSE4.1. How old is your machine? Do you run this in the cloud? or locally inside a VM? Did you somehow disabled SIMD?

**Comment by stweil** [comment] 2022-11-10 09:25
That's indeed very strange because any amd64 platform should at least show support for SSE 4.1.

**Comment by amitdo** [comment] 2022-11-10 12:03
>any amd64 platform should at least show support for SSE 4.1

First 64-bit CPU from AMD came out in 2003, a few years before SSE4.1 was introduced.

https://en.wikipedia.org/wiki/X86-64

https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level#background_of_the_x86_64_microarchitecture_levels

https://www.phoronix.com/news/GCC-11-x86-64-Feature-Levels

https://www.phoronix.com/news/LLVM-12-Clang-12-Feature-Over

**Comment by vmato** [comment] 2022-11-14 05:41
Following trace may give additional info:
https://forums.freebsd.org/attachments/log_tail-txt.15069/

**Comment by amitdo** [comment] 2022-11-14 05:42
The discussion in the FreeBSD forum indicates the issue is related to OpenMP.

>OMP_THREAD_LIMIT=1
Didn't get any visible changes

It's not clear how you used this environment variable.

You need to do either of these:

>`OMP_THREAD_LIMIT=1 Tesseract in.png output_name`

Or

>`export OMP_THREAD_LIMIT=1`
>` Tesseract in.png output_name`

**Comment by stweil** [comment] 2022-11-14 17:38
> According to your `tesseract -v` output, tesseract does not detect any SIMD instruction. not even SSE4.1. 

That's a bug in Tesseract (fixed in commit adbefa83160c42371e7a4b0cf16a16a3aff26b08) which also caused bad performance for recognition and training on FreeBSD.

**Comment by vmato** [comment] 2022-11-16 05:52
Looks very strange but now tesseract started working.

This happened before any software or OS updates.
So I can only suppose there was update of provider's virtualization software or something like that

**Closed** 2022-11-16 08:39 UTC
Labels: process hangs
