### ISSUE TITLE
Clustering error: Matrix inverse failed with error 8.82272

### ISSUE THREAD

**Issue by sherrylee2013** [tesseract-ocr/tesseract#1757] opened 2018-07-06 03:46 UTC
cntraining veng.tr
Reading veng.tr ...
Clustering ...
Clustering error: Matrix inverse failed with error 8.82272

MAC OS

**Comment by amitdo** [comment] 2018-07-06 08:29
Duplicate of #771, #1111

**Closed** 2018-07-06 09:00 UTC
Labels: duplicate

**Comment by yahengqi** [comment] 2019-03-18 15:12
mftraining -F font_properties -U unicharset eng_my.unicharset eng_my.engfont.exp0.tr

Reading eng_my.engfont.exp0.tr ...
Bad properties for index 3, char 2: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 4, char 0: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 5, char 1: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 6, char 9: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 7, char 7: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 8, char W: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 9, char :: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 10, char 5: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 11, char 8: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 12, char 3: 0,255 0,255 0,0 0,0 0,0
Bad properties for index 13, char B: 0,255 0,255 0,0 0,0 0,0
Clustering error: Matrix inverse failed with error 1.26432
Clustering error: Matrix inverse failed with error 1.19818
Clustering error: Matrix inverse failed with error 1.05027
Clustering error: Matrix inverse failed with error 1.08535
Clustering error: Matrix inverse failed with error 19.0322
Clustering error: Matrix inverse failed with error 2.19076
Clustering error: Matrix inverse failed with error 13.0772
Clustering error: Matrix inverse failed with error 1.10794
Warning: no protos/configs for sh0007 in CreateIntTemplates()
Warning: no protos/configs for sh0008 in CreateIntTemplates()
Warning: no protos/configs for sh0009 in CreateIntTemplates()
