### ISSUE TITLE
!int_mode_:Error:Assert failed:in file weightmatrix.cpp, line 244

### ISSUE THREAD

**Issue by msute** [tesseract-ocr/tesseract#3069] opened 2020-07-22 10:13 UTC
hi！ i meet  the question！how can i solve？ my tesseract version is 4.0.  i want to train the chi_sim.traineddata
i tried to train the eng and number, it's all this kind of mistake!

msute@ubuntu:~/Desktop/jTessBoxEditor/tesseract-ocr$ lstmtraining --debug_interval -1 --max_iterations 800 --continue_from='/home/msute/Desktop/jTessBoxEditor/tesseract-ocr/chi_sim.lstm' --model_output='/home/msute/Desktop/jTessBoxEditor/tesseract-ocr/trainingoutput' --train_listfile='/home/msute/Desktop/jTessBoxEditor/tesseract-ocr/chi_sim.training_files.txt' --traineddata='/home/msute/Desktop/jTessBoxEditor/tesseract-ocr/chi_sim.traineddata'
Loaded file /home/msute/Desktop/jTessBoxEditor/tesseract-ocr/chi_sim.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Continuing from /home/msute/Desktop/jTessBoxEditor/tesseract-ocr/chi_sim.lstm
Loaded 1/1 pages (1-1) of document /home/msute/Desktop/jTessBoxEditor/tesseract-ocr/name.test.exp0.lstmf
Iteration 0: ALIGNED TRUTH : 惠娟潘墩镇镐源志学韩瑞峰男女壹贰叁肆伍陆柒捌玖拾源村
Iteration 0: BEST OCR TEXT : 惠娟潘墩镇镐源志学韩瑞峰男女壹武叁肆伍陆柴捌玖拾源村
File /home/msute/Desktop/jTessBoxEditor/tesseract-ocr/name.test.exp0.lstmf page 0 :
!int_mode_:Error:Assert failed:in file weightmatrix.cpp, line 244
Segmentation fault (core dumped)

**Comment by amitdo** [comment] 2020-07-26 04:57
Duplicate of #1573.

**Closed by amitdo** 2020-07-26 04:57 UTC

**Comment by msute** [comment] 2020-07-27 08:28
> [＃1573的](https://github.com/tesseract-ocr/tesseract/issues/1573)副本。

what‘s your mean?

**Comment by amitdo** [comment] 2020-07-27 18:28
Someone already reported about this issue before.

[See issue 1573](https://github.com/tesseract-ocr/tesseract/issues/1573)

Use the a traineddata file from the [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) repo for training.

**Comment by msute** [comment] 2020-07-28 10:10
> Someone already reported about this issue before.
> 
> [See issue 1573](https://github.com/tesseract-ocr/tesseract/issues/1573)
> 
> Use a traineddata file from the [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) repo for training.
yes，my file source from this website. but it still made this mistake. i just want to combine my traineddata and this source.  train more font.

**Comment by msute** [comment] 2020-07-28 10:22
> Someone already reported about this issue before.
> 
> [See issue 1573](https://github.com/tesseract-ocr/tesseract/issues/1573)
> 
> Use a traineddata file from the [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) repo for training.

yes，my file from this website. but it still made this mistake. i just want to combine my traineddata with this  source. train more font.

**Comment by amitdo** [comment] 2020-07-28 20:49
>yes，my file from this website

This error message indicates that you are training with integer model(tessdata_fast) instead of float model (from tessdata_best).

What the size of your chi_sim.traineddata file?

**Comment by msute** [comment] 2020-07-29 01:47
> > yes，my file from this website
> 
> This error message indicates that you are training with integer model(tessdata_fast) instead of float model (from tessdata_best).
> 
> What the size of your chi_sim.traineddata file?

What size?  how can i kown my traineddata size?  If i use the method from this photo, can i solve this error message?  Thank you for your patience
![image](https://user-images.githubusercontent.com/52910627/88746866-1e254700-d180-11ea-8d62-a91b0a0b8e0e.png)
