### ISSUE TITLE
Unnecessary gap between the lines

### ISSUE THREAD

**Issue by Nisfan** [tesseract-ocr/tesseract#2179] opened 2019-01-22 11:13 UTC
I am using tesseract dotnet wrapper 3.05  [https://github.com/charlesw/tesseract](https://github.com/charlesw/tesseract) to construct html using using bbox coordinate from image pdf (converted by ghostscript).

I have used the latest version of tesseract with tsv argument to demonstrate the issue

PDF to image 
`gswin64c.exe -dNOPAUSE -q -r300x300 -sDEVICE=tiffg4 -dBATCH -sOutputFile=d:\file.tif my.pdf`

Tried using  
`tesseract d:\\file.tif d:\\psm-6 -l eng --psm 6 tsv`

with
tesseract 4.0.0 Release

![image](https://user-images.githubusercontent.com/22009890/51531521-adeb8600-1e63-11e9-9bce-89e8fe2843bb.png)

Output

>5	21	1	1	14	1	415	2267	437	56	91	unpatentability
5	21	1	1	14	2	876	2266	54	44	96	of
5	21	1	1	14	3	949	2267	88	43	96	the
5	21	1	1	14	4	1062	2266	261	56	95	plaintiffs
5	21	1	1	14	5	1349	2267	165	48	96	claim,
5	21	1	1	14	6	1543	2267	122	56	96	they
5	21	1	1	14	7	1688	2267	131	43	96	have
5	21	1	1	14	8	1844	2270	93	40	96	not
5	21	1	1	14	9	1958	2267	220	43	96	violated
4	21	1	1	15	0	415	2407	742	57	-1	
5	21	1	1	15	1	415	2408	247	55	96	patented
5	21	1	1	15	2	683	2408	177	56	96	rights,
5	21	1	1	15	3	886	2407	40	43	96	if
5	21	1	1	15	4	942	2421	114	43	96	any,
5	21	1	1	15	5	1083	2421	74	30	96	as:
3	21	1	2	0	0	567	2547	1499	57	-1	
4	21	1	2	1	0	567	2547	1499	57	-1	
5	21	1	2	1	1	567	2548	67	51	89	“a)
5	21	1	2	1	2	716	2548	291	43	87	Nuziveedu
5	21	1	2	1	3	1055	2548	172	43	96	sowed
5	21	1	2	1	4	1275	2548	153	43	96	seeds
5	21	1	2	1	5	1476	2547	55	44	96	of
5	21	1	2	1	6	1571	2548	133	43	96	their
5	21	1	2	1	7	1750	2551	316	53	96	proprietary
**3	21	1	3	0	0	566	2619	1499	56	-1	
4	21	1	3	1	0	566	2619	1499	56	-1 <- extra line**	
5	21	1	3	1	1	566	2622	176	40	96	cotton
5	21	1	3	1	2	765	2622	237	40	96	varieties
5	21	1	3	1	3	1028	2619	265	56	96	alongside
5	21	1	3	1	4	1319	2619	88	43	96	the
5	21	1	3	1	5	1430	2621	313	54	96	Transgenic
5	21	1	3	1	6	1769	2621	77	41	96	Bt.
5	21	1	3	1	7	1877	2620	188	42	96	Cotton
**3	21	1	4	0	0	566	2689	138	43	-1	
4	21	1	4	1	0	566	2689	138	43	-1 <- extra line** 	
...

I tried with other page segment as well but same result

**Comment by amitdo** [comment] 2020-05-01 13:09
Duplicate of #2155.

**Closed by amitdo** 2020-05-01 13:09 UTC
Labels: layout-analysis
