### ISSUE TITLE
TessBaseAPI Init failed with datapath param contain CJK character

### ISSUE THREAD

**Issue by annidy** [tesseract-ocr/tesseract#4167] opened 2023-12-06 08:10 UTC
### Current Behavior

`fopen` does not support utf8 by default on Windows, anywhere use it will failed if not English path. ex. "C:\测试\tessdata"

### Suggested Fix

support UNICODE on the Windows platform

### Operating System

Windows 11, Windows 10

**Comment by amitdo** [comment] 2023-12-06 09:19
Duplicate of #3709.

**Closed by amitdo** 2023-12-06 09:19 UTC
