### ISSUE TITLE
Segmentation fault on some platforms / with some compilers when processing image with latest revision

### ISSUE THREAD

**Issue by kbrajwani** [tesseract-ocr/tesseract#3361] opened 2021-03-23 08:41 UTC
The latest push is working fine but when image is blury or have some noise it can't able to pass the image. it shows Detected 12 diacritics . The previous version was working fine with my images.

intallation
!apt-get install python-dev libxml2-dev libxslt1-dev antiword unrtf poppler-utils pstotext tesseract-ocr 
!sudo apt-get install libenchant1c2a
!sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel
!sudo apt-get update
# !sudo apt-get install tesseract-ocr
!sudo apt install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
!fc-cache -vf
!apt-get install libtesseract-dev libleptonica-dev pkg-config
!pip install pytesseract pdf2image
!tesseract -v

download image
!wget https://i.pinimg.com/originals/e1/82/03/e182036ad97b14eb4b9db05d43484b0e.jpg

Tesseract cmd
!tesseract " e182036ad97b14eb4b9db05d43484b0e.jpg " "out"

Tesseract Open Source OCR Engine v5.0.0-alpha-20201231-417-g2d805 with Leptonica 
Estimating resolution as 845 
Detected 12 diacritics
Result
out.txt file is empty. i also checked with other images. i think the latest push have some issues.
------------------------

### Environment

* **Tesseract Version**:  tesseract 5.0.0-alpha-20201231-417-g2d805
* **Platform**:  ubuntu 18.04 google colab 

### Suggested Fix: downgrade to last tesseract 5 version tesseract 5.0.0-alpha-20201231-246-gfe61.

can you tell me how can i downgrade to last tesseract 5 version tesseract 5.0.0-alpha-20201231-246-gfe61 ?

**Comment by Shreeshrii** [comment] 2021-03-23 08:49
@AlexanderP FYI re: PPA

**Comment by Shreeshrii** [comment] 2021-03-23 09:41
I tested on 2 different systems with tesseract built from source, different commits from the one mentioned above. I get OCR result in both cases.

```
 tesseract -v
tesseract 5.0.0-alpha-20201231-237-g51a21
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found NEON
 Found OpenMP 201511
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1
 Found libcurl/7.58.0 NSS/3.35 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
```

```
tesseract -v
tesseract 5.0.0-alpha-20201231-467-gdcde
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found OpenMP 201811
```

**Comment by Shreeshrii** [comment] 2021-03-23 09:52
I can confirm the error at commit https://github.com/tesseract-ocr/tesseract/commit/205cd32184dfb3b9c4ad28681405babf76dbd7d0

```
(kraken) ubuntu@tesseract-ocr:~/TEST$ tesseract -v
tesseract 5.0.0-alpha-20201231-417-g2d805
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found OpenMP 201811
(kraken) ubuntu@tesseract-ocr:~/TEST$ tesseract e182036ad97b14eb4b9db05d43484b0e.jpg -
Detected 51 diacritics
Segmentation fault
(kraken) ubuntu@tesseract-ocr:~/TEST$
```

**Comment by kbrajwani** [comment] 2021-03-23 10:05
Hey @Shreeshrii , Till the issue will be fixed can you tell me how can I built tesseract from the source with the commit that you are saying. 
Thanks

**Comment by Shreeshrii** [comment] 2021-03-23 10:24
See 

- https://github.com/tesseract-ocr/tessdoc/blob/master/Compiling-%E2%80%93-GitInstallation.md
- https://github.com/tesseract-ocr/tesseract/blob/master/.github/workflows/autotools.yml

**Comment by kbrajwani** [comment] 2021-03-23 11:09
Hey Shree,
i have already tried to build from socurce but always stuck into it.

os : ubuntu 18.04
gcc version 7.5.0 

Command is make
```src/ccmain/par_control.cpp: In member function ‘void tesseract::Tesseract::PrerecAllWordsPar(const std::vector<tesseract::WordData>&)’:
src/ccmain/par_control.cpp:57:21: error: found ‘:’ in nested-name-specifier, expected ‘::’
     for (auto &blob : blobs) {
                     ^
src/ccmain/par_control.cpp:57:16: error: ‘blob’ has not been declared
     for (auto &blob : blobs) {
                ^~~~
src/ccmain/par_control.cpp:57:28: error: qualified-id in declaration before ‘)’ token
     for (auto &blob : blobs) {
                            ^
src/ccmain/par_control.cpp:57:28: error: expected ‘=’ before ‘)’ token
src/ccmain/par_control.cpp:60:3: error: expected ‘;’ before ‘}’ token
   } else {
   ^
src/ccmain/par_control.cpp:60:3: error: expected primary-expression before ‘}’ token
src/ccmain/par_control.cpp:60:3: error: expected ‘;’ before ‘}’ token
src/ccmain/par_control.cpp:60:3: error: expected primary-expression before ‘}’ token
src/ccmain/par_control.cpp:60:3: error: expected ‘)’ before ‘}’ token
src/ccmain/par_control.cpp:60:3: error: expected primary-expression before ‘}’ token
src/ccmain/par_control.cpp:57:5: error: expected iteration declaration or initialization
     for (auto &blob : blobs) {
     ^~~
Makefile:5375: recipe for target 'src/ccmain/libtesseract_la-par_control.lo' failed
make[2]: *** [src/ccmain/libtesseract_la-par_control.lo] Error 1
make[2]: Leaving directory '/content/tesseract'
Makefile:8262: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/content/tesseract'
Makefile:2782: recipe for target 'all' failed
make: *** [all] Error 2```
Thanks

**Comment by Shreeshrii** [comment] 2021-03-23 11:34
Yeah, I reported that as issue https://github.com/tesseract-ocr/tesseract/issues/3360

Try one of the combinations from https://github.com/tesseract-ocr/tesseract/blob/master/.github/workflows/autotools.yml
those are working.

**Comment by Shreeshrii** [comment] 2021-03-23 11:35
Or after git clone

```
git reset --hard <old commit which works>
```

**Comment by AlexanderP** [comment] 2021-03-23 11:57
Hi. In ppa version downgraded to 5.0.0 ~ git5149-fe614c60

**Comment by Shreeshrii** [comment] 2021-03-23 12:00
@AlexanderP Thanks!

@kbrajwani Try with the PPA again and if issue is fixed, please close this.

**Comment by AlexanderP** [comment] 2021-03-23 12:04
@Shreeshrii Still in build status

**Comment by egorpugin** [comment] 2021-03-23 12:09
@kbrajwani

Get the latest gcc from ppas. Or try to install g++-8, g++-9 or g++-10 from ubuntu repos.

**Comment by stweil** [comment] 2021-03-23 12:42
> I can confirm the error at commit [205cd32](https://github.com/tesseract-ocr/tesseract/commit/205cd32184dfb3b9c4ad28681405babf76dbd7d0)

How did you build Tesseract to reproduce the issue? I don't get it with my default builds.

**Comment by Shreeshrii** [comment] 2021-03-23 13:55
```
COMPILER=clang++-11
$COMPILER --version

./autogen.sh

sudo rm -rf bin/$COMPILER
mkdir -p bin/$COMPILER
cd bin/$COMPILER

### export CXXFLAGS="-O3 -maltivec -mabi=altivec -mcpu=power8 -mtune=power8 -fopenmp -pthread -Wl,--no-as-needed"
../../configure --enable-openmp --disable-graphics --disable-shared --with-tensorflow=no --disable-debug  --disable-opencl "CXX=$COMPILER" 'CXXFLAGS=-g -O2'

make training -j 4
sudo make install -j 4
sudo make training-install
```

```
uname -a
Linux tesseract-ocr 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:23 UTC 2021 ppc64le ppc64le ppc64le GNU/Linux
```

**Comment by kbrajwani** [comment] 2021-03-23 14:23
Thank you all
The old ppa version fix my issue.

**Comment by stweil** [comment] 2021-03-23 14:51
@Shreeshrii, I had to apply commit 264dfb36859b3383c1337306d3825a1fcf3edc64 to compile on ppc64le with clang++-10 (Ubuntu bionic). And the resulting `tesseract` had no problem with the test image.

**Comment by stweil** [comment] 2021-03-23 15:23
>  The old ppa version fix my issue.

... but it does not fix latest revisions from Git. So this issue is still open.

**Comment by Shreeshrii** [comment] 2021-03-23 16:18
@stweil It is working with the latest git revision - your commit 264dfb3.

```
(kraken) ubuntu@tesseract-ocr:~/TEST$ tesseract -v
tesseract 5.0.0-alpha-20201231-475-gf97e
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found OpenMP 201811

(kraken) ubuntu@tesseract-ocr:~/TEST$ uname -a
Linux tesseract-ocr 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:23 UTC 2021 ppc64le ppc64le ppc64le GNU/Linux


(kraken) ubuntu@tesseract-ocr:~/TEST$ tesseract e182036ad97b14eb4b9db05d43484b0e.jpg - --psm 6
Sample of a Correctly Aligned 1500 Health Insurance Claim Form
ie +
[ER §
HEALTH INSURANCE CLAIM FORM £
[ro aa
es Qe [Jr (Jranwan JER oR Jo 1
MEMBER, IMA MMDD YY “[] +X] |SAME
paso] inal I
Awows Ja :
Sos (an asa (1) H

Tm Te wR ooo
A—— Te pee &
se weit fe —— :
inn ws 4 =
SRE Le 5
iio ha i vs OO
EE ET as a ig
1M. REFERRING PROVIDER _ | 1. ou ©
ps
(eps 1 |
fr
EL Br ES TT + z
Er nt a hin)
Bwoovy| od xooxixe SE
ON ni
SE Se ii
3 ci
of en we pel
a IL ay 18
Or ue in all FE PA a
ty ete smn eee 1M. PROVIDER
A ANVTOWN Wi 3555-1234
A 34s
2 MMDDgCYY Ee) pron
TT Tey PERERA Eee
(kraken) ubuntu@tesseract-ocr:~/TEST$
```

**Comment by stweil** [comment] 2021-03-23 16:28
I now get a fatal error with clang-11 on Ubuntu hirsute:

```
root@sweil-tesseract:~/tesseract/build# ./tesseract e182036ad97b14eb4b9db05d43484b0e.jpg -
Detected 51 diacritics
Assertion failure at kmp_runtime.cpp(6833): __kmp_dflt_team_nth <= __kmp_dflt_team_nth_ub.
OMP: Error #13: Assertion failure at kmp_runtime.cpp(6833).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
Aborted (core dumped)
```

The error is triggered by the code in src/lstm/fullyconnected.cpp:150.

So it seems to occur only with OpenMP and certain compiler or libomp versions.

**Comment by stweil** [comment] 2021-03-23 16:54
> I now get a fatal assertion with clang-11 on Ubuntu hirsute

That fatal assertion also occurs with tag `5.0.0-alpha-20201231`. Maybe that libomp-11 1:11.0.1-2 is really broken as the error message indicates. For my last test I used these commands:

```
./autogen.sh
./configure --enable-openmp --disable-graphics --disable-shared --enable-debug CC=clang-11 CXX=clang++-11 'CXXFLAGS=-g -O0'
make tesseract
./tesseract e182036ad97b14eb4b9db05d43484b0e.jpg -
```

So it looks like the original issue was fixed (see comment above) and the assertion is caused by libomp and otherwise unrelated to Tesseract code. Therefore I close the issue again.

**Closed by stweil** 2021-03-23 16:54 UTC
