### ISSUE TITLE
tesseract 4 --oem 0 baseline error with rotated pages

### ISSUE THREAD

**Issue by mhechthz** [tesseract-ocr/tesseract#2086] opened 2018-11-28 16:54 UTC
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by mhechthz** [comment] 2018-11-28 17:07
Hello,

I recently installed Tesseract 4.0 tesseract-ocr-w64-setup-v4.0.0.20181030.exe on my Win7 System. To check the page orientation I used the old OCR method, i. e. --oem 0 since it is much faster than LSTM, and hocr output. With the information of textangle I rotated the tiff files if necessary an than did LSTM-OCR and produced an overlayed PDF.

With the new Tesseract version I get always no textangle information if the page is rotated by 180 degree and no text is recognized. The same is unfortunately for LSTM where also no text is recognized.

Are there any chages or errors? How to get text orientation if 180 degree rotated?

**Comment by amitdo** [comment] 2018-11-28 17:48
Please provide:

* `tesseract -v` output.
* The full command you used.

**Comment by mhechthz** [comment] 2018-11-28 17:54
tesseract.exe "image.tif" "image.tif_ocr" --oem 0 -l deu+eng hocr

By the way: using psm option is useless because rotation by eg. 10 degree (from scanning) is recognized as 0 degree.

**Comment by amitdo** [comment] 2018-11-28 18:09
What the output in the terminal?

Can you provide the image?

**Comment by mhechthz** [comment] 2018-11-30 07:16
I meanwhile uninstalled the version I used
https://digi.bib.uni-mannheim.de/tesseract/tesseract
-ocr-w64-setup-v4.0.0.20181030.exe and went back tu the last beta
https://digi.bib.uni-mannheim.de/tesseract/tesseract
-ocr-w64-setup-v4.0.0-beta.4.20180912.exe that does the job. Unfortunately
I don't have the output anymore but the hocr files from both tesseract
versions for a 180 degree rotated page (see attachement: the one with
textangle 180 is the beta and the one without is the "stable" release, I
also added the tif file as jpeg because tiff is to large for your server
and was rejected). Is this sufficient? The output on the shell was
inconspicuous.



Am Mi., 28. Nov. 2018 um 19:10 Uhr schrieb Amit D. <notifications@github.com

**Comment by zdenop** [comment] 2018-11-30 07:52
Can you provide image for testing?

**Comment by mhechthz** [comment] 2018-11-30 08:29
Well you can take any image that is rotated by 180 degree, since it happens for any document with rotated pages.

**Comment by zdenop** [comment] 2018-12-02 12:04
image for testing:
![phototest-r180](https://user-images.githubusercontent.com/574156/49339470-79f99e80-f632-11e8-9f0e-56f6b9982f6b.png)
`tesseract phototest-r180.png - `

produce:
```
"Xo} Aze| sy} 1ano0 padwinl Bop umoiq
┬ąaInb 8y "xoj Aze| sy} son0 padwn(
Bop umoiq oinb ay) "xoy Aze| ayy Jeno
padwn( Bop umougq oInb sy xoy Aze|
8y} Jano padwinl Bop umouq yoinb sy
ÔÇťJewloy oyl Jo

sadA} |le uo s)I10m )l i 88S puE 8pod 190
3y} 1881 0} 1xa} Julod Z| 4o 10| ÔéČ s siy)
```

**Comment by amitdo** [comment] 2018-12-02 14:56
I guess this test will fail:
https://github.com/tesseract-ocr/tesseract/blob/master/unittest/osd_test.cc

**Comment by christoph1703** [comment] 2019-11-14 18:22
Any news on this? It's still broken in 5.00 Alpha (installed from Ubuntu PPA).

**Comment by amitdo** [comment] 2019-11-15 04:51
Duplicate of #2062

**Comment by amitdo** [comment] 2020-05-14 02:35
@mhechthz

You need to add `--psm 1` to the command.

https://github.com/tesseract-ocr/tesseract/commit/ecfee53bac5

**Closed by amitdo** 2020-05-14 02:35 UTC
Labels: bug
