### ISSUE TITLE
Specific file causes error

### ISSUE THREAD

**Issue by qm3ster** [tesseract-ocr/tesseract#1849] opened 2018-08-19 19:10 UTC
### Environment

* **Tesseract Version**: v4.0.0-beta.4-37-g115f from the PPA
* **Platform**: Linux 4.17.0-14.1-liquorix-amd64 liquorix 4.17-10ubuntu1~bionic (2018-08-14) x86_64

### Current Behavior:
A particular file, produced by extracting images from a PDF scanned by an HP_Officejet_Pro_8620_6B729F causes an error on a particular page.
```
pdfimages -j scan.pdf scanpic
ls *.jpg -1 > jpgs
tesseract jpgs out -l rus+eng pdf
```
Output:
```
Tesseract Open Source OCR Engine v4.0.0-beta.4-37-g115f with Leptonica
Page 0 : scanpic-000.jpg
Page 1 : scanpic-001.jpg
Page 2 : scanpic-002.jpg
contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 509
scan.sh: line 5: 22627 Segmentation fault      (core dumped) tesseract jpgs out -l rus+eng pdf
```
It really seems like it's something visual about the image that it doesn't like and not the encoding, because converting the image doesn't help:
```
pdfimages -j scan.pdf scanpic
convert scanpic*.jpg convert.png
ls *.png -1 > pngs
tesseract pngs out -l rus+eng pdf
```
Output:
```
Tesseract Open Source OCR Engine v4.0.0-beta.4-37-g115f with Leptonica
Page 0 : convert-0.png
Page 1 : convert-1.png
Page 2 : convert-2.png
contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 509
Segmentation fault (core dumped)
```

**Comment by qm3ster** [comment] 2018-08-19 19:25
Yup, even if I rescan it.

**Comment by Shreeshrii** [comment] 2018-08-19 19:34
Please test separately with -l eng and -l rus to check that the problem is not related to multiple language invocation.

Also, check using the traineddata files from tessdata, tessdata_fast and tessdata_best and see whether you get same error with each.

**Comment by qm3ster** [comment] 2018-08-19 19:38
It does not fail with just `eng`, it fails with just `rus`. [This `rus` ](https://github.com/tesseract-ocr/tessdata/blob/c2b2e0df86272ce11be323f23f96cf656565ed41/rus.traineddata)
Will now test with `_fast` and `_best`

**Comment by amitdo** [comment] 2018-08-19 19:45
>contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 509

Seem like yet another duplicate of #1205.

**Comment by qm3ster** [comment] 2018-08-19 20:16
`rus_best` and `rus_fast` work. The problem is localized to the regular `rus`

**Comment by amitdo** [comment] 2018-08-19 20:29
It still the same bug...

https://github.com/tesseract-ocr/tesseract/issues/1205#issuecomment-364169774

**Comment by Shreeshrii** [comment] 2018-08-20 03:27
The file in tessdata repo has both the legacy and LSTM models and by
default maybe invoking --oem 2 which tries to use both together. There is a
known problem with that.

Please repeat your test with tessdata using --oem 1 with -l rus as well as
-l rus+eng.

Thanks.

**Comment by qm3ster** [comment] 2018-08-20 12:53
`--oem 1 -l rus` and `--oem 1 -l rus+eng` also work

**Comment by amitdo** [comment] 2018-08-20 13:10
>--oem 1 -l rus and --oem 1 -l rus+eng also work

This proves that the source of the bug is combining the results of two ocr engines, just like all the previous reports with the same error.

**Comment by Shreeshrii** [comment] 2018-08-20 13:27
@stweil Can we change the default in the code to not use --oem 2 even when legacy model is present? With tesseract 4, let it be always be --oem 1 by default. 

Let --oem 0 or --oem 2 be used only if a user requests it specifically.

Do you foresee any problems with this approach? It will eliminate a lot of user reports.

**Comment by stweil** [comment] 2018-08-23 05:25
Yes, we could redefine `--oem 3` to either use `--oem 1` (not by default, but only if LSTM traineddata is available, because otherwise models like `-l deu_frak` would fail) or `--oem 0`.

`--oem 2` then still would crash, so fixing that is still needed. I already spent some time on this, up to now without success.

**Comment by stweil** [comment] 2018-10-01 15:19
I suggest to continue the discussion and handling of this issue at #1205 and close this one as a duplicate.

**Closed by stweil** 2018-10-01 15:19 UTC
Labels: bug, duplicate
