### ISSUE TITLE
Compiler warning on macOS / Xcode

### ISSUE THREAD

**Issue by holtwick** [tesseract-ocr/tesseract#2120] opened 2018-12-15 20:18 UTC
### Environment

* **Tesseract Version**: master 4.0.0 (2018-12-15) 
* **Commit Number**: e398601bf51f92cf32bd60a577603ca18679973f
* **Platform**:  Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

### Current Behavior:

Linking emits warning: ld: warning: direct access in function 

    'ETEXT_DESC::ETEXT_DESC()' from file '/Users/dirk/Library/Developer/Xcode/DerivedData/PDFify-gupjnofvlgfzxcgjmgrshzovtgwn/Build/Intermediates.noindex/TesseractOCR.build/Debug/TesseractOCR-macOS.build/Objects-normal-tsan-ubsan/x86_64/G8Tesseract.o' to global weak symbol 'ETEXT_DESC::default_progress_func(ETEXT_DESC*, int, int, int, int)' from file '/Users/dirk/work/frameworks/tesseract/TesseractOCR/macos/lib/libtesseract.a(libtesseract_api_la-baseapi.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

### Expected Behavior:

No warning

### Suggested Fix:

Warning does not show up if following is commented out in ocrclass.h:

	ETEXT_DESC()
	  : count(0),
	    progress(0),
	    more_to_come(0),
	    ocr_alive(0),
	    err_code(0),
	    cancel(nullptr),
	    progress_callback(nullptr),
	    progress_callback2(&default_progress_func),
	    cancel_this(nullptr) {
	end_time = std::chrono::time_point<std::chrono::steady_clock,
	                                   std::chrono::milliseconds>();
	}

**Comment by zdenop** [comment] 2018-12-17 10:40
Do you get this error when building [tesseract described](https://github.com/tesseract-ocr/tesseract/wiki/Compiling#macos) way or when you try to use tesseract in other project?

**Comment by holtwick** [comment] 2018-12-17 10:58
I'm doing a custom build with https://github.com/holtwick/Tesseract-OCR. Steps to compile Tesseract in the repo are:

```
cd TesseractOCR
make platform=mac
```

In the code that uses this build it sets up the progress monitor like this:

```
ETEXT_DESC *_monitor; = new ETEXT_DESC();
```
 
Since the warning says: "This was likely caused by different translation units being compiled with different visibility settings." the compiler settings might also be interesting to know. They are also part of the Xcode project referenced before. Here is an extract:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/49557/50083102-f7a4d900-01f2-11e9-9e76-6e11255353f1.png">

**Comment by alexmanzer** [comment] 2019-02-27 07:54
I get the same compiler warning. Any news on this issue?

**Comment by amitdo** [comment] 2019-02-27 08:59
https://www.google.com/search?q=warning+%22direct+access+in+function%22++%22global+weak+symbol%22

**Comment by lqhart** [comment] 2020-03-10 01:38
how to solve this problem ? do you have any solution ?

**Comment by amitdo** [comment] 2020-05-18 02:44
@stweil, 

Why is this pinned?

The problem is related to compiler flag -fvisibility. It seems that the OP tries to link a **custum** libtesseracr with his program and the two has conflicting -fvisibility flags.

The issue is with two 3rd party software, not in tesseract code / build system.

**Comment by stweil** [comment] 2020-05-18 04:37
> Why is this issue pinned?

I don't remember why I pinned it more than a year ago. Maybe I wanted to make sure that the warning does not occur in the Tesseract build system for macOS, but never had the time to look for it.

Perhaps we should close it (and reopen it if there is such warning in our build, too).

**Comment by amitdo** [comment] 2020-05-18 14:08
My suggestions:
* Pin only major issues.
* For reminders to yourself, either use projects in this repo or create tesseract-todo repo under your username, with todo.md page.
* Another alternative for pinning issues is using labels like "Priority-1", "Priority-2" etc.

**Closed by amitdo** 2020-05-18 14:08 UTC
