### ISSUE TITLE
Creating ALTO [enhancement]

### ISSUE THREAD

**Issue by FoxKyong** [tesseract-ocr/tesseract#419] opened 2016-09-06 07:52 UTC
Are there any plans for creating ALTO support in tesseract? I was thinking about programming a module for it. I was searching some conversion tool but found nothing working. I need it to be working in linux terminal, I found just conversion tool from hOCR to ALTO but the output is wrong. It would be also better if tesseract would generate ALTO.

**Comment by stweil** [comment] 2016-09-06 08:31
Did you try https://github.com/UB-Mannheim/ocr-fileformat?

**Comment by FoxKyong** [comment] 2016-09-06 08:35
Yes I have and the generated ALTO isn't valid. It can't be imported to the software I use and also the validator ocr-validate says it's not valid.

**Comment by stweil** [comment] 2016-09-06 11:02
Could you please [create an issue for that project](https://github.com/UB-Mannheim/ocr-fileformat/issues) then and add more details about the problems which you encountered?

**Comment by jbreiden** [comment] 2016-09-06 17:49
I don't think there are any plans for a direct ALTO support. And I think it is a good idea. Recommend implementing in a separate file api/altorenderer.cpp rather than adding to api/baseapi.cpp.

**Comment by stweil** [comment] 2018-11-30 07:42
There is now initial support for ALTO output in latest Git master. I keep this issue open nevertheless until issue https://github.com/altoxml/schema/issues/54 was solved and more testing with Tesseract + ALTO was done.

**Comment by Shreeshrii** [comment] 2019-07-13 10:37
@stweil ResultIteratorTest shows that tesseract can identify superscripts, subscripts, small caps and drop caps.

Alto schema seems to support these - see
https://github.com/kermitt2/pdfalto/blob/master/schema/alto.xsd#L762

Does tesseract ALTO output include such Font styles?

**Comment by parkerngg** [comment] 2019-10-08 00:00
no no no!

**Comment by parkerngg** [comment] 2019-10-08 00:02
Duplicate of #78555

**Comment by amitdo** [comment] 2022-03-16 11:34
This feature request was implemented a long time ago.

**Closed by amitdo** 2022-03-16 11:34 UTC
Labels: feature request, output
