### ISSUE TITLE
unofficial installer will EMPTY PATH in Win10 x64

### ISSUE THREAD

**Issue by CeBkCn** [tesseract-ocr/tesseract#481] opened 2016-11-18 08:26 UTC
unofficial installer for windows for Tesseract 3.05-dev is available from Tesseract at UB Mannheim.
http://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-setup-3.05.00dev.exe
win10, x64, lastest update.

the installer will not just add path,it will EMPTY path.

**Comment by stweil** [comment] 2016-11-18 08:34
This is not an issue for https://github.com/tesseract-ocr/tesseract/issues. Nevertheless I can try to answer here.

I got a similar report per e-mail recently, but could not reproduce it. Could you tell me the previous value of `PATH` which was emptied by the installation? Do you need the option which claims to set `PATH`? It is disabled by default, so I suggest to use the default setting (which avoids the issue).

**Comment by CeBkCn** [comment] 2016-11-18 16:24
All values of PATH were emptied by the installation.
Maybe the installer alerted me ,or as you said it is disabled by default.
Maybe I click the "next" too fast cause I thought it's OK.
Fortunately,I opened the PowerShell before the installation,the change of PATH didn't refresh in the opened PowerShell,so that I can restore the values of PATH,or it will be a little trouble.

**Comment by stweil** [comment] 2016-11-18 16:28
How does your normal value of `PATH` look like? I need the value which you restored (or like it was before it was emptied) because the problem might be related to the length or the content of `PATH`.

**Comment by zdenop** [comment] 2016-11-18 20:02
AFAIK there is the limit for [system variable](https://blogs.msdn.microsoft.com/oldnewthing/20100203-00/?p=15083) - but I am not sure if this is a case also in Windows 10.
Anyway this is not tesseract project issues - so I am closing issue.

**Closed by zdenop** 2016-11-18 20:02 UTC

**Comment by CeBkCn** [comment] 2016-11-19 04:03
`C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python27\;C:\Program Files\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files (x86)\IDM Computer Solutions\UltraCompare;C:\Shorts;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\MySQL\MySQL Server 5.7\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\wamp64\bin\php\php7.0.10;C:\wamp64\bin\php\php7.0.10\ext;C:\Users\CeBk\AppData\Roaming\npm;C:\Users\CeBk\AppData\Local\Microsoft\WindowsApps;C:\Users\CeBk\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;`

that's all the values of PATH before the installation

**Comment by stweil** [comment] 2016-11-19 08:12
The NSIS installer (which is used for Tesseract) has a [limit of 1024 characters](http://nsis.sourceforge.net/Path_Manipulation). Your PATH is clearly longer, so it hits that limit. I think the simplest solution will be removing the PATH setting from the installer, so users cannot activate it.
