### ISSUE TITLE
Incorrect character coordinates

### ISSUE THREAD

**Issue by Luk164** [tesseract-ocr/tesseract#1810] opened 2018-07-31 07:23 UTC
------------------------

### Environment

* **Tesseract Version**: 4.0.0-beta.1-262-g555f
* **Platform**: Linux kali 4.16.0-kali2-amd64 #1 SMP Debian 4.16.16-2kali2 (2018-07-04) x86_64 GNU/Linux

### Current Behavior:
makebox output has multiple characters on 880 0 880 0 0 coordinates even though it is clear they are on different ones

### Expected Behavior:
characters in makebox output have correct coordiantes and two charcters should never exist on the same spot

### Suggested Fix:
check for multiple characters on the same coordinates?

**Comment by zdenop** [comment] 2018-07-31 07:49
1. Please post issue after using the latest code. Current code is 4.0.0-beta.4.
2. Without files that help to reduce your problem nobody will help you.

**Comment by Luk164** [comment] 2018-07-31 07:58
Ok, though this new version is not yet out in my repos and I dislike downloading externally.

**Comment by zdenop** [comment] 2018-07-31 08:06
But you can still provide files for reproducing problem - maybe somebody can test it with current code...

**Comment by Luk164** [comment] 2018-07-31 08:47
https://drive.google.com/file/d/1pVIkCvIe1QleUYRuOz3ecpassWWsCjGQ/view?usp=sharing
This is a picture I was taking text out of. The command: tesseract cropped_screen.png eng makebox

**Comment by amitdo** [comment] 2018-07-31 13:09
#1015

**Comment by zdenop** [comment] 2018-09-30 16:05
@Lud164: can you please once again share you test case? I got error that file does not exists...

**Comment by Luk164** [comment] 2018-09-30 18:54
@zdenop Sorry, I deleted it during cleaning, I no longer have it. I figured that by now nobody is gonna need it.
P.S.: It's Luk164, not Lud164 :)

**Comment by amitdo** [comment] 2018-10-06 18:41
From the description it looks like this issue is a duplicate of #1015,  #1192.

**Closed** 2018-10-07 19:39 UTC
