### ISSUE TITLE
Tesseract not rendering searchable PDF correctly in Arabic

### ISSUE THREAD

**Issue by Shadi-trpf** [tesseract-ocr/tesseract#3472] opened 2021-06-29 04:29 UTC
I'm using Tesseract v5.0.0-alpha.20210506 with Leptonica-1.78.0 on Windows 10, with the latest ara.traineddata. 

When using Tesseract in Arabic, I face 2 issues:
- exporting result at txt seems to be completely fine, and the result is better than any other OCR software I've ever used (image below)
<a href="https://i.postimg.cc/QF9PKyxN/2021-06-29-07-26-15-out-txt-Notepad.png" target="_blank"><img src="https://i.postimg.cc/QF9PKyxN/2021-06-29-07-26-15-out-txt-Notepad.png" alt="1"/></a>
- however, exporting into searchable PDF does not even recognize that Arabic is written right-to-left, with highlighting inside the PDF looking like this 
<a href="https://i.postimg.cc/34BbHM91/2021-06-29-07-17-08-out2-pdf-Foxit-Reader.png" target="_blank"><img src="https://i.postimg.cc/34BbHM91/2021-06-29-07-17-08-out2-pdf-Foxit-Reader.png" alt="2"/></a>
- Copying the text and pasting into notepad results in complete gibberish that's obviously rendered left-to-right 
<a href="https://i.postimg.cc/Mc1FdfQh/2021-06-29-07-17-23-listtt-txt-Notepad.png" target="_blank"><img src="https://i.postimg.cc/Mc1FdfQh/2021-06-29-07-17-23-listtt-txt-Notepad.png" alt="3"/></a>
- In addition, the file size bloats considerably. In this instance, the original PDF file was 20 mb, but after OCR it skyrocketed to 171 mb.

Thanks in advance.

**Comment by stweil** [comment] 2021-06-29 05:36
This is partially a duplicate of issue #238.

**Comment by amitdo** [comment] 2021-06-30 14:56
Which PDF viewer did you use? How does it look with other viewers?

**Comment by amitdo** [comment] 2021-08-16 08:51
No feedback. and as said already reported in other issues.

**Closed by amitdo** 2021-08-16 08:51 UTC
Labels: bug, duplicate, PDF, RTL
