### ISSUE TITLE
The 'Tesseract' able to recognize 'Arabic' words but not 'Arabic' numerals from scanned Image using Python

### ISSUE THREAD

**Issue by sawankumar94** [tesseract-ocr/tesseract#2955] opened 2020-04-23 10:14 UTC
Hello  All,

I'm using  'tesseract v5.0.0-alpha.20190708' with 'leptonica-1.78.0' on Windows 10 Pro to extract Arabic text with numerals from a scanned Image(attached). 

So, after running following Python Code:
text = str(((pytesseract.image_to_string(Image.open(filename),lang='ara')))) 

I can see that 'Tesseract' is able to recognize 'Arabic' words but not able to recognize  'Arabic' numerals.  I will attach the screen shot of the tesseract output too. 

Please help me, what needs to be done such that it recognizes 'Arabic' numerals too.  

Please find attached scanned Image here.
![Scanned_Image](https://user-images.githubusercontent.com/12645695/80087617-fa4ad780-8578-11ea-8b81-ec37d396b648.JPG)

Please find attached the screenshot of the tesseract output obtained from the above code.
![Tesseract_Output](https://user-images.githubusercontent.com/12645695/80087803-3d0caf80-8579-11ea-8988-3fc0c8618261.png)

Thank you!

**Comment by amitdo** [comment] 2020-04-24 00:44
Duplicate of many of other issues.

[arabic numerals](https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+is%3Aopen+arabic+numerals)
[arabic numbers](https://github.com/tesseract-ocr/tesseract/issues?q=is%3Aissue+is%3Aopen+arabic+numbers)

The issue is related to the data that were used for training Arabic. not to the tesseract program/library itself.

See tesseract-ocr/langdata#71, tesseract-ocr/langdata#72

**Closed by amitdo** 2020-04-24 00:44 UTC

**Comment by hadilaff** [comment] 2021-07-03 15:59
> Hello All,
> 
> I'm using 'tesseract v5.0.0-alpha.20190708' with 'leptonica-1.78.0' on Windows 10 Pro to extract Arabic text with numerals from a scanned Image(attached).
> 
> So, after running following Python Code:
> text = str(((pytesseract.image_to_string(Image.open(filename),lang='ara'))))
> 
> I can see that 'Tesseract' is able to recognize 'Arabic' words but not able to recognize 'Arabic' numerals. I will attach the screen shot of the tesseract output too.
> 
> Please help me, what needs to be done such that it recognizes 'Arabic' numerals too.
> 
> Please find attached scanned Image here.
> ![Scanned_Image](https://user-images.githubusercontent.com/12645695/80087617-fa4ad780-8578-11ea-8b81-ec37d396b648.JPG)
> 
> Please find attached the screenshot of the tesseract output obtained from the above code.
> ![Tesseract_Output](https://user-images.githubusercontent.com/12645695/80087803-3d0caf80-8579-11ea-8988-3fc0c8618261.png)
> 
> Thank you!

hello,can you tell me how you could read the data in arabic please

**Comment by amitdo** [comment] 2021-07-04 10:12
@hadilaff, please use our forum for asking questions about Tesseract's usage.

**Comment by hadilaff** [comment] 2021-07-04 21:50
> @hadilaff, please use our forum for asking questions about Tesseract's usage.

which forum?

**Comment by amitdo** [comment] 2021-07-04 22:17
https://groups.google.com/g/tesseract-ocr

**Comment by Frescoboy18** [comment] 2023-01-19 14:00
can you share your project as zip as I am working on the same thing but having several isssues.
