### ISSUE TITLE
Floating exception with -l equ 

### ISSUE THREAD

**Issue by Paul-Taylor-EU** [tesseract-ocr/tesseract#3732] opened 2022-01-25 11:19 UTC
### Environment

* **Tesseract Version**: 

NB I downloaded equ.testdata manually from the tesseract website and it may only be compatible with V4 not V5.

tesseract --version
tesseract 5.0.1-5-gad55c
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found SSE4.1
 Found OpenMP 201511
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1
 Found libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

* **Platform**: 

Linux 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:

tesseract Stolz3.tiff Stolz -l deu+equ  -c tosp_old_to_method=0
Detected 41 diacritics
Floating exception

Same result with just equ and not deu, also without -c...

No floating exception with just deu and not equ.

Adding -c tosp_old_to_method=0 was suggested by:

https://github.com/tesseract-ocr/tesseract/issues/3483

I have tried to upload Stolz3.tiff but can't see whether this has been done.

Here it is (temporarily) on my website:    http://paultaylor.eu/drafts/Stolz3.tiff

It is the third page of 

@article{StolzO:geoaia,
  title={Zur {G}eometrie der {A}lten,
     insbesondere {\"u}ber ein {A}xiom des {A}rchimedes},
  author={Stolz, Otto},
  journal={Mathematische Annalen},
  volume={22},
  number={4},
  pages={504--519},
  year={1883},
  publisher={Springer-Verlag}
}

converted from scanned pdf to tiff using

ghostscript -o /tmp/Stolz3.tiff -sDEVICE=tiffgray -r720x720 -g6120x7920 -sCompression=lzw ~/Stolz.pdf

**Comment by stweil** [comment] 2022-01-25 11:28
This looks like a duplicate of issue #3693.

**Comment by stweil** [comment] 2022-01-25 11:31
I propose to continue the discussion at the older bug report and close the issue here.

**Closed by stweil** 2022-01-25 11:31 UTC
Labels: duplicate
