### ISSUE TITLE
Error in pixReadStreamPng: spp == 1, cmap, trans array, invalid depth: 4

### ISSUE THREAD

**Issue by Stajor** [tesseract-ocr/tesseract#3458] opened 2021-06-18 07:27 UTC
tesseract can't read string from low resolution png image.

Platform: macOS 11.4
tesseract --version
```
tesseract 4.1.1
 leptonica-1.81.1
  libgif 5.2.1 : libjpeg 9d : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.0 : libopenjp2 2.4.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
```

cli command:  tesseract number.png output
```
Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Error in pixReadStreamPng: spp == 1, cmap, trans array, invalid depth: 4
``````

![number](https://user-images.githubusercontent.com/1831826/122523354-98bcb680-d01f-11eb-8365-4913682b894d.png)

**Comment by zdenop** [comment] 2021-06-18 12:32
@DanBloomberg: seems like a leptonica issue... Can you have a look?

**Comment by stweil** [comment] 2021-06-18 13:59
I can confirm that I get the same error on Linux and MacOS for [this image](https://user-images.githubusercontent.com/1831826/122523354-98bcb680-d01f-11eb-8365-4913682b894d.png).

**Comment by DanBloomberg** [comment] 2021-06-20 06:24
Should be fixed with the latest leptonica commit

**Comment by zdenop** [comment] 2021-06-20 11:45
thanks. It works for me (on windows).

**Closed by zdenop** 2021-06-20 11:45 UTC
Labels: leptonica
