### ISSUE TITLE
preserve_interword_spaces option not working on 4.00alpha

### ISSUE THREAD

**Issue by abieler** [tesseract-ocr/tesseract#781] opened 2017-03-23 07:51 UTC
I am running the same command line as for the 3.x versions with 

-c preserve_interword_spaces=1

as option. The resulting text does not preserve the white spaces, which it correctly did for the 3.x version.

Thanks
Andre

**Comment by MoinulJoje** [comment] 2017-03-29 15:59
I am also facing the same problem. After using "preserve_interword_spaces", there is actually no significant difference noticed between the normal OCR and "preserve_interword_spaces=1" parameterized OCR.
Is there any solution?

**Comment by mm-manu** [comment] 2017-05-16 14:14
Same problem here. "preserve_interword_spaces" has no effect.
Also many other parameters do not work in v4.0 :/

**Comment by s-asish** [comment] 2017-06-24 13:14
I have the same problem in version 4.0. I have tried with version 3.0.2 - It does not have this option.

**Comment by mingodad** [comment] 2017-08-14 10:03
I also noticed this problem and it seems related with the trained data, because if I use tesseract 4 with the trained data of 3.05 I do get the interword spaces.
```
#!/bin/sh
export PATH=$HOME/local/tesseract/bin:$PATH
export LD_LIBRARY_PATH=$HOME/local/tesseract/lib:$LD_LIBRARY_PATH
#ubuntu tesseract 3 trained data
export TESSDATA_PREFIX=/usr/share/tesseract-ocr
#export TESSDATA_PREFIX=$HOME/local/tesseract/share/tessdata
tesseract $*

#tesseract -l spa -psm 4 $1 scanned
#mytesseract -c preserve_interword_spaces=1 -l spa  $1 scanned
```

**Comment by amitdo** [comment] 2017-08-14 10:17
>I also noticed this problem and it seems related with the trained data, because if I use tesseract 4 with the trained data of 3.05 I do get the interword spaces.

With 4.00, If you don't use the --oem option, the default oem will be used:

>3    Default, based on what is available.

The traineddata for 3.05 does not have lstm data, so oem 3 in this case is equivalent to:

>0    Original Tesseract only.

**Comment by mingodad** [comment] 2017-08-18 09:21
Thanks for pointing out !
I dived on tesseract source code and found an almost solution to the preserve_interword_spaces problem, it seems that when transferring the words the spaces were not transfered see patch bellow.
With this patch the output is almost identical with the 3.05 version except for the missing spaces for the first column (need more research to see where the first/second word is transfered and why the spaces/blanks are not).
```
@@ -1329,11 +1329,11 @@ void PAGE_RES_IT::ReplaceCurrentWord(
   WERD_RES* input_word = word();
   // Set the BOL/EOL flags on the words from the input word.
   if (input_word->word->flag(W_BOL)) {
     (*words)[0]->word->set_flag(W_BOL, true);
   } else {
-    (*words)[0]->word->set_blanks(1);
+    (*words)[0]->word->set_blanks(input_word->word->space());
   }
   words->back()->word->set_flag(W_EOL, input_word->word->flag(W_EOL));
 
   // Move the blobs from the input word to the new set of words.
   // If the input word_res is a combination, then the replacements will also be
```

**Comment by Shreeshrii** [comment] 2017-08-21 15:13
Please create a PR.

**Comment by Shreeshrii** [comment] 2017-09-11 10:33
Checked with the proposed pr.

[toc-eng.txt](https://github.com/tesseract-ocr/tesseract/files/1292209/toc-eng.txt)
[toc-eng-space.txt](https://github.com/tesseract-ocr/tesseract/files/1292208/toc-eng-space.txt)
![toc](https://user-images.githubusercontent.com/5095331/30270531-835fa0c4-970a-11e7-8403-b3b21a217680.png)

Spaces are preserved now when using tesseract with `--oem 1 --psm 6 -l best/eng -c preserve_interword_spaces=1`

Here is the output:

```
1 First chapter                                   3
1.1 Section One                                 3
1.2 Section Two                                   3
1.3 Section Three                                  3

2 Last chapter                                     5
2.1 Section One                                 5
22 Section Two                                   5
2.3 Section Three                                  5
```

**Comment by mm-manu** [comment] 2017-09-14 14:53
Can't reproduce :/
I tried it with the python tesserocr wrapper like so:

> tess = PyTessBaseAPI(init=False, lang="eng", psm=PSM.SINGLE_BLOCK)
settings = {"preserve_interword_spaces": "1"}
tess.InitFull(lang="eng", oem=OEM.LSTM_ONLY, variables=settings)
tess.SetSourceResolution(300)
tess.SetPageSegMode(PSM.SINGLE_BLOCK)
img = Image.open("image.jpg")
tess.SetImage(img)
> print(tess.GetUTF8Text())

prints the text without preserved spaces :/

Also tried it through the command line as follows:

> tesseract image.jpg --tessdata_dir /usr/local/share/tessdata --oem 1 --psm 6 -l eng -c 
> preserve_interword_spaces=1

Gives me this error:

> tesseract: genericvector.h:713: T& GenericVector<T>::operator[](int) const [with T = char]: Assertion `index >= 0 && index < size_used_' failed.

I use the .traineddata files from https://github.com/tesseract-ocr/tessdata/tree/master/best

Any advice please? :)

**Comment by Shreeshrii** [comment] 2017-09-15 07:20
The fix was applied in https://github.com/tesseract-ocr/tesseract/commit/e62e8f5f802c0d8f3dd67da993327cdafaee9763

Build the new version and check.

**Comment by mm-manu** [comment] 2017-09-15 14:45
Thanks, it works!

**Comment by Shreeshrii** [comment] 2017-09-15 16:05
@zdenop You can close this. Thanks!

**Closed** 2017-09-15 16:10 UTC

**Comment by kylefoley76** [comment] 2020-12-19 04:34
It seems to me that you have to upgrade to tesseract 5.0 to get this solution to work.  But using a mac and using brew install tesseract, I can not upgrade to tesseract 5.0

**Comment by Shreeshrii** [comment] 2020-12-25 12:32
@kylefoley76  The spaces at beginning of line are not being recognized yet. See the image and result in https://github.com/tesseract-ocr/tesseract/issues/781#issuecomment-328490156
