### ISSUE TITLE
x_fsize always 0 in hocr-output since latest commit 

### ISSUE THREAD

**Issue by hnesk** [tesseract-ocr/tesseract#2110] opened 2018-12-07 12:28 UTC
### Environment

* **Tesseract Version**: 4.0.0-86-gbee8
* **Commit Number**: ad40131385541d7eacf313f2199e4b3fa1f3e345
* **Platform**: Linux jk-XPS-13 4.18.0-12-generic #13-Ubuntu SMP Wed Nov 14 15:17:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
With current git master version:
$ ~/bin/tesseract -v 
tesseract 4.0.0-86-gbee8
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE

$ ~/bin/tesseract --psm 3 --oem 0  -c tessedit_create_hocr=1 -c hocr_font_info=1 -l deu page.tif page-4.0.0-86-gbee8

In page-4.0.0-86-gbee8.hocr: "x_fsize 0" and "x_font" is missing completly:
`<span class='ocrx_word' id='word_1_1' title='bbox 253 248 365 292; x_wconf 89; x_fsize 0'>rung</span>`
 
### Expected Behavior:
With the current ubuntu version 4.0.0-beta.3-249-g607e:
$ tesseract -v
tesseract 4.0.0-beta.3-249-g607e
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
$ tesseract --psm 3 --oem 0  -c tessedit_create_hocr=1 -c hocr_font_info=1 -l deu page.tif page-4.0.0-beta.3-249-g607e

In page-4.0.0-beta.3-249-g607e.hocr: "x_fsize" and "x_font" have sensible values: 
`<span class='ocrx_word' id='word_1_1' title='bbox 253 248 365 292; x_wconf 89; x_font Times_New_Roman; x_fsize 56'>rung</span>`

### Suggested Fix:
review c9e85ab78fa61a86ec6e391e2e6a073f770617ea or ad40131385541d7eacf313f2199e4b3fa1f3e345 one of these commits fixed too much ;)

**Comment by hnesk** [comment] 2018-12-07 12:29
Testcase:
[page.zip](https://github.com/tesseract-ocr/tesseract/files/2657206/page.zip)

**Comment by amitdo** [comment] 2018-12-08 09:11
c9e85ab

` if (it_->word()) { `

should be: 
 if (it_->word() == nullptr) { `

**Comment by stweil** [comment] 2018-12-08 09:46
@hnesk and @amitdo, thank you for your reports and sorry for the regression. It is fixed now with commit 2c044df95998bc52e70fbcc1a5f0a2c97b931408.

**Comment by stweil** [comment] 2018-12-08 09:51
`x_fsize` is not written by default because the `hocr` config file sets `hocr_font_info 0`, so I assume most users won't notice the bug.

**Closed as completed** 2018-12-08 17:23 UTC
Labels: bug
